### ISSUE TITLE
Typo in Line 24 "253_The_Wailing_Caverns_pt.3.sql"

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#100]
Fix:
UPDATE creature SET spawndist = 5, MovementType = 1 WHERE guid IN (18679,18681,18680);

**Comment by Grz3s** [comment]
c'mon .... :)
youre faster than me :+1: 
https://github.com/unified-db/Database/commit/a219adfb31bbb58846e9b21129b570c27826f1d3
