### ISSUE TITLE
[Quest] Attack on Camp Narache!

### ISSUE THREAD

**Issue by alysher** [unified-db/Database#106]
game object 3076 doesnt give this quest(24857) atm, and chief hawkwind isnt involved with quest 24857

sql query to fix issue:

INSERT INTO `gameobject_questrelation` (`id`, `quest`) VALUES (3076, 24857);
INSERT INTO `creature_involvedrelation` (`id`, `quest`) VALUES (2981, 24857);

**Comment by Grz3s** [comment]
thx for report.
