### ISSUE TITLE
Oblivion Mage and Doomfire Destroyer(Sunwell Plateau)

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#11]
Happy New Year!
http://www.wowhead.com/npc=25597
Oblivion Mage(Only separate guid, not everything)
should channeling cast on Doomfire Destroyer.
http://www.wowhead.com/npc=25592
http://www.wowhead.com/npc=25592#screenshots:id=74600
http://www.wowhead.com/npc=25597#screenshots:id=74606
Screenshots confirm this.
EventAI EVENT_T_RECEIVE_EVENT and can not be used, may affect other guid Mage Oblivion that should not cast a spell on him.
What you need - to learn id spell and cast script write.
If spell has spell_script_target, 38 or 7 or 8 targets. Use EventAI can not, I have already explained above why.
Only if db_script_on_creature_movement. Create these two guid to waypoint, with the coordinates of this point must be equal to the spawn point. And the process - though this is a hack.

**Comment by Ulduar** [comment]
I asked a difficult question?

**Comment by Grz3s** [comment]
thx for your report. 
sor.... im busy with dk zone....
hmm ... ill check this ofc soon...
but everytime i hear 'channel spells'  i know there will be problem...
99% this spells cannot be inteurrpted... so creature that casts tchem ..wont react for any agrro :/
this is am sure core problem... same one that i had with tchem summoners in shawdowmoon valley

**Comment by Ulduar** [comment]
When aggro force them to cast Flame Buffet - through interrupt previous flag.
How are successful in finding?
@xfurry You do SD2 will not help here. You will not be able to make some sorts for Guido beings with the same entry.
