### ISSUE TITLE
[Wotlk] Quest: The hunt is on [#11794]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#116]
While doing the alliance quest in the Valiance Keep you need to use the item before you should be able to 'unmask' the npcs. But now you can talk to them before using the item, and you will instant-finish your objective, instead of having to fight them (they dont even start the small scene they used to make)

Quest information:
Vindicator Yaala wants you to use the Oculus of the Exorcist in three different locations in Valiance Keep to uncover and defeat Cult of the Damned members.
Quest:
http://www.wowhead.com/quest=11794/the-hunt-is-on
Quest item:
http://www.wowhead.com/item=35125/oculus-of-the-exorcist
Video:
https://www.youtube.com/watch?v=pLUzRDqLfeM

**Comment by Grz3s** [comment]
hey @Argonn 
Thank you for all reports... they will be fixed soon*
