### ISSUE TITLE
[Wotlk] Quest: Take no Chances [#11913]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#117]
When doing the alliance quest, you can keep burning the same stack of sacks over and over again. This shouldnt be able.

Quest description:
Wendy Darren wants you to use Wendy's Torch to burn 8 sacks of Farshire Grain.
Quest:
http://www.wowhead.com/quest=11913/take-no-chances
Quest item:
http://www.wowhead.com/item=35491/wendys-torch

**Comment by NeatElves** [comment]
+ double killcredit, spell 46574 in database and ACID
```sql
DELETE FROM `creature_ai_scripts` WHERE `id` = 2616101;
UPDATE creature_template SET AIName = '' WHERE Entry = 26161;
```
