### ISSUE TITLE
[Wotlk] Quest: Massacre At Light's Point [#12701]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#119]
When doing this quest, killing a single mob with the ships cannon will yield full xp (1500~ per kill). Granting you an easy level per 2-3minutes.

These mobs should not give any xp.

Quest:
http://www.wowhead.com/quest=12701/massacre-at-lights-point

NPC:
http://www.wowhead.com/npc=28834/scarlet-fleet-defender
http://www.wowhead.com/npc=28856/scarlet-fleet-guardian

**Comment by NeatElves** [comment]
```sql
UPDATE creature_template SET ExtraFlags = ExtraFlags|64 WHERE Entry IN (28834, 28856);
```
