### ISSUE TITLE
[Wotlk] NPC: Stonescythe Alpha [#16929]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#123]
The NPC Stonescythe Alpha in Hellfire Peninsula makes no use of his 'Defense' ability.

NPC:
http://www.wowhead.com/npc=16929/stonescythe-alpha#abilities [^]

Ability:
http://www.wowhead.com/spell=33896/desperate-defense [^]

**Comment by Grz3s** [comment]
fixed some time ago
