### ISSUE TITLE
[Wotlk] Quest: Boiling Blood  [#10538]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#125]
While doing the quest, you need to cast boiling blood into the cauldron, then after 2-3 seconds bugs should come out of the cauldron. This doesn't happen, but they do spawn when you pickup the quest (in the middle of the NPC area).

Quest:
http://www.wowhead.com/quest=10538/boiling-blood

Loot item:
http://www.wowhead.com/item=30425/bleeding-hollow-blood

Created item:
http://www.wowhead.com/item=30430/boiled-blood

Scarab:
http://www.wowhead.com/npc=21306/cursed-scarab

**Comment by Grz3s** [comment]
```quote
but they do spawn when you pickup the quest (in the middle of the NPC area).
```
this is effect of prev. quest... and its correct...

fix for 'boiling blood' will be added tomorrow ;)
