### ISSUE TITLE
[Wotlk] NPC: Crazed Mana-Wyrm [#26761] 

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#126]
The Crazed Mana-Wyrm is attackable, while the Crazed Mana-Surge aren't. They seem to be mixed up.

You can target both of them, but you agro and attack the Wyrm but not the Surge, which should be the other way around.

"These arcane wyrms are meant to be just part of the aesthetics of the Nexus and not something you're supposed to have to kill. In fact currently they're not attackable except by the other NPCs (blue dragons) in the dungeon."

Wyrm:
http://www.wowhead.com/npc=26761/crazed-mana-wyrm

Surge:
http://www.wowhead.com/npc=26737/crazed-mana-surge

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/e6e8081d6df0aaedc42e74f5fb9b5fb4c9f12b21
