### ISSUE TITLE
[Wotlk] Core: Ranged enemies not moving on LOS

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#127]
When the player pulls a mage/ranged NPC, and then move out of sight (behind a wall, pillar, door etc) the creature will enter a passive stance, and will remain onspot until the player who has agro on the mob moves back into LOS again.

This also happens on spellcasters being silenced, they will not move for the duration. So you cannot pull a spellcaster with silence.

**Comment by xfurry** [comment]
Well, this is kind of a generic issue for range scripts in eventAI.

**Comment by Argonn** [comment]
Could this be of any use?:

It appears there is a fix made for this:
http://cmangos.net/thread-503-post-41259.html#pid41259 

(original topic: https://github.com/cmangos/issues/issues/588

From the topic:
I found the cause for this behaviour:

Code:
case ACTION_T_COMBAT_MOVEMENT:
    //ignore no affect case
    if (m_isCombatMovement == (action.combat_movement.state != 0) || m_creature->IsNonMeleeSpellCasted(false))
        return;

this means that if a range event that is NOT repeatable (like in the geomancer script you provided) triggers while the npc is casting(which he almost always is), it will never start/stop combat movement

that's also why it didn't work in my little stream demonstration and worked on my tests with wastewander shadow mage, because they have repeatable combat movement events

I think all the combat movement events should be repeatable to prevent this and also support moving out of range multiple times.

lots of entries miss this:
SELECT * FROM creature_ai_scripts WHERE event_type = 9 AND event_flags & 1 = 0;

proposed fix:
UPDATE creature_ai_scripts SET event_flags = event_flags|1 WHERE event_type = 9;


So that means that the event is simply missing for most mobs, its worth testing.

Side-note: CMangos Admin (Schmoozerd) is against this solution, because it takes the logic to a database level instead of the scripts.

**Comment by xfurry** [comment]
I need to revisit that solution. It's quite some time and I forgot what was the conclusion.

**Comment by Argonn** [comment]
Is there anything like a priority list? Because things like this kinda wreck the game.

**Comment by xfurry** [comment]
well, I don't know for sure.
The last thing I heard about this was that people were supposed to test it and come back with some feedback.

**Comment by Argonn** [comment]
Is this anything we could test on apexwow.com ?
Could we just run the updates from the topic ? (https://github.com/krullgor/mangos-classic/commit/7feaf5b135c830d0989a538b30eb11a267be5f84) on a Wotlk brancht? Or do we need classic server for this to test.

**Comment by Grz3s** [comment]
looks like this problem has been fixed by ACID - added new action:
```sql
49   ACTION_T_DYNAMIC_MOVEMENT              EnableDynamicMovement           Enable dynamic movement behavior (1 = on; 0 = off)
```
All we need now to redo: all creatures who casts spells :D:D (43282 - creatures in templates)
anyone? :)

**Comment by adellaci** [comment]
@Grz3s 
I look into it, but I will have a few questions for you. First question which tables to I need to start looking at? This will give me a chance to learn a little more about the interrelationship.

**Comment by Grz3s** [comment]
... in progres...
pls check:
https://github.com/ACID-Scripts/WOTLK/commits/master

Ofc ... it will take lots of time.... and masive work need to be done to finisz this for entire world.
Anyway... issue here can be closed.
thanks for report
