### ISSUE TITLE
[Wotlk] NPC: Shirrak the Dead Watcher [#18371]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#128]
When fighting the boss in Auchenai Crypts, he will use his ability 'Focus Fire'. This ability will 'create' 3 dummy targets (infernals) to show where the boss will fire at. These should be flames.

FOCUS FIRE – Shirrak will emote “Shirrak the Dead Watchers focuses on (party member name)!” beneath that player a flare will appear, about 3 seconds later he will shoot 3 AoE blasts around flared location for 1600-1700 fire damage.

NPC:
http://www.wowhead.com/npc=18371/shirrak-the-dead-watcher

**Comment by AnonXS** [comment]
i think this is resolved now?
