### ISSUE TITLE
Patchwerk - need set corpse delay and respawntime delay.

### ISSUE THREAD

**Issue by ghost** [unified-db/Database#13]
http://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold
Patchwerk has Rank World_Boss - Because of this, his corpse removed for too long, plus it will ignore
respawntime in DB creature.
Analogic issue and more details provided here - https://github.com/TrinityCore/TrinityCore/issues/4146
I beg please read to the end.
Maybe in EventAI add ACTION_T_CORPSE_DELAY AND ACTION_T_SET_RESPAWNTIME and SCRIPT_COMMAND_CORPSE_DELAY AND SCRIPT_COMMAND_SET_RESPAWNTIME.
It is necessary. Otherwise you'll have to edit mangosd.conf, and this is bad, very bad. On the work of other creatures may have a negative impact.

**Comment by xfurry** [comment]
@Grz3s is already working on the DK zone fixes. I'm sure he will have this covered, once he gets to the final part.

**Comment by Ulduar** [comment]
@Xfurry Here not only the base, but also the core. Thank you for your participation, but please read again.

**Comment by xfurry** [comment]
Let's wait until @Grz3s looks at this issue and in the sniff. He will tell us what is the course of action.
If there will be core changes required, we'll work them out. :wink:

**Comment by Ulduar** [comment]
How long to wait. And it already could address this issue - and the details are provided, plus the link given.

**Comment by xfurry** [comment]
> How long to wait. And it already could address this issue - and the details are provided, plus the link given.

It will have to wait for as long as it's necessary. :wink: 
This is a fun project, so we don't set ourselves deadlines. The issue will be addressed soon.

**Comment by Ulduar** [comment]
Okay, sorry.

**Comment by Grz3s** [comment]
i did some research ... here...
and as i said before..."i dont see anything special here"
from sniff... u can see that he has 120secs... respawntime.( will add this ... with all updates for phase 265)
also... few facts about him:
- has no loot
- hes corpse despawns 8 secs after kill
so i can sugest simple fix (works in WoTLK):
```sql
DELETE FROM dbscripts_on_creature_death WHERE id = 31099;
INSERT INTO dbscripts_on_creature_death (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(31099,7,18,0,0,0,0,0x04,0,0,0,0,0,0,0,0,'despawn self');
```
We dont need to change anything in config

**Comment by xfurry** [comment]
Then, I think it's safe to assume that this solution can be applied to all such similar cases.

**Comment by Grz3s** [comment]
its not implemented yet...so why you.. closing this issue?
