### ISSUE TITLE
[Wotlk] Quest: A Spirit Guide [#9410] 

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#131]
When you follow your Ancestral Spirit Wolf Totem, when if gets attacked (by Boars of Birds or anything really) it will attack the enemy. But it will no longer follow its path, and will stay at your side as a 'hunter' pet.

Quest:
http://www.wowhead.com/quest=9410
Quest item:
http://www.wowhead.com/item=23669

**Comment by Grz3s** [comment]
@xfurry needed here ....
npc_ancestral_wolf in hellfire_peninsula.cpp
Wolf need react passive.... (shouldnt attack anything)...
thanks

**Comment by xfurry** [comment]
Will review this soonish.

Btw, I think I proposed some time ago some ACTIVE / PASSIVE behavior for scriptedAI and eventAI that can be enabled by DB or Acid.
Not sure if anybody tested that, but if you are still interested I can show you the patch.

**Comment by Grz3s** [comment]
sure.I'll be happy to test it

**Comment by xfurry** [comment]
There you go:

http://paste2.org/_8ItAE97d

**Comment by Ulduar** [comment]
Thanks for patch Xfurry, but he is useless. ACTION_T_CONTROL_ATTACK can be more flexibility.

**Comment by Ulduar** [comment]
Wolf has SD2 script.
Need add line
void AttackStart(Unit* /*pWho*/) override { }
Make React Passive. Not React on Aggro.

**Comment by Grz3s** [comment]
Ulduar is right here...
I cant use EAI -- if sd2 script is already used...
or...
i can redo.. completely quest... using waypoints + EAI..(but is there any sense?)

BTW:
i'll check this patch anyway...koz im sure i coould be useful sometimes...

**Comment by Ulduar** [comment]
You cannot redono with EAI, because:
1) EAI cannot have TARGET_SUMMONER_OR_OWNER.
2) db_script_on_creature_movement - don't have method GetPlayerForEscort for quest complete.

**Comment by Ulduar** [comment]
Add in 152 and 153 lines and enjoy!
``` CPP
void AttackStart(Unit* /*pWho*/) override { }
void MoveInLineOfSight(Unit* /*pWho*/) override { }
```

**Comment by Grz3s** [comment]
your path works fine...
:+1: 
lets see if @xfurry will add it ...
thx

**Comment by xfurry** [comment]
Will add.
