### ISSUE TITLE
[Wotlk] Quest: Marking the Path [#9391] 

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#132]
The beacons can be lit, time after time. Not giving any credits, so its a minor thing.

Quest:
http://www.wowhead.com/quest=9391/marking-the-path

**Comment by Grz3s** [comment]
can anyone else confirm this?
I checked it... and works perfectly fine... (credit is given to player on each object)

**Comment by Grz3s** [comment]
Invalid: Quest works fine.
