### ISSUE TITLE
[Wotlk] Talent: Missile Barrage [#44404]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#134]
This talent is bugged, as it DOES reduce the channel time, it also only deals halve the damage in total.

(testing on lvl 68)
While normal casting this spell:
Channel time: 5 seconds,
Missiles: 5
Damage: 5 x 490~ = 2500~

While casting this spell with Missile Barrage:
Channel time: 2.5 seconds,
Missiles: 2 (I guess 2.5 :8ball: )
Damage: 2 x 490~ = 1000~

This should not be a talent to nerf mages, this talent should still give 5 missiles but within half the time.

Tooltip:

> > Gives your Arcane Blast a 40% change, and your Arcane Barrage, Fireball, Frostbolt and FrostFire Bolt spells a 20% change to reduce the channeled duration of the next Arcane Missisles spell by 2.5 secs, reduce the mana cost by 100% and missiles will fire every .5 secs.

**Comment by al3xc1985** [comment]
argon i believe this is a core problem, and not db

Cheers

**Comment by Argonn** [comment]
After posting all bugs on the core git, they told me to post everything here. And that from here the issues will be divided according to system specific githubs.

**Comment by xfurry** [comment]
> i believe this is a core problem, and not db

It might be both, as the procs are stored in DB.
Anyway, it sounds complicated to fix, so any help is welcomed

**Comment by Argonn** [comment]
I made a report on the core github as well, lets get all the help we can.

**Comment by Grz3s** [comment]
fixed long time ago
