### ISSUE TITLE
[Wotlk] Core: Quest item looting while in party

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#137]
When you are in a party, and the other members have completed their quest objectives. You should be able to instant-loot the item from a corpse when it's not your turn to loot (group loot).

Now you have to wait for the player in turn, to open the loot window (they will not see the quest item! ) before you can loot the quest item. Before you cannot click the corpse for a loot window.

**Comment by Ulduar** [comment]
Core side - loot system.

**Comment by Grz3s** [comment]
yes ... we need to keep order... on this...
pls report core issues here:
https://github.com/cmangos/issues/issues
