### ISSUE TITLE
Madrigosa and Brutallus(Isle of Quel'Danas side, not in Sunwell Plateau)

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#14]
http://www.wowwiki.com/Madrigosa
http://www.wowhead.com/npc=25160/madrigosa#abilities
At the moment, this mini Event is not implemented.
Brutall has EventAI, but if Madrigosa make him a frosty blast, he becomes aggressive towards her. I think there is interference core need. Namely create EventAI action ACTION_T_SET_REACT_STATE (Passive, Defensive and Aggressive). This is required for many creatures. It also flies through waypoints and periodic taunt Brutallus.
http://www.wowhead.com/quest=11533/the-air-strikes-must-continue
On the official server, when we fly by taxi we see the battle of the Scourge and the Legion, flying by Brutallus, we see how Madrigosa flying around at the moment, it just flies in place.
Need script support.
P.S: How to add a label to the issue? Tell me please and thanks in advance.

**Comment by Rushor** [comment]
some more infos:
https://github.com/TrinityCore/TrinityCore/issues/12798

**Comment by Ulduar** [comment]
@Rushor Thank you of course, but there is a description of the battle in Sunwell Plateau, and I'm talking about the Isle of Quel'Danas.
Fight in Sunwell Plateau is almost completely implemented in SD2.

**Comment by xfurry** [comment]
I don't think that referring TC issues will help, since the core and DB is different than ours.

Yes, this event needs to be implemented, probably in a similar way as I did with the event inside the instance. It might work with DBscripts, but I'm not sure.

**Comment by Ulduar** [comment]
You can not do this with a db script without using a hack. Does not hack. Do not forget Brutallus should not attack Madrigosu all. But after hitting an icy blast it just moves forward a little and goes to the point of spawn, plus screaming - they say get down, I'll make you a worm dragon

**Comment by Ulduar** [comment]
I will try to recreate the memory event. But I need:
1)SCRIPT_COMMAND_SET_REACT_STATE and ACTION_T_SET_REACT_STATE in EventAI)
2)SCRIPT_COMMAND_SEND_AI_EVENT_TARGET and ACTION_T_SEND_AI_EVENT_TARGET (not around, and specifically without affecting Target buddy system)
Brutallus don't never attack Madrigosa and Madrigosa don't never attack Brutallus. REACT STATE - best solution (SD2 script - full hack this will be the case.)
http://www.wowhead.com/npc=25033/eredar-sorcerer
He also needs REACT STATE. He never enters the fray, has even more players. ACID script also needs to change.
http://www.wowhead.com/npc=25028/skeletal-ravager and 
http://www.wowhead.com/npc=25027/frenzied-ghoul
don't never should attack Eredar Sorcerer. SD2 script need? Lol.

**Comment by xfurry** [comment]
Let's stick to the topic....
It's always hard to understand what you are trying to say because, beside using Google translate, you are also mixing up a lot of things in one topic.

If you have a problem with the other npcs that are scripted in acid, please open an issue there.
I know that not all simple AI npcs are working as expected, but in order to fix this we need to have clear details.

**Comment by Ulduar** [comment]
``` quote
Let's stick to the topic....
```
They also belong to this topic.
``` quote
It's always hard to understand what you are trying to say because, beside using Google translate, you are also mixing up a lot of things in one topic.
```
I do not mix topics, they are relevant to the issue.
``` quote
If you have a problem with the other npcs that are scripted in acid, please open an issue there.
```
Because of the stupid restrictions I can not open issue in ACID - EventAI does not have necessary functions to fix it.
``` quote
I know that not all simple AI npcs are working as expected, but in order to fix this we need to have clear details.
```
I have given details and solutions. On all issues. But you do not listen to me again.

http://www.wowhead.com/npc=25033/eredar-sorcerer, http://www.wowhead.com/npc=25028/skeletal-ravager and http://www.wowhead.com/npc=25027/frenzied-ghoul
I repeat the question - three of them SD2 write? It is able that can not EventAI. Sorcecer spamming Flame Rock and everything. Skeletal Ravager and Frenzied Ghoul Possible write this
``` CPP
    void AttackStart(Unit* pWho) override
    {
        if (pWho->GetEntry() == NPC_EREDAR_SORCECER)
            return;

        ScriptedAI::AttackStart(pWho);
    }

```
This will offlike - enough for me and the eye to notice it.

**Comment by Ulduar** [comment]
Thanks to these innovations Schmoozerd Seems I had an idea how to make a script db through the whole thing.
https://github.com/cmangos/mangos-wotlk/commits/master?author=Schmoozerd
Create a path with the same coordinates. Need the truth SCRIPT_COMMAND_LOAD_PATH and modify ACTION_CHANGE_MOVEMENT (Waypoint movement side, add path)
Then remove Brutallus EventAI and add NullAI (their texts he says quietly thanks db script)
Or add Brutallus(Brutallus Must not have NullAI unfortunately) EXTRA_FLAG_NO_CALL_ATTACK(see http://cmangos.net/thread-6735.html)

**Comment by xfurry** [comment]
:confused:

**Comment by Ulduar** [comment]
:rofl

**Comment by Ulduar** [comment]
Does anyone have any data to implement?
I remember flying Madrigosa waypoints and at some period of time casts spell 45201 having 38 Target. But the truth is this negative spell and Brutallus begins to attack on Madrigosa.
Need ACTION_T_SET_REACT_STATE. Or Extra Flag NO_CALL_ATTACK)
