### ISSUE TITLE
[Wotlk] Quest: Help Tavara [#9586]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#140]
The priest quest help tavara should send you out to heal Tavara, but when you find her, you cannot heal her (you will heal yourself, even when you target her).

Also she is 100% hp on spawn it seems.

Quest:
http://www.wowhead.com/quest=9586/help-tavara

**Comment by Grz3s** [comment]
thanks for this report...
as u can see I'm in progress... of fixing Draeneis zone 
This will be fixed soon. (i'll check all classes)

**Comment by Argonn** [comment]
Do you want us to pre-test a zone, report the issues here before you start on a starting-zone? This could win you some time.

**Comment by Rushor** [comment]
most issues cannot be reported from videos etc. most of the stuff can only be gathered from sniffs from official servers

**Comment by Grz3s** [comment]
@Rushor i have enough sniffs from this ;)
