### ISSUE TITLE
[Wotlk] NPC: Ziz [#17486]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#141]
It is not possible to buy a "Mining Pick" from Ziz in the Draenei starting area.

NPC:
http://www.wowhead.com/npc=17486/ziz

**Comment by Grz3s** [comment]
thx for report
fix will come soon

**Comment by Grz3s** [comment]
actualy what "pick axe" you looking for?
shouldnt be "Mining Pick" ? instead?

**Comment by Argonn** [comment]
Aye yes, sorry for the mix up. It should be the default 'Mining Pick'.

**Comment by Grz3s** [comment]
hmm i see no problem with this:
![wowscrnshot_111115_185815](https://cloud.githubusercontent.com/assets/2374069/11099996/72de9224-88a6-11e5-80cb-65701cb66b48.jpg)

can you pls check again?

**Comment by Argonn** [comment]
For some reason, the lad now has 4 pages of items, including the mining pick... I could have sworn he only had 3 pages yesterday... Will close this, and will check the stream of yesterday to make sure I'm just getting blind.
