### ISSUE TITLE
[Wotlk] NPC: Venture Co. Saboteur [#17278]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#142]
This NPC uses the ability 'Thorns'. Which is/seems incorrect they should have a 'Torch burn' ability (hence their torches).

**Comment by Grz3s** [comment]
yes ... :)
Also just for your knowledge ... this one should be reported on ACID issues.
but.
i also having fun with fixing these things... so im accepting tchem all ...here ;)
i'll fix this soon :)

**Comment by Argonn** [comment]
Is there a clear 'instruction' as to what to report where?

**Comment by Grz3s** [comment]
pls look here
https://github.com/unified-db/Database/issues/139#issuecomment-155536444

**Comment by Argonn** [comment]
Super! thnx for that explanation. I will try to put some effort into classifying the bugs before posting.
