### ISSUE TITLE
[Wotlk] Quest: Search Stillpine Hold [#9565]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#144]
This quest, does not work as intended. There is no movement between the 2 factions (moonkins and furborls) there are corpses everywhere, but everyone is fine with each other it seems.

There are no troops to enter the hold when you accept the quest (could be sheer luck in the movie)

Quest:
http://www.wowhead.com/quest=9565/search-stillpine-hold

Youtube:
https://www.youtube.com/watch?v=MfXeLd1Xsyc

**Comment by Argonn** [comment]
Also there appears to be a 'Gromsblood' spawn-node next to the end of this quest (next to the blood crystal)

**Comment by Grz3s** [comment]
Stillpine Hold had major update in recent commits:
- all quests related were corrected
- all spawns and movements corrected
