### ISSUE TITLE
[Wotlk] NPC: Training Dummies [#30527]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#147]
Training dummies, as found in Exodar, DK starting area etc, can be hit (and die, which shouldn't be possible) by players to test they rotation and damage per second.

When in combat, the dummy will follow the player (and attack the player) as any normal monster.
You can also range-reset the dummy forcing him to walk (slide) back to his starting position.
- [ ] Training dummies can die by taking damage
- [ ] Training dummies follow the player
- [ ] Training dummies fight back

NPC:
www.wowhead.com/npc=30527/training-dummy

**Comment by Argonn** [comment]
I tried some NPC flags, but I found myself limited by knowledge on this subject to properly fix it.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/blob/61c7161a1069f93948b8b4d80b501d9358b4844c/src/server/scripts/World/npcs_special.cpp#L1408

**Comment by Ulduar** [comment]
``` QUOTE
 Training dummies can die by taking damage
```
ACTION_T_SET_INVINCIBILITY_HP_LEVEL solved this problem.
``` QUOTE
 Training dummies follow the player
```
ACTION_REACT_PASSIVE (not implemented in off repo) can be solved problem.
``` QUOTE
 Training dummies fight back
```
Need check for damage take - if 0 on 10 seconds - can be evade.

**Comment by Argonn** [comment]
@Ulduar is this set in the database or in the script?

**Comment by Rushor** [comment]
can be done with db

**Comment by Ulduar** [comment]
``` QUOTE
can be done with db
```
Can be done without SD2.
On Current State you can use only this.
``` SQL
-- Creature id: 30527
UPDATE creature_template SET AIName='EventAI' WHERE entry=30527;
DELETE FROM creature_ai_scripts WHERE creature_id=30527;
INSERT INTO creature_ai_scripts VALUES 
('3052701','30527','11','0','100','0','0','0','0','0','42','1','0','0','20','0','0','0','21','0','0','0','Training Dummy - Set Damage = 0, Stop Auto Attack, Stop Combat Movement.');
```

**Comment by xfurry** [comment]
> ACTION_REACT_PASSIVE (not implemented in off repo) can be solved problem.

Not implemented because people didn't provide feedback on my patch...
As per your last quote on the forum you say http://cmangos.net/thread-6897-post-44768.html#pid44768 :

> Thanks for patch Xfurry, but he is useless. ACTION_T_CONTROL_ATTACK can be more flexibility.


Anyway I think that if we add this command, then we can safely say that we can fix this by Acid.

I already provided patch here: http://paste2.org/_8ItAE97d

**Comment by Grz3s** [comment]
hey @xfurry ... 
Can u pls update your patch...  gives some errors (out of date?)
and i'll check it ASAP ;)
thx

**Comment by xfurry** [comment]
Will update soon.
