### ISSUE TITLE
[Wotlk] Quest: Death's Challenge [#12733]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#148]
When you challenge two other death knights at the same time, one of them will fight you and the other one will bug out (your PVP will also remain on the ground next to him for some time) the flag will be gone after some time, but the NPC doesn't accept any challenges at that point

Quest:
http://www.wowhead.com/quest=12733/deaths-challenge

As to be read on wow-head, it should work on 2 at the same time:
>>By Zentaxio (1,516 – 1·5) on 2008/12/25 (Patch 3.0.3)		
if you want to go the hard way, you can actualy challenge 2 of those.. But its way harder than 1 at time
Simply just find a place with 2 of those initiate and duel both (Very fast) 
Try it if you think you are good eneough :-)
Last edited by Zentaxio on 2008/12/25 (Patch 3.0.3)

**Comment by Grz3s** [comment]
this script is made by sd2... and if smth is not right ,,, must be reported there:...
but be serious... is this a real problem?:) ... (personaly i think ..that we have worst things to fix) :)
but let @xfurry to comment on this ...

**Comment by Argonn** [comment]
Yeah sorry, not everything I report is major issue, but there is no 'severity' or anything to put on a report.
Things like LOS on casters looks like a bigger problem.

**Comment by xfurry** [comment]
It might be actually a  problem.
I need to investigate. Let's keep the ticket open here, until I have a chance to look at this.

**Comment by Argonn** [comment]
Takes around 10-12 people messing this quest up, and no DK can complete the quest

**Comment by xfurry** [comment]
> Takes around 10-12 people messing this quest up, and no DK can complete the quest

Problem is that there is no easy way to fix this.
There is no aura, or something that can tell us if the player already started the event.

Maybe only to check if the GO 191126 owner is the player.

**Comment by Grz3s** [comment]
This is ScriptDev2 issue ...and scnnot be fixed here.
sory
