### ISSUE TITLE
Bonechewer Messenger

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#15]
http://www.wowhead.com/npc=21244/bonechewer-messenger
Need add waypoint, also when you reach the point of what I do not remember, there are four sinister catcher and attacking it. Plus, it must be accompanied by four more
http://www.wowhead.com/npc=21245/bonechewer-marauder four marauder follow for messenger
follow. If the player intervenes and carefully destroy demons, they will continue to move in and out despawned after the leave can not remember at what point - I was there for a long time and I do not remember all the details, remember that they begin their movement as much in Terrokar Forest. I think they definitely need to add more and flag CREATURE_FLAG_EXTRA_ACTIVE.
wowhead quote:
``` quote
Apparently, these spawn at about 67,54 in Terokkar Forest, just outside and to the east of the large central building in Bonechewer Ruins. I found this out the hard way (and in the process also discovered that they can swim, joy). They're guarding a single Bonechewer Messenger (http://www.wowhead.com/?npc=21244). The group of 5 travel to and along the road until they reach about 23,29 in Shadowmoon Valley, where they're summarily slaughtered by elite Wrathwalkers. Lovely.
```
http://www.wowhead.com/npc=19740/wrathwalker#comments
Wrathwalker - npc, their spawns four and they attack Bonechewer.
``` quote
Actually, the Wrathwalkers despawn very shortly after appearing, and the Bonechewers continue to about 30,46 at Illidari Point and despawn.
```

**Comment by Grz3s** [comment]
thx for report
will fix this soon..

**Comment by Grz3s** [comment]
fixed.
in: https://github.com/unified-db/Database/commit/0f04164420fcaab1f80c53a98c7ab99e9789b520

**Comment by Ulduar** [comment]
```quote
If the player intervenes and carefully destroy demons, they will continue to move in and out despawned after the leave can not remember at what point
```
Thanks, but point despawn missing. If player help destroy wrathstalkers, Messenger and followers should resume movement.

**Comment by Grz3s** [comment]
have no details.... about this.. so if someone will get it... then will add missing part( not that important)

**Comment by Ulduar** [comment]
``` quote
have no details.... about this.. so if someone will get it... then will add missing part( not that important)
```
For this and sufficient eye. http://cmangos.net/thread-6692.html and http://cmangos.net/thread-6697-post I implemented without sniff at all. But I am limited in functions to implement and do not give it better. Forever I hear the same thing - write in SD2.
``` quote
Why don't you want to just submit a nice SD2 patch for the whole event. :wink:
This would make our life much easier, and will fix the event much faster.
```
@xfurry Why do I SD2, if I could do without it. Yes, and feedback to wait for years.

**Comment by Grz3s** [comment]
its not a problem to add anything... but i need  correct data to see what happens there..... (even vid will be enough)
