### ISSUE TITLE
[Wotlk] Zone: Dalaran [#4395]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#151]
When walking around Dalaran, i came across a couple of strange things.

A swimming ghost in the floor + a wandering ghost troll:
http://apexwow.com/img/screenshots/WoWScrnShot_111715_195341.jpg

The wandering ghost troll seems to be everywhere + the quest giver gives every quest:
http://apexwow.com/img/screenshots/WoWScrnShot_111715_195459.jpg

Afsaneh Asrar seems to be a descendant of the genies:
http://apexwow.com/img/screenshots/WoWScrnShot_111715_195852.jpg

**Comment by Grz3s** [comment]
hi
yes ... Dalaran needs same thing what was just done with "The Exodar" 
soon*

**Comment by Grz3s** [comment]
fixed some time ago
