### ISSUE TITLE
[WotLK] Quest ID 11307 - Field Test

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#153]
(Howling Fjord) The NPC's "Plagued Dragonflayer Vrykul" in Halgrind are not exist or the
Item ID 33621 - Plague Spray doesen't work on the existing NPC's

**Comment by Grz3s** [comment]
thanks for report
fixed:
https://github.com/ACID-Scripts/WOTLK/commit/7edfd291639a18803bbd687fcf300b672666187a
