### ISSUE TITLE
[Wotlk] Quest: The amphitheater of anguish Yggdras [#12932] 

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#159]
This quest, can be accepted twice (as quest starting option) and both will not summon the first boss.

Screen-cast (Current version):
https://youtu.be/WxoYjD_i8gw

Screen-cast(Live version):
https://www.youtube.com/watch?v=Eadoan6YSwA

Quest:
http://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/ff9c715695bce7dbc67256709f68b1e8958daaa8

**Comment by al3xc1985** [comment]
well 9 more, and we are done here with the issues
