### ISSUE TITLE
[Wotlk] Quest: Ring of blood [#9962]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#160]
This following NPCs are missing their abilities, making them more or less tank-spank encounters.

- [x] Brokentoe:
NPC: http://www.wowhead.com/npc=18398/brokentoe
Ability: http://www.wowhead.com/spell=32023/hoof-stomp

- [x] Murkblood Twin:
NPC: http://www.wowhead.com/npc=18399/murkblood-twin
Abilities: 
http://www.wowhead.com/spell=32319 
http://www.wowhead.com/spell=14873

- [x] Rokdar the Sundered Lord:
NPC: http://www.wowhead.com/npc=18400/rokdar-the-sundered-lord
Abilities: 
http://www.wowhead.com/spell=31389
http://www.wowhead.com/spell=15976
http://www.wowhead.com/spell=16727

- [x] Skra'gath
NPC: http://www.wowhead.com/npc=18401/skragath#abilities
Abilities: 
http://www.wowhead.com/spell=32322
http://www.wowhead.com/spell=29299 
http://www.wowhead.com/spell=16429,
Also all his 'damage reducing abilities won't work (like http://www.wowhead.com/spell=34336/damage-reduction-holy)

- [x] Warmaul Champion
NPC: http://www.wowhead.com/npc=18402/warmaul-champion#abilities
Abilities: 
http://www.wowhead.com/spell=31403
http://www.wowhead.com/spell=32323
http://www.wowhead.com/spell=15708
http://www.wowhead.com/spell=17963

- [x] Mogor Hero of the Warmaul
NPC: http://www.wowhead.com/npc=18069/mogor
Abilities:
http://www.wowhead.com/spell=16033
http://www.wowhead.com/spell=39529
http://www.wowhead.com/spell=28747
http://www.wowhead.com/spell=15982
http://www.wowhead.com/spell=32343

**Comment by adellaci** [comment]
Argonn

Looking through the current database (2/27/16)(creature_template_spells) i have found these entries

    Brokentoe: npc=18398
    Ability: Hoof Stomp spell=32023

    Murkblood Twin: npc=18399
    Abilities: Mutilate: spell=32319
                  Sinister Strike: spell=14873
                  Eviscerate: spell=5692
                  Dual Wield: spell=30798

    Rokdar the Sundered Lord: npc=18400
    Abilities: Knock Away: spell=31389
                  War Stomp: spell=16727

    Skra'gath: npc=18401
    Abilities: Dark Shriek: spell=32322
                  Drain Touch: spell=29299
                  Piercing Shadow: spell=16429,
                  Shadow Burst: spell=32324
    
    Warmaul Champion: npc=18402
    Abilities: Batlle Shout: spell=31403
                  Charge: spell=32323
                  Mortal Strike: spell=15708
                  Sundering Cleave: spell=17963

    Mogor Hero of the Warmaul: npc=18069
    Abilities: Chain Lighting: spell=16033
                  Flame Shock: spell=39529
                  Healing Wave: spell=15982
    
The differences:
In Wrath of the Lich King; 

- Murkblood Twins had the added abilities of Eviscerate and Dual Wield.

- Rokdar the Sundered Lord did not have the Puncture ability.

- Skra'gath had the added ability Shadow Burst. I'm still researching damage reducing abilities.

- Mogor Hero of the Warmaul did not have the ability Revive Self, but I do believe he should have Frenzy.

**Comment by adellaci** [comment]
Argonn

I have searched all database updates since the current release, these NPC had to be corrected in a prior release. 

Have you tried redoing your database?

**Comment by adellaci** [comment]
Skra'gath damage reducing abilities is limited to the first school of damage that is used on him. If the first is attack is of the arcane class he gains a reduction to all arcane damage, and has that ability through out the fight.

**Comment by adellaci** [comment]
@Grz3s 
From the research I did, Mogor Hero of the Warmaul, in Wrath of the Lich King, did have the ability Frenzy.
  
```
UPDATE creature_template_spells SET spell5 = 28747 WHERE entry = 18069;
```
As for Skra'gath damage reducing abilities, I do not know how to write the code for this.

**Comment by Argonn** [comment]
The issue was 2 months old, we update the server on a weekly basis. And not a single ability was used, not even the self-ress of the last ogre.

**Comment by adellaci** [comment]
I'll check again, but i do not believe that in Wrath of the Lich King 3.3.5a he had the ability of Revive Self. I have not logged on to my server and tried the Ring of Blood yet. Still working on a few other things. As soon as I do I will post what I find

**Comment by adellaci** [comment]
@Grz3s 
The wife and I was testing prior to your update on Argonn's issue. Brokentoe did not use the ability Hoof Stomp. How can I un-do that quest completion so that i may test it again, now that I have made the update to the DB?

**Comment by Grz3s** [comment]
hi @adellaci 
if you have .gm rights simply use command to remove quest.
.quest remove "id"  (for Brokentoe you need: .quest remove 9962) -- 
pls dont forget .. if u also finished quests that comes after this... u need to remove them all in reverse order.
So if you have done whole chain... you need to remove them all:
.quest remove 9977    -- for final  'The Ring of Blood: The Final Challenge'
.quest remove 9973    -- for  'The Ring of Blood: The Warmaul Champion'
.quest remove 9972    -- for  'The Ring of Blood: Skra'gath'
.quest remove 9970
.quest remove 9967
.quest remove 9962 - first one 
So you can do all again :)

BTW:
Pls dont forget about ACID updates - they are req. to see creatures abillities. (pls look into comments on each of prev updates - it says reQ. ACID ..... )
GL

**Comment by adellaci** [comment]
Hi @Grz3s 

I did know about doing the updates. We were not able to complete the second round, but i did not know about removing them in the reverse order, so thank you for the heads up! I will to a 'mangos', unified-db, & acid update tomorrow night. Then the wife and i are going to take a run at it again.

**Comment by adellaci** [comment]
@Grz3s 
By the way, i am going to go back at "Rare Spawns", any zone you prefer?

**Comment by Grz3s** [comment]
(..)any zone you prefer?(..)
you need to ask yourself that question ;)

**Comment by Grz3s** [comment]
Small problem with: Skra'gath
I cant set his reaction according to this:
```quote
Skra'gath damage reducing abilities is limited to the first school of damage that is used on him. If the first attack is of the arcane class he gains a reduction to all arcane damage, and has that ability through out the fight.
```
We could use reaction on spellhit Parameter 2: School but: 
EventAI -- has no option to use random event from list of selected events.. 
So if i'll set diff event for each school ...we'll end up with him 75% resist.. for all of them :)

Not sure if this can be done also by sd2 <--- need to ask @xfurry
Anyway:
I'll add fix for quest and him using all other abillities ...(if xfurry one day decide to fix him in sd2 ... then he can simply be removed from acid) ;)

**Comment by adellaci** [comment]
@Grz3s 
I haven't had the time to look through he database, and how all of them interrelate, but i kinda understand what you are saying. My thought on it was that he has all of the resist abilities inactive. When the first attacked occurred, a test was made on what class attack it was and activate the resist ability, then no further test. If he dies or de-spawns, he is reset with all abilities inactive, and the test is enabled again.

I have not ventured into 'acid' or 'SD2' as of yet, so i can not offer any true help.

In the mean while, is it possible, in the interim, to give him the all resist abilities @ 5 - 7% ? It would make it feel at least a little closer to normal.

My line of thought: The math works out to be 75% / 6 = 12.5%. Once the group figured out that he resisted a ability they would compensate by using what ever other abilities they had to maintain their DPS. Which means that they couldn't use their normal rotation of spells/hits, we reduce this by another half to offer a fair realism of the combat, putting the resist to about 6.5%.

It's just a thought.

**Comment by adellaci** [comment]
@Argonn 

You started this thread, your two cents matters.

On to another subject in this post;
I did more research on Mogor Hero of the Warmaul, I still can not find any reference that he had Self Revive in TBC, or in WotLK. I have found reference to it in Cat , one of the updates.

**Comment by Grz3s** [comment]
About - Skra'gath
I can only use what ACID or DB_tools allow me to use:
Problem here... is simple...
All depends what kind  "school" magic is used against him... he will react casting on of these spells on himself:
```code
ID - 34331 Damage Reduction: Arcane
ID - 34333 Damage Reduction: Fire
ID - 34334 Damage Reduction: Frost
ID - 34335 Damage Reduction: Nature
ID - 34336 Damage Reduction: Holy
ID - 34338 Damage Reduction: Shadow
```
It's not our goal to change anything inside spells etc... (so no mehanic can be change here)
Part of it can be done using ACID:
```sql
8  =  EVENT_T_SPELLHIT  with 11 =  ACTION_T_CAST
explain:
 if he recives spell (parametr 2 will check what school) -- and as a reaction he will cast protecting spell on himself.
So .. i can do the same for all types of spells.
```

The only issue here... is we do NOT have any tool to force him to check only first spell ... and do not use this event on others ... ( so he will cast protecting spell ... on any school spells ..  and we will end up with him + 75% protect on everything we used against him)

**Comment by Grz3s** [comment]
BTW:
pls wait ... with testing until i'll finish all of them ;)

**Comment by adellaci** [comment]
The wife and i are going to try Brokentoe again tonight only. 

To better understand, the protection spell offers 75% protection and could not be changed to a much lower %?

Oh! i see if we make a change to the ability spell casted, it would impact all creatures that use that ability?

**Comment by Grz3s** [comment]
```quote
On to another subject in this post;
 I did more research on Mogor Hero of the Warmaul, I still can not find any reference that he had Self Revive in TBC, or in WotLK. I have found reference to it in Cat , one of the updates. Can either @Grz3s or you confirm?
```
https://www.youtube.com/watch?v=LoB70fUnc_A   -- 2008 WoTLk ..should explain all :)

**Comment by Argonn** [comment]
I'm more than 100% sure he had that ability in TBC (got me killed a couple of times). And as shown in @Grz3s  his link.

**Comment by Grz3s** [comment]
hi all again ...
Finall quest in this chain is difficult to fix :)....
I tried many mothods.. without 100% result. (took me last 2 days to trying everything) :)
had problems like:
- creatures after death cant be resurrected (respawned manualy will respawn at spawn point)
- etc...

I have a fix: this is not 100% blizzlike (i cant do it any better)  but pls look what i've done:
https://youtu.be/_jCnyWrliTk

And  code if someone would like to test it:
```sql
-- q.9977 'The Ring of Blood: The Final Challenge'
DELETE FROM dbscripts_on_quest_start WHERE id = 9977;
INSERT INTO dbscripts_on_quest_start (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(9977,1,31,18069,15,0,0,0,0,0,0,0,0,0,0,0,'search for 18069'), -- in case if someone is in this q. already.
(9977,2,29,3,2,0,0,0,0,0,0,0,0,0,0,0,'quest flag removed'),
(9977,2,0,0,0,0,0,0,2000000842,0,0,0,0,0,0,0,''),
(9977,12,0,0,0,0,0,0,2000000843,0,0,0,0,0,0,0,''),
(9977,17,0,0,0,18069,60873,7 | 0x10,2000000844,0,0,0,0,0,0,0,''),
(9977,17,3,0,0,18069,60873,7 | 0x10,0,0,0,0,-717.793,7898.38,48.8137,4.86694,''),
(9977,34,0,0,0,18069,60873,7 | 0x10,2000000845,0,0,0,0,0,0,0,''),
(9977,34,22,16,0x01 | 0x04,18069,60873,7 | 0x10,0,0,0,0,0,0,0,0,'temp faction'),
(9977,35,26,0,0,18069,100,0,0,0,0,0,0,0,0,0,''),
(9977,35,29,3,1,0,0,0,0,0,0,0,0,0,0,0,'quest flag added');
DELETE FROM db_script_string WHERE entry BETWEEN 2000000842 AND 2000000846;
INSERT INTO db_script_string (entry, content_default, sound, type, language, emote, comment) VALUES
(2000000842,'Mogor has challenged you. You have to accept! Get in the ring if you are ready to fight.',0,0,0,0,NULL),
(2000000843,'For the first time in the Ring of Blood\'s history, Mogor has chosen to exercise his right of battle! On this wartorn ground, $n will face Mogor, hero of the Warmaul!',0,1,0,0,NULL),
(2000000844,'Now you face da true champion! I give you chance to run away little one. Run away now before Mogor decim... destyor... Run away before Mogor KILL!',0,1,0,0,NULL),
(2000000845,'No more chances! Now you pay da ogre!',0,1,0,15,NULL),
(2000000846,'$n has defeated the hero of the Warmaul, Mogor! All hail $n!',0,1,0,0,NULL);

-- Mogor
UPDATE creature_template SET MovementType = 0 WHERE Entry = 18069;
DELETE FROM dbscripts_on_creature_death WHERE id = 18069;
INSERT INTO dbscripts_on_creature_death (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(18069,1,0,0,0,18471,66480,0 | 0x10,2000000846,0,0,0,0,0,0,0,'buddy : yell'),
(18069,10,41,0,0,0,0,0x04,0,0,0,0,0,0,0,0,'');
-- ACID
-- Mogor
Delete from `creature_ai_scripts` where `creature_id`= 18069;
Insert into `creature_ai_scripts` values
('1806901','18069','11','0','100','0','0','0','0','0','22','1','0','0','0','0','0','0','0','0','0','0','Mogor - set phase 1 on spawn'),
('1806902','18069','0','61','100','1','9400','13200','75000','80000','11','18975','1','1','0','0','0','0','0','0','0','0','Mogor - Cast Summon Ice Totem (Phase 1+6)'),
('1806903','18069','9','61','100','1','0','30','6000','8000','11','16033','4','0','0','0','0','0','0','0','0','0','Mogor - Cast Chain Lightning (Phase 1+6)'),
('1806904','18069','9','61','100','1','0','20','18000','21000','11','39529','4','0','0','0','0','0','0','0','0','0','Mogor - Cast Flame Shock (Phase 1+6)'),
('1806905','18069','2','125','100','0','50','0','0','0','11','15892','0','1','0','0','0','0','0','0','0','0','Mogor - cast Permanent Feign Death at 50% HP (Phase 1)'),
('1806906','18069','2','125','100','0','5','0','0','0','11','29266','0','7','18','2','0','0','22','2','0','0','Mogor - cast Permanent Feign Death, set unitFlag and set phase 2 at 5% HP (Phase 1)'),
('1806907','18069','29','123','100','0','5000','5000','0','0','11','32343','0','23','22','3','0','0','0','0','0','0','Mogor - cast Revive Self and set Phase 3 (Phase2)'),
('1806908','18069','29','119','100','0','10000','10000','0','0','11','17683','0','23','22','4','0','0','0','0','0','0','Mogor - cast full hp set Phase 4 (Phase3)'),
('1806909','18069','29','111','100','0','15000','15000','0','0','1','-1424','0','0','19','2','0','0','22','5','0','0','Mogor - Yell and remove unitFlag set Phase 5 (Phase4)'),
('1806910','18069','29','95','100','0','17000','17000','0','0','11','28747','0','23','28','0','29266','0','22','6','0','0','Mogor - cast Frenzy, remove aura, set phase 6 (Phase5)'),
('1806911','18069','21','0','100','0','0','0','0','0','22','1','0','0','0','0','0','0','0','0','0','0','Mogor - set phase 1 on Reaching Home');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '18069';
DELETE FROM `creature_ai_texts` WHERE `entry` IN ('-1424');
INSERT into `creature_ai_texts` (`entry`,`content_default`,`sound`,`type`,`language`,`comment`,`emote`) VALUES
('-1424','No more nice ogre! You hurt Mogor!','0','1','0','18069','0');
```

Pls let me know what you all think about it?
should this be added or not..(why)
thanks

**Comment by adellaci** [comment]
@Grz3s 

It looks pretty good. The only difference from Blizzlike is he doesn't lay down before he revives.

**Comment by Grz3s** [comment]
Well ..he does..(death animation works fine on him) but another anim breaks it:

you can see in script...
```sql
('1806907','18069','29','123','100','0','5000','5000','0','0','11','32343','0','23','22','3','0','0','0','0','0','0','Mogor - cast Revive Self and set Phase 3 (Phase2)'),
```
here:
....'0','**5000**','**5000**','0'.....
revive self should occur 5secs after **'death anim'**... phase change... unfortunately, it happens automatically.  
As i said before... i tried everything... and nothing worked better than this:)
I dont even know if he can be done better by sd2 (@xfurry - probably could say more - but serious i gave him lots stuff to looked up .. already so .. i dont think that this is a case;) ...
Anyway... im happy to add it as it is... main mehannic works fine for me...
If noone else has nothing against it ill do it on this evening.
