### ISSUE TITLE
Flagglemurk the Cruel - Darkshore - Drops

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#161]
Update drops  to be more bliz like.

~~He should spawn @ (58.4,9.8) (58.6,9.8) (58.2,12.0) or (57.6,14.8) ingame coord instead of (36.74,67.60)~~

[Wowhead](www.wowhead.com/npc=7015/flagglemurk-the-cruel) - Flagglemurk the Cruel

```
-- Flagglemurk the Cruel
-- Add to items dropped and change movement
UPDATE creature SET spawndist = 5 WHERE id = 7015;
UPDATE creature SET MovementType = 1 WHERE id = 7015;
UPDATE creature_template SET MovementType = 1 WHERE entry = 7015;

DELETE FROM creature_loot_template WHERE  entry = 7015; 
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(7015, 730, 34.8718, 0, 1, 1, 0),
(7015, 818, 0.06, 0, 1, 1, 1),
(7015, 858, 0.5128, 0, 1, 1, 0),
(7015, 954, 0.18, 0, 1, 1, 0),
(7015, 955, 0.54, 0, 1, 1, 0),
(7015, 1179, 3.0769, 0, 1, 1, 0),
(7015, 1180, 0.9, 0, 1, 1, 0),
(7015, 1206, 0.06, 0, 1, 1, 0),
(7015, 1210, 0.72, 0, 1, 1, 0),
(7015, 1468, 36, 0, 1, 1, 0),
(7015, 2455, 1.5385, 0, 1, 1, 0),
(7015, 3012, 0.18, 0, 1, 1, 0),
(7015, 4292, 0.18, 0, 1, 1, 0),
(7015, 4410, 0.06, 0, 1, 1, 0),
(7015, 4537, 0.18, 0, 1, 1, 0),
(7015, 5498, 0.06, 0, 1, 1, 0),
(7015, 5503, 1.9, 0, 1, 1, 0),
(7015, 5523, 29.2308, 0, 1, 1, 0),
(7015, 5574, 0.06, 0, 1, 1, 0),
(7015, 5784, 20, 0, 1, 1, 0),
(7015, 5785, 1.4963, 0, 1, 1, 0),
(7015, 6266, 3.8237, 0, 1, 1, 0),
(7015, 6268, 5.1537, 0, 1, 1, 0),
(7015, 6289, 4.1026, 0, 1, 3, 0),
(7015, 6512, 3.2418, 0, 1, 1, 0),
(7015, 6537, 1.2, 0, 1, 1, 0),
(7015, 6539, 1.7, 0, 1, 1, 0),
(7015, 6541, 1.8, 0, 1, 1, 0),
(7015, 6542, 1.9950, 0, 1, 1, 0),
(7015, 6543, 1.7, 0, 1, 1, 0),
(7015, 6546, 3, 0, 1, 1, 0),
(7015, 6547, 0.7, 0, 1, 1, 0),
(7015, 6548, 3, 0, 1, 1, 0),
(7015, 6549, 2, 0, 1, 1, 0),
(7015, 6550, 1.1, 0, 1, 1, 0),
(7015, 6551, 1.2, 0, 1, 1, 0),
(7015, 6554, 0.9, 0, 1, 1, 0),
(7015, 6555, 4, 0, 1, 1, 0),
(7015, 6556, 1, 0, 1, 1, 0),
(7015, 6557, 3, 0, 1, 1, 0),
(7015, 6558, 1.1, 0, 1, 1, 0),
(7015, 9746, 0.8, 0, 1, 1, 0),
(7015, 9747, 14, 0, 1, 1, 0),
(7015, 9748, 1.2, 0, 1, 1, 0),
(7015, 9749, 3, 0, 1, 1, 0),
(7015, 9755, 0.4, 0, 1, 1, 0),
(7015, 9756, 11, 0, 1, 1, 0),
(7015, 9757, 1.2, 0, 1, 1, 0),
(7015, 9762, 0.6, 0, 1, 1, 0),
(7015, 9763, 8, 0, 1, 1, 0),
(7015, 9765, 1.5, 0, 1, 1, 0),
(7015, 9785, 1.7, 0, 1, 1, 0),
(7015, 9786, 3, 0, 1, 1, 0),
(7015, 15303, 0.6, 0, 1, 1, 0),
(7015, 24060, 1, 1, -24060, 1, 0),
(7015, 24062, 1, 1, -24062, 1, 0),
(7015, 24070, 5, 1, -24070, 1, 0),
(7015, 24076, 1, 1, -24076, 1, 0),
(7015, 24077, 1, 1, -24077, 1, 0),
(7015, 24078, 1, 1, -24078, 1, 0);
```

**Comment by Grz3s** [comment]
hi and thanks...
may I ask where this info comming from?

**Comment by adellaci** [comment]
Wowhead there is a link in my first post

**Comment by adellaci** [comment]
i'm fixing Lady Vespia right now

**Comment by adellaci** [comment]
I am not sure if the spawn location is exact

**Comment by Grz3s** [comment]
update to this:
I wouldnt only check wowhead... (they have updated data from newest ver.)
Pls dont forget that Darkshore was redone in cata. and many changes was made there....
UDB spawns are in 99% correct (most of times when smth is wrong ...is because creature is "catched"  somewhere in his waypoint or event etc).

Anyway... i looked at this carefully... and it looks like that this rare spawn should have randomized spawn. You can see on this old map where he should be found.
![50](https://cloud.githubusercontent.com/assets/2374069/12245586/6b60afd4-b8a1-11e5-8ad1-1c0a2b4d1a1e.jpg)

And loot -- good work with this... (we need to fix lots of rares)
Will comeback soon with this ;)

**Comment by adellaci** [comment]
I'll take care of all the response you just going to need to help me on how to generate randomized 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by Grz3s** [comment]
Update to your loot....
pls remember that "ChanceOrQuestChance" shouldnt be higher than 100% (without quest drops)
after your update it will be much higher

**Comment by adellaci** [comment]
Sorry about the reply early, i made it with voice to text on my way home. I was ry to say that i will work on the rare spawns, zone by zone. I don't know how to create the randimization of the spawn location, and will need your help. 

As far as the "ChanceOrQuestChance" totalling greater then 100%,  in the many years playing retail, we use to chase done the rare spawns because they almost always drop more then one green/blue items.  Ussually it was two or more plus a white or two and the same for the grey items. This is way it totals greater then 100%.

**Comment by adellaci** [comment]
Let me put it like this, in order for the drop % to equal 100, the NPC can only drop one item everytime they are looted. If they drop  more then one item per loot, it has to be greater then 100% on the total of all items

**Comment by Grz3s** [comment]
about random spawn/
You need to use pools to create random xyz spawns for creature...

Also... I looked again into your updated loot for this creature... and tested it few (maybe more than few:) ) times...
Im not an expert with loot_system (@cyberium) probably could explain more about it....
I understand that rare creatures should drop better stuff than trash mobs... but is this normal.. that almost everytime i killed him ... i recived 2 or 3 green items in that updated loot? 

BTW:
Leave pools -- i'll make update for this ;)

**Comment by adellaci** [comment]
Hi Grz3s
Yes it was normal for them to drop several green items. I also tested the drops and it appeared fairly normal. I also do not know how the loot_system is implemented in CMaNGOS compared to retail. 

Where did you go to get the map of spawn locations?

I do not know how to set up pools to create random spawn locals, can it give me an example on how to set that up?

He it an adjust to the drops based on [Wowhead](www.wowhead.com/npc=7015/flagglemurk-the-cruel) - Flagglemurk the Cruel

```
-- Flagglemurk the Cruel
-- Add to item drops & movement

UPDATE creature SET spawndist = 5 WHERE id = 7015;
UPDATE creature SET MovementType = 1 WHERE id = 7015;
UPDATE creature_template SET MovementType = 1 WHERE entry = 7015;

DELETE FROM creature_loot_template WHERE  entry = 7015;

INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(7015,730,1.7,0,1,1,0),
(7015,858,2,0,1,1,0),
(7015,1179,1.6,0,1,1,0),
(7015,1468,36,0,1,1,0),
(7015,1506,0.4,0,1,1,0),
(7015,1514,1.7,0,1,1,0),
(7015,1516,0.5,0,1,1,0),
(7015,1734,0.5,0,1,1,0),
(7015,2215,0.6,0,1,1,0),
(7015,2589,32,0,1,3,0),
(7015,5523,19,0,1,1,0),
(7015,5785,1.5,0,1,1,0),
(7015,6266,4,0,1,1,0),
(7015,6268,5,0,1,1,0),
(7015,6289,4,0,1,3,0),
(7015,6336,5,0,1,1,0),
(7015,6512,3,0,1,1,0),
(7015,6537,1.2,0,1,1,0),
(7015,6539,1.7,0,1,1,0),
(7015,6541,1.8,0,1,1,0),
(7015,6542,2,0,1,1,0),
(7015,6543,1.7,0,1,1,0),
(7015,6546,3,0,1,1,0),
(7015,6547,0.7,0,1,1,0),
(7015,6548,3,0,1,1,0),
(7015,6549,2,0,1,1,0),
(7015,6550,1.1,0,1,1,0),
(7015,6551,1.2,0,1,1,0),
(7015,6554,0.9,0,1,1,0),
(7015,6555,4,0,1,1,0),
(7015,6556,1,0,1,1,0),
(7015,6557,3,0,1,1,0),
(7015,6558,1.1,0,1,1,0),
(7015,9746,0.8,0,1,1,0),
(7015,9747,14,0,1,1,0),
(7015,9748,1.2,0,1,1,0),
(7015,9749,3,0,1,1,0),
(7015,9755,0.4,0,1,1,0),
(7015,9756,11,0,1,1,0),
(7015,9757,1.2,0,1,1,0),
(7015,9762,0.6,0,1,1,0),
(7015,9763,8,0,1,1,0),
(7015,9765,1.5,0,1,1,0),
(7015,9785,1.7,0,1,1,0),
(7015,9786,3,0,1,1,0),
(7015,15303,0.6,0,1,1,0),
(7015,24060,1,1,-24060,1,0),
(7015,24062,1,1,-24062,1,0),
(7015,24070,5,1,-24070,1,0),
(7015,24076,1,1,-24076,1,0),
(7015,24077,1,1,-24077,1,0),
(7015,24078,1,1,-24078,1,0);
```

**Comment by adellaci** [comment]
Are you okay with me pushing the rare spawn drops up into Updates?

**Comment by Grz3s** [comment]
hi.
Sor that it took that loong... You know *life*.
Anyway... someetimes .. it takes long checking etc.

**Comment by adellaci** [comment]
adellaci@sacoriver.net
