### ISSUE TITLE
[WotLK] Warrior Trainer's Dual Spec learning

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#166]
So i hope this are all Warrior Trainer's all other Classes i will post soon
Here the List from the NPC ID's where you don't can learn Dual Spec
======================================
Here we need an Update!!!
Horde Warrior Trainer ID's
Trisfal Glades: 2131
Undercity: 4594 ; 4595 ; 4593
Orgrimmar: 3408 ; 3354
Durotar: 3153

Alliance Warrior Trainer ID's
Elwynn Forest: 913
The Exodar: 17120 ; 16771 ; 17504

Here the List from the NPC ID's where you can learn Dual Spec
==================================

Here we need no Updates they are all OK
Horde Warrior Trainer ID's
Thunder Bluff: 3041 ; 3042 ; 3043
Mulgore: 3063 ; 3059
Durotar: 3169

Alliance Warrior Trainer ID's
Dun Morogh: 1229 ; 912
Ironforge: 5114 ; 1901 ; 5113
Stormwind City: 5479 ; 5480 ; 914
Elwynn Forest: 911
Azuremyst Isle: 17480 ; 16503
Darnassus: 7315 ; 4087
Teldrassil: 3598 ; 3593

**Comment by Grz3s** [comment]
hi
Well i saw topic.. about this.. on Cmangos forum and yes we need update for all classes.
Ofc i'll try to fix it ASAP ;)
thanks for report..
