### ISSUE TITLE
Possible fix for quest 8309 (Glyph Chasing)

### ISSUE THREAD

**Issue by Slizzo** [unified-db/Database#169]
The Silithus quest 8309 (Glyph Chasing) wasn't working for me, and I found the following fix at the ClassicDb site:

https://github.com/classicdb/database/commit/a0134abc982d7288caaf305472035dbdf59e370b

This worked for me - is is okay for the wotlk database?

**Comment by xfurry** [comment]
It should be fine. @cala can you please confirm

**Comment by cala** [comment]
Yes, this fix is OK for WotLK too. One just need to check that the condition ID is not already used in UDB.
