### ISSUE TITLE
[WotLK] Milling from Inscription have a bug

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#170]
Milling (Spell ID 51005) have a bug
if you have 1 Stack (20) Flowers like Silverleaf (ID 765)
and you want to use Milling on the Stack it will mill 5 from this, its ok, 5 flowers are milled and you have an Stack with 15 Silverleafes
Here coms the Bug
if you want to mill the next 5 one you can't do that, couse no item is inside the looting Bag

so
if you split this Stack from above in 3 Parts with 5 Flowers you can only mill 2 from this, couse the lastone is corrupt

so
if you have an new Stack with 20 flowers  and split it first in 4 parts with 5 Flowers, you can mill all

**Comment by adellaci** [comment]
The wife and i conformed what you have seen, but want to add, the wife continue to mill, no herbs were removed from the stack, no resulting product showed up in her bag, yet she continued to gain skill.
I had her log out and log back in, and again she was able to mill one out of the stack as you would normally, and then back to, no consumption, no product, yet her skill points rose.

**Comment by Grz3s** [comment]
Well will check this soon*
if its core issue  = not much i can do about it.
if DB -- ill try ;)
We'll see soon ;)

**Comment by adellaci** [comment]
Taking a look at this, I was not convince that it was a DB issues, was just add additional information that may help with determining.

**Comment by Darth-Postal** [comment]
I think this was fixed in the core:

https://github.com/cmangos/mangos-wotlk/commit/ba6ce1a00fbf23557b5615f4c2101facf37dbea2

**Comment by Phatcat** [comment]
This sounds very much like the jewelcrafting bug described here: https://github.com/cmangos/issues/issues/953

which should have been fixed by this commit: https://github.com/cmangos/mangos-tbc/commit/d2bd17056d87a683cc376b0b0a690f29075e8d07

**Comment by adellaci** [comment]
I'll test it out tonight

**Comment by adellaci** [comment]
@Grz3s 
I tested it out tonight, I believe @Phatcat & @Darth-Postal is correct. This issue with Milling and Prospecting appears to working correctly once again

**Comment by Grz3s** [comment]
thanks for testing
