### ISSUE TITLE
Firecaller Radison - Darkshore - Drops

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#181]
Firecaller Radison	2192		
Level: 19
Class: Rare-Elite
React: A H
Faction: Monster
Health: 449
Wealth: 27
Damage: 162 - 193 (Physical)
Armor: 442
Model: 5772

Crazed	        5915
Fire Nova	        11969
Fireball	        20793

Video:	
Abilities:	http://db.vanillagaming.org/?npc=2192#abilities
Info:	http://db.vanillagaming.org/?npc=2192

```
-- Firecaller_Radison
-- Add to item drops

DELETE FROM creature_loot_template WHERE  entry = 2192;
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(2192,414,5,0,1,1,0),
(2192,785,0.3,0,1,1,0),
(2192,818,0.19,0,1,1,0),
(2192,858,2.8169,0,1,1,0),
(2192,954,0.3,0,1,1,0),
(2192,955,0.29,0,1,1,0),
(2192,1179,2.8169,0,1,1,0),
(2192,1206,0.3,0,1,1,0),
(2192,1210,0.3,0,1,1,0),
(2192,1738,0.2,0,1,1,0),
(2192,1743,0.03,0,1,1,0),
(2192,1766,0.03,0,1,1,0),
(2192,1768,0.16,0,1,1,0),
(2192,1769,0.19,0,1,1,0),
(2192,1770,0.19,0,1,1,0),
(2192,1787,0.3,0,1,1,0),
(2192,1794,0.16,0,1,1,0),
(2192,1812,0.16,0,1,1,0),
(2192,1813,0.4,0,1,1,0),
(2192,1814,0.19,0,1,1,0),
(2192,1816,0.3,0,1,1,0),
(2192,2287,6.338,0,1,1,0),
(2192,2447,0.3,0,1,1,0),
(2192,2453,0.3,0,1,1,0),
(2192,2455,0.7042,0,1,1,0),
(2192,2589,20,0,1,3,0),
(2192,2592,19,0,1,2,0),
(2192,2698,0.1,0,1,1,0),
(2192,2781,0.16,0,1,1,0),
(2192,3012,0.3,0,1,1,0),
(2192,3193,0.3,0,1,1,0),
(2192,3376,0.19,0,1,1,0),
(2192,4575,0.03,0,1,1,0),
(2192,5503,0.1,0,1,1,0),
(2192,6348,0.3,0,1,1,0),
(2192,6536,4,0,1,1,0),
(2192,6538,3,0,1,1,0),
(2192,6540,4,0,1,1,0),
(2192,6545,4,0,1,1,0),
(2192,6552,5,0,1,1,0),
(2192,6553,5,0,1,1,0),
(2192,6562,1.7,0,1,1,0),
(2192,6563,2,0,1,1,0),
(2192,6564,3,0,1,1,0),
(2192,6565,0.8,0,1,1,0),
(2192,6570,0.6,0,1,1,0),
(2192,6574,0.5,0,1,1,0),
(2192,6575,1.9,0,1,1,0),
(2192,6576,0.5,0,1,1,0),
(2192,6581,3,0,1,1,0),
(2192,6582,0.5,0,1,1,0),
(2192,6583,1.9,0,1,1,0),
(2192,6585,2,0,1,1,0),
(2192,9766,1.8,0,1,1,0),
(2192,9767,3,0,1,1,0),
(2192,9768,4,0,1,1,0),
(2192,9770,4,0,1,1,0),
(2192,9771,2,0,1,1,0),
(2192,9772,0.3,0,1,1,0),
(2192,9775,4,0,1,1,0),
(2192,9776,3,0,1,1,0),
(2192,9777,4,0,1,1,0),
(2192,9779,5,0,1,1,0),
(2192,9780,2,0,1,1,0),
(2192,9781,0.5,0,1,1,0),
(2192,9783,2,0,1,1,0),
(2192,9784,4,0,1,1,0),
(2192,9787,4,0,1,1,0),
(2192,9788,4,0,1,1,0),
(2192,9789,4,0,1,1,0),
(2192,9812,1.3,0,1,1,0),
(2192,10287,0.9,0,1,1,0),
(2192,10405,0.7042,0,1,1,0),
(2192,10407,3.9,0,1,1,0),
(2192,14367,0.19,0,1,1,0),
(2192,15498,0.03,0,1,1,0),
(2192,24060,1,1,-24060,1,0),
(2192,24062,1,1,-24062,1,0),
(2192,24064,1,1,-24064,1,0),
(2192,24066,0.5,1,-24066,1,0),
(2192,24070,5,1,-24070,1,0),
(2192,24078,1,1,-24078,1,0);
```

**Comment by adellaci** [comment]
@Grz3s 

I believe that this is the last of the rare spawns in Darkshore.

If you show me a example of a spawn pool, i will start on adding to those rare spawns that have random spawn locations.

**Comment by Grz3s** [comment]
example u had in https://github.com/unified-db/Database/commit/c5081a0507f383273add72af862ab0e8682f4023
look at pools..
BTW:
pls be careful with your fixes:
As i said already:
Wowhead has all updated for WoD .. and between WoD and Wotlk .. there were many changes. (not always but...)
- Some spawn poss a not the same that we had in prev ver.
- most of time rare spawns had large paths.. so it was hard to find'em ( this is why it takes me loots of time to search for any info about that - most of the time its imposs. to get that data)
Anyway pls keep up with gr8 job u doing with this.
thanks

**Comment by adellaci** [comment]
Thank you Grz3s

I do realize WoWHead is up to date with retail, i do try to look at db.vanillagaming.org to identify what may have changes. I also have reading all the comments to and which version they pertain to.

**Comment by Grz3s** [comment]
:+1:

**Comment by adellaci** [comment]
@Grz3s 
I was looking at 'c5081a0'. I understand most of it, but am unsure about the last piece. So for now i'm going to move on to another zone, and work on the rare spawns there. If I run another spawn that has a lot of random spawn locations, I’ll post my attempt to writing it in a separate issue post with as much detail I can find. From there you can point out the point I am not grasping.

**Comment by Grz3s** [comment]
hej @adellaci ... let me try to make easy for you:
example:
```code
-- Only one can be spawned at at the same time
DELETE FROM pool_template WHERE entry = 25521;
INSERT INTO pool_template (entry, max_limit, description) VALUES 
(25521,1,'Draenei Youngling');
DELETE FROM pool_creature_template WHERE pool_entry = 25520;
INSERT INTO pool_creature_template (id, pool_entry, chance, description) VALUES
(17587, 25521, 0, 'Draenei Youngling - 17587');
```
first you checking how many random spawns your creature has...
spawn them all (they all must be added as normal creatures)

Creating pool we need to start from unique 'pool_template' <--- just take next free entry for it
and create smth like:
```sql
DELETE FROM pool_template WHERE entry = 25521;
INSERT INTO pool_template (entry, max_limit, description) VALUES 
(free entry, how many can be spawned in the same time, %chane to spawn(0 - is equal for all) , comment);
```
and after this we need to add our npcs to that pool
becouse we having only one "the same ID" creature we will use `pool_creature_template`
And create smth like this:
```sql
DELETE FROM pool_creature_template WHERE x=x
INSERT INTO pool_creature_template (id, pool_entry, chance, description) VALUES
(npcEntry, entry - from pool_template(our first free), %for spawn, 'comment');
```
pls do not forget ... that pools may contain more than one creature - sometimes few mixed together
for harder scripts pls check in older scripts -- like this one 408_updatepack_mangos.sql

Back to subject:
From my experience... most of rares ... had a large waypoints...so it was quite hard to find them
Sometimes ... u may find spawn location for rare .. and then in our 'legit' data he is in diff place... usualy with movement set =0 --- this gives me 'red light' stright ... that 90% waypoints are there...
:)

Anyway:
I'll look at all your rares on saturday (got more free time) .
Regards

**Comment by adellaci** [comment]
Thank you very much for that explanation that is extremely helpful to me


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
