### ISSUE TITLE
405_creature.sql 	[405] Blood Elf Bandit 

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#183]
I found this information related

"kaerid on 2008/10/15 (Patch 3.0.2)
There are definitely more than 10 spawn locations for the bandits. Using the map pin points here on wowhead back when I was farming the masks for all my low levels, I eventually had personal confirmed spawns at all 20 locations. "

" kryzflavored on 2009/10/04 (Patch 3.2.2)
Just a warning, the wandering Peacekeepers will kill him if they get to him before you."

It also said he de-spawns in 10 minutes if not attack, and respawns at another location.
I'm trying to get you accurate xyzo for the other ten locations.

**Comment by Grz3s** [comment]
1st: -- this may be true... 
http://smg.photobucket.com/user/I_Dont_Exist/media/WoWie/Wowhead/beb-patrol.png.html
picture here shows all spawn locations... 
also in our parsed data we have... Bandits spawned in few of these missing locations (.. prev. i thought its fake, but it may be myistake) 
So yes... I'll update all missing ones... 

2nd: -- this is correct .. on above pic... u can see location where bandit can be killed by guard... 
I tested this. and it works fine.

3rd: -- this was tested by few ppl ..(u can even find a vid - someone waited there for ~30mins = no desp)

Thanks

**Comment by adellaci** [comment]
Thank you Grz3s, I didn't mean to cause you to spend your time on it. I apologize.
