### ISSUE TITLE
[TBC] To catch a thistlehead q.10563 and q.10596

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#187]
I cleaned up the quest and made it actually work (the quest was being triggered on spell that doesnt support dbscript). I added a missing spell to spell_template (trinitycore sniff gathered that information) and changed the script to on event. I changed one timing and transfered the "emote" from separate command to db_script_string, and changed a few emotes according to videos of quest.

I am sharing this cleanup with you because I know that @Grz3s is fixing up Shadowmoon valley.

https://gist.github.com/killerwife/9038c41b399b55070125

When you look at it/implement, you can close this issue.

Oh and could you please remove wpguid from database? As far as I know its a redundant collumn.

**Comment by Grz3s** [comment]
Well ..dont know what to do with your script...
Our older version works perfecly fine for WoTLK....
Also i removed sniffs... from this quest long time ago... and... it will be hard to check if this ..does exact what TC says....
Anyway... I using often theirs parser... and "it doesnt show server side spells" -- im sure are hardcoded  ..not just simple spells. Only line you can check is ... to look at example: summoned creature there... and it will tell you ...smth like:  summoned by ..... (spell/player etc)...
I'll leave it... as is not that urgent...and in spare time ..recheck it again ;)
Thanks for your work.

**Comment by Grz3s** [comment]
i also found on TC where this concept was created:
```quote
Id: 37097
 Name: Crate Disguise
 ...
 Effect 2:
 Id: 64 (SPELL_EFFECT_TRIGGER_SPELL)
 BasePoints = 1
 Targets (1, 0) (TARGET_SELF, NO_TARGET)
 Trigger spell: 37492 Not found

that not found spell has effect aply aura stuned + effect send event 13852. 335 - 434 I don't know how works now in wod the spell_dbc table.
```

I checked  3.3.5 spell.dbc --- 37492 doesnt exist there

Can someone pls check in 434? if this spell exist there? @Ulduar ? @ghost ?

**Comment by killerwife** [comment]
Your solution was creating errors on TBC-DB core, and I know this isnt crucial, but I am trying to unify data in UDB and TBC-DB. And afaik the spell isnt even in 4.3.4, but my source could be wrong.

If I do any other work in Shadowmoon I will post it here immediately.

**Comment by Ulduar** [comment]
``` QUOTE
Can someone pls check in 434? if this spell exist there? @Ulduar ? @ghost ?
```
Checked 4.3.4, checked 5.4.8, checked 6.2.3 Spellwork - is absent.

**Comment by Grz3s** [comment]
ok... i had enough time to think about it...
Both ways of scripting this quest are "maybe" not 100%... but  defenetly that server side spell does smth with event start.
Method proposed by you (TrinityCore) ... looks better for me and as you said... works fine for Both versions TBC and WotLK ... 

BTW:
emotes used by me... were from sniff. + checked on vids. ... 
- good catch with first one... its not needed (its his natural reaction)
- last one for '2000005425' - you shouldnt change .... its got to be e.'274' = EMOTE_ONESHOT_NO
Thanks.

**Comment by killerwife** [comment]
thx for letting me know, im gonna change it in that 5425 db_script_string
btw I have it confirmed that the serverside spell is used, there was a leak in blizzards XML the other day and we got serverside spell names, at least some of them

**Comment by Grz3s** [comment]
Also one more thing:
Spell casted on this event ... should be debuff not a buff.
@xfurry can you pls add this into core:


**SpellMgr.cpp**
```code
        // non-positive aura use
        case SPELL_EFFECT_APPLY_AURA:
+		    // aura can be positive or negative dependent on casted spell
+            switch (spellproto->Id)
+			{
+               case 37097:                                 // Crate Disguise
+                   return false;
+                default:
+                    break;
+            }
+            break;
		case SPELL_EFFECT_APPLY_AREA_AURA_FRIEND:

Tested and works fine.

**Comment by killerwife** [comment]
uhm, wrong spot @Grz3s :D
add it here
                case SPELL_AURA_TRANSFORM:
                    // some spells negative
                    switch (spellproto->Id)
                    {
                        case 36897:                         // Transporter Malfunction (race mutation to horde)
                        case 36899:                         // Transporter Malfunction (race mutation to alliance)
                        case 37097:                         // Crate Disguise
                            return false;
                    }
                    break;

**Comment by Grz3s** [comment]
hmm... ok :)

**Comment by xfurry** [comment]
I will check this once I'm back from holiday

**Comment by Grz3s** [comment]
With recent core changes:
this quest is broken again:
- transorm wrongly changes model into IMP --> https://github.com/cmangos/mangos-wotlk/commit/b9006d3237870e9cd13662e0ce98217fede9bcfe
- stun cancels transform --> no idea where this was changed
- none of above spell fixes will work anymore. --> no idea where this was changed

Problably we'll have to put this on hold until .. core allow us to work on it again ehh :/

**Comment by xfurry** [comment]
So what exactly is the requirement here?
I understand that we need to add a new category in the core, to define which transformation auras are negative and which positive. Is that it?

Not sure about what is the problem with the stun, as I can't find any stun in the spell. And the model should be fixed in the latest core.

**Comment by killerwife** [comment]
For aura being negative, just change the "is positive spell" in IsPositiveEffect :P basically what i linked from my local commit.

For stun cancelling transform, we implemented new aura interrupt flags, thats possibly the issue. Most likely we will have to stop using this "hack" with dbscript and start using proper stun aura on the missing spell ID. Just wait for maximuses spell dbc migration, and then it will be taken care of.

**Comment by Grz3s** [comment]
small update after todays core changes:
- model came back to normal
- we can implement this part in core ... it works fine:
**SpellMgr.cpp**
```sql
case SPELL_AURA_TRANSFORM:
 // some spells negative
 switch (spellproto->Id)
 {
 case 36897: // Transporter Malfunction (race mutation to horde)
 case 36899: // Transporter Malfunction (race mutation to alliance)
+  case 37097: // Crate Disguise
 return false;
 }
 break;
```

About stun...
Yes..
currently we using this:
```sql
DELETE FROM dbscripts_on_event WHERE id = 13852; 
INSERT INTO dbscripts_on_event (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES 
(13852,0,15,48342,0,0,0,4,0,0,0,0,0,0,0,0,'stun'),
(13852,3,10,21633,61000,0,0,0,0,0,0,0,-3312.04,2948.81,171.12,4.83,'summon - Deathbringer Jovaan'),
(13852,4,40,0,0,184835,25738,1 | 0x10,0,0,0,0,0,0,0,0,'despawn object'),
(13852,5,40,0,0,184834,25737,1 | 0x10,0,0,0,0,0,0,0,0,'despawn object'), -- doesnt work anymore
(13852,57,8,21502,0,0,0,4,0,0,0,0,0,0,0,0,'q. completed');
(13852,60,14,48342,0,0,0,4,0,0,0,0,0,0,0,0,'stun');
```
And now...
48342 -- used here..breaks ..transform aura... and player comes back to his normal form...
We all knowthat this spell doesnt belong to this script and it was only used to give stun effect...
Because it doesnt work anymore... we should use correct spell: Im agree with @killerwife 
```sql
DELETE FROM spell_template WHERE id = 37492;
-- 1st effect that triggers event
INSERT INTO spell_template (id, effect0, effect0_misc_value, comments) VALUES
(37492,61,13852,'Crate Disguise Subspell'); -- add trigger for server-side spell boxotricks
-- 2nd that stuns player
-- INSERT INTO spell_template (id, attr, attr_ex, effect0, proc_chance,duration_index, effect0_implicit_target_a, effect0_apply_aura_name, comments) VALUES
-- (37492,384,268435456,6,101, 3,1,12,'Crate Disguise Subspell');
```
I just tested that spell for both effects: 
1st stun ... works fine
2nd - trigers event also works fine...
Shame that we can add into ours spell_template only one effect.

```quote
Just wait for maximuses spell dbc migration, and then it will be taken care of.
```
didnt hear anything about it .:(

**Comment by killerwife** [comment]
Thats because you dont come to IRC :P

**Comment by Grz3s** [comment]
this one ....awaits only for more effects in spell_template.
