### ISSUE TITLE
[Classic - WotLK] Gravis Slipknot (rare spawn) - Alterac Mountains (Strahnbrad) - Drops, Ability 

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#189]
Gravis Slipknot

id:      14221
guid:  86756

    Classification: Rare
    React: A H (hostile) should be hostile towards A & H
    Faction: Syndicate
    Health: 1,608

Upon aggro he says "Greetings hapless adventurer. I ask only that you wait a moment...and BLEED!"

```
-- Gravis Slipknot

-- Add ability
DELETE FROM creature_template_spells WHERE entry = 14221;
INSERT INTO creature_template_spells (entry, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8) VALUES
(14221,18501,0,0,0,0,0,0,0);

-- Update Health
UPDATE creature SET curhealth = 1608, WHERE guid = 85756;

-- Loop drop corrected
DELETE FROM creature_loot_template WHERE  entry = 14221;
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(14221,1477,0.38,0,1,1,0),
(14221,1707,7.9365,0,1,1,0),
(14221,1708,3.86,0,1,1,0),
(14221,1710,1.0582,0,1,1,0),
(14221,1759,0.07,0,1,1,0),
(14221,1785,0.2,0,1,1,0),
(14221,1806,0.03,0,1,1,0),
(14221,1830,0.03,0,1,1,0),
(14221,2222,0.16,0,1,1,0),
(14221,2289,0.11,0,1,1,0),
(14221,2453,0.38,0,1,1,0),
(14221,3827,0.5291,0,1,1,0),
(14221,4306,32.8042,0,1,3,0),
(14221,4338,4.2328,0,1,1,0),
(14221,4421,0.38,0,1,1,0),
(14221,4424,0.38,0,1,1,0),
(14221,4715,2,0,1,1,0),
(14221,5113,20.1058,0,1,1,0),
(14221,6567,1.6,0,1,1,0),
(14221,6569,2,0,1,1,0),
(14221,6584,2,0,1,1,0),
(14221,6590,1,0,1,1,0),
(14221,6591,2,0,1,1,0),
(14221,6592,0.6,0,1,1,0),
(14221,6593,6,0,1,1,0),
(14221,6594,1,0,1,1,0),
(14221,6595,0.4,0,1,1,0),
(14221,6596,1.2,0,1,1,0),
(14221,6597,1.2,0,1,1,0),
(14221,6600,3,0,1,1,0),
(14221,6601,1.1,0,1,1,0),
(14221,6602,2,0,1,1,0),
(14221,6604,6,0,1,1,0),
(14221,6605,1,0,1,1,0),
(14221,6612,0.6,0,1,1,0),
(14221,6613,1,0,1,1,0),
(14221,6614,0.9,0,1,1,0),
(14221,6615,0.7,0,1,1,0),
(14221,6986,4,0,1,1,0),
(14221,7415,0.9,0,1,1,0),
(14221,7448,0.3,0,1,1,0),
(14221,9791,0.6,0,1,1,0),
(14221,9792,2,0,1,1,0),
(14221,9793,1.4,0,1,1,0),
(14221,9794,2,0,1,1,0),
(14221,9795,5,0,1,1,0),
(14221,9796,2,0,1,1,0),
(14221,9797,1.4,0,1,1,0),
(14221,9799,5,0,1,1,0),
(14221,9801,2,0,1,1,0),
(14221,9802,6,0,1,1,0),
(14221,9803,6,0,1,1,0),
(14221,9806,2,0,1,1,0),
(14221,9807,2,0,1,1,0),
(14221,9808,1.2,0,1,1,0),
(14221,9809,1.4,0,1,1,0),
(14221,9810,1.8,0,1,1,0),
(14221,9813,2,0,1,1,0),
(14221,9815,2,0,1,1,0),
(14221,9817,5,0,1,1,0),
(14221,9818,3,0,1,1,0),
(14221,9822,0.6,0,1,1,0),
(14221,9829,0.6,0,1,1,0),
(14221,9831,0.8,0,1,1,0),
(14221,9838,0.7,0,1,1,0),
(14221,15224,0.03,0,1,1,0),
(14221,24047,5,1,-24047,1,0),
(14221,24052,1,1,-24052,1,0),
(14221,24054,1,1,-24054,1,0),
(14221,24056,1,1,-24056,1,0);
```

**Comment by Grz3s** [comment]
Hi @adellaci 
About this one:
- I corrected faction - he should be indead hostile against players (Syndicate faction)
- I also changed his weapon - we had his new model from 4.x.x
- You proposing "Health: 1,608" - this value comes from after Wotlk wow (cata -- WoD).. wont be accepted.
- Also pls give me source of your loot list.. <-- this one is most important here

**Comment by adellaci** [comment]
@Grz3s 

It has been so long, i can't say for sure. but the sites i have been using to look loot up has been a combinations of WoWHead(thou leery of the info there, because they are at the latest db), Valkyrie WoW, OpenWoW, and VanillaGaming. I believe i got the health from VanillaGaming. As far as the loot, it was pawing through the data from all the of them. WoWHead shows 61 item drop list, 4 pickpocket items. All the other db show 300+ item drop list, 4 pickpocket items, except OpenWoW shows 7 pickpocket items. 

Unfortunately, OpenWow, to get a list of drop items i had to use the Cata_db, but only as reference comparing to the other db's.

If you know of more accurate db sites, i would be interested in using them.

**Comment by Grz3s** [comment]
Well... problem with Loot System we have is simple: it just doesnt work correctly.
X-Savior made a new system that changes it completely... to much to explain... but in simply way.. we have classes of drops ... like world drop added to all (so u can see that 300+ items etc) + some green+blue etc items added individual to each special creature...
System looks promising. .. but its not available to other DBs only for TBC at the moment...
One day i'll (or someone else) look closer to that.. and *maybe* will be added into Wotlk also.

About better sites: ... its difficult to find info these days. Im checking old vids.(gogle ot yt)  sniffs (if i can find from that place) .. screenshots etc...
I do not trust sites... most of them are updated according to Wowhead .. or info coms from fake DB's ;) 
Ofc they help a lot... but i want to be sure before ill add anything that im not;]

**Comment by adellaci** [comment]
@Grz3s 
I found this October, 6 2010;

Gravis Slipknot
Level: 36
Classification: Rare
React: A H
Faction: Syndicate
Health: 1,469

**Comment by Grz3s** [comment]
you see? ... :)
also his aggro text comes from 4.x.x

**Comment by Grz3s** [comment]
another problem .... Chance to drop on this is high above 100%...
Or we missing grups on this one ... or ... as i said before ... 99% of this items are comming from (let me say that: "Junk" group)  -- and thay will be added into all spawns + smth special to this npc.
I'm seriously interested with X-saviors Drop system... 
Anyway.... From comments .. this npc doesnt drop anything special.
Pls lets hold this for now...  and  hopefuly we can fix this in correct way.

**Comment by adellaci** [comment]
Grz3s

Just because the total comes up to > 100% does not means that it is wrong, but did does depend on how the loot system is processed in CMaNGOS. That is why I was asking  if you could point me to any information, or the section of code that handles the drop system. With that information I can take the process and derive the mathematical relationship between CMaNGOS, and lets say WoWHead. With that I can write an equation that would give me an accurate representation of what the drop % should be. 

As far as the "Junk" group, as I am spending more time researching, I can absolutely agree with you. There is too many differences amongst all of them to discern what is right.   

The item that this NPC dropped, I can't say, I never farmed him in the 5 years I played, so he probably didn't have anything special that I wanted, or wasn't worth anything to any of my guild members wanted. 

About holding off on this for now....I have no objections, it can wait. The other rare spawns that I have submitted, please hold off also. The only thing that I am positive at the moment is Cranky Benj's movement. 

I will take the time to review up through the others I submitted, make comment and tag you in my response to review. 

And one most important thing.....if you disagree with me, feel free to express it, as you have done in the past. I will never get upset as long was you explain why you disagree. It's conversations like these that help all of us understand, learn, and exchange ideas/concepts.

Mathelmi   <---   ;-)

**Comment by adellaci** [comment]
Sorry push the wrong button...oppsy

**Comment by Grz3s** [comment]
Useful info about loot you will find here:
https://github.com/cmangos/issues/wiki/loot_template
pls focus on **groupid**

this one is important:
```quote
Note: The core has a limitation – only 16 non-quest items (money and items added into the loot for quests are not counted for this "16") may come into the loot. And this is not a caprice of core devs – the client has some constraints. As most of loots have much more than 16 possible items (sometimes several hundreds) so without groups there is a (little) chance that more than 16 items will be rolled for a given loot but player will be able to see (and take) only first 16 of them. With groups you can ensure that more than 16 items will never drop. If DB pretends to be a quality software it must have loot template definitions which ensure that not more than 16 plain entries and groups are defined for any loot template. 
```

You are right with sayin (...)but did does depend on how the loot system is processed in CMaNGOS(...)
You know ... I knew (lots of ppl - im sure also) ... that its impossible that so many random items  (sometimes ~700) . are added into each of +40k creatures +xK objects etc... its just a waste of space.
For me .... Wowhead... and all that %...to drop smth... its not what exactly happens...
You may see that 90% of items in drop have 0.1 ~ 0.2 drop %....  thay must be stored in "one large group" and then added ...
I didnt see X-Saviors (new drop system) ... but i spoke with him... and i know.. that concept of it is very close to what i just said...

So ... why I put on hold all your work?... I know You did lot of work with it... and i thank you for that... but we cannot choose only part of drop...and then add it ... Imagine ,,, that soon after someone will create an issue that he cannot drop smth from him ...only because was missed on script :) 
Also ... i know that is not right ... to keep smth that doesnt work at all... and not to add better one...
but look at some of issues are few years old ..and cannot be finished :)...

We will wait... I hope that x-savior will release "drop system" to public... so then we can work with it...
and fix stuff in better way. :)

**Comment by adellaci** [comment]
Grz3s
Agreed, Thank you

**Comment by adellaci** [comment]
@Grz3s 

Sorry it has taken so long to replay. I have been spending time reading the link you posted. 

I am familiar with the 16 non-quest items limitation. If I remember correctly there was the same issue with buffs in raids (limit of 16).

I don't think that I still grasp completely all the content of loot_template, but now that I have my server running cmangos again, refering to [https://github.com/cmangos/issues/issues/927](url), I'm going to play with groupid in my DB and check the impact to the drop.

**Comment by adellaci** [comment]
@Grz3s 

```
-- Gavis Slipknot

--Add ability
DELETE FROM creature_template_spells WHERE entry = 14221;
INSERT INTO creature_template_spell (entry, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8) VALUES
(14221,18501,0,0,0,0,0,0,0);

-- Loop drop corrected,,,,,,,,
DELETE FROM creature_loot_template WHERE  entry = 14221;,,,,,,,,
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES,,
(14221,4306,25.9,0,1,3,0),
(14221,5113,12.9,0,1,1,0),
(14221,3505,8.1,0,1,1,0),
(14221,1707,5,0,1,1,0),
(14221,4338,4.5,0,1,1,0),
(14221,9864,4.1,0,1,1,0),
(14221,7447,4,0,1,1,0),
(14221,9856,3.8,0,1,1,0),
(14221,6986,3.6,0,1,1,0),
(14221,9859,3.5,0,1,1,0),
(14221,7437,3.3,0,1,1,0),
(14221,9850,3.1,0,1,1,0),
(14221,9849,3.1,0,1,1,0),
(14221,7448,2.9,0,1,1,0),
(14221,7461,2.8,0,1,1,0),
(14221,7407,2.7,0,1,1,0),
(14221,9861,2.6,0,1,1,0),
(14221,9855,2.5,0,1,1,0),
(14221,7438,2.4,0,1,1,0),
(14221,9848,2.4,0,1,1,0),
(14221,9870,2.3,0,1,1,0),
(14221,1708,2.2,0,1,1,0),
(14221,9868,2.1,0,1,1,0),
(14221,7369,2,0,1,1,0),
(14221,7446,2,0,1,1,0),
(14221,7353,1.9,0,1,1,0),
(14221,9869,1.9,0,1,1,0),
(14221,7444,1.8,0,1,1,0),
(14221,9863,1.8,0,1,1,0),
(14221,9871,1.7,0,1,1,0),
(14221,7435,1.6,0,1,1,0),
(14221,7436,1.6,0,1,1,0),
(14221,7418,1.5,0,1,1,0),
(14221,7434,1.5,0,1,1,0),
(14221,7462,1.4,0,1,1,0),
(14221,7443,1.4,0,1,1,0),
(14221,9851,1.3,0,1,1,0),
(14221,9846,1.3,0,1,1,0),
(14221,7433,1.3,0,1,1,0),
(14221,9862,1.3,0,1,1,0),
(14221,9845,1.2,0,1,1,0),
(14221,9872,1.2,0,1,1,0),
(14221,7458,1.2,0,1,1,0),
(14221,9854,1.1,0,1,1,0),
(14221,9891,1.1,0,1,1,0),
(14221,9852,1.1,0,1,1,0),
(14221,1710,1.1,0,1,1,0),
(14221,7457,1.1,0,1,1,0),
(14221,7456,1.1,0,1,1,0),
(14221,24047,5,1,-24047,1,0),
(14221,24052,1,1,-24052,1,0),
(14221,24054,1,1,-24054,1,0),
(14221,24056,1,1,-24056,1,0);
```

**Comment by Grz3s** [comment]
ability .. comes from 4.x.x
