### ISSUE TITLE
[Classic - WotLK] Skhowl (rare spawn) - Alterac Mountains - Drops

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#194]
```
-- Skhowl

--Corrected loot drop
DELETE FROM creature_loot_template WHERE  entry = 2452;
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(2452,1477,0.14,0,1,1,0),
(2452,1708,3,0,1,1,0),
(2452,1710,1.4,0,1,1,0),
(2452,1725,0.42,0,1,1,0),
(2452,1783,0.7,0,1,1,0),
(2452,1809,0.4,0,1,1,0),
(2452,1829,0.3,0,1,1,0),
(2452,1830,0.2,0,1,1,0),
(2452,2289,0.42,0,1,1,0),
(2452,2772,0.84,0,1,1,0),
(2452,2786,0.05,0,1,1,0),
(2452,2838,0.42,0,1,1,0),
(2452,3011,75,0,1,1,0),
(2452,3385,0.7937,0,1,1,0),
(2452,3720,-80,0,1,1,0),
(2452,3771,4,0,1,1,0),
(2452,4304,1.5873,0,1,1,0),
(2452,4636,1.28,0,1,1,0),
(2452,5637,3,0,1,1,0),
(2452,6331,25,0,1,1,0),
(2452,8146,3.1746,0,1,1,0),
(2452,24047,5,1,-24047,1,0),
(2452,24052,1,1,-24052,1,0),
(2452,24053,0.5,1,-24053,1,0),
(2452,24054,1,1,-24054,1,0),
(2452,24056,1,1,-24056,1,0),
(2452,24058,5,1,-24058,1,0);
```

**Comment by adellaci** [comment]
@Grz3s 

These look reasonably for drops. Let me know what you think.

**Comment by Phatcat** [comment]
@adellaci 
I don't think they look unreasonable, but where have you got them?
I can see you did not get them from here; https://web.archive.org/web/20061230211724/http://wow.allakhazam.com/db/mob.html?wmob=2452

**Comment by adellaci** [comment]
Thank you for the information, i'll make the changes.

**Comment by Phatcat** [comment]
You can thank me for this one instead; https://docs.google.com/spreadsheets/d/1Bli1uzBZD8hyphXF_QqaFpLmpLNAZKd5ItDp9U_yOrs/edit#gid=0

atm it is only missing instanced rares. and yes, I plan on finishing it.

**Comment by adellaci** [comment]
I've been fishing through archive.org. Great stuff

**Comment by Phatcat** [comment]
my list is however made for vanilla, be aware of that so you may have to check up if loot for some of these changed for wrath.
