### ISSUE TITLE
Ability to label

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#196]
@Grz3s 

Can i get the ability to put labels on the issues i post?

**Comment by Grz3s** [comment]
can you explain pls?

**Comment by Rushor** [comment]
in github itself - you can see on the top right hand corner the fields for: Labels, Milestone and Assignee.
Adellaci wants to be a member of the project in order to get the rights to add a [Label] under the field: Labels ^^

**Comment by adellaci** [comment]
Yes that is correct.

**Comment by Grz3s** [comment]
I can't help you with this:
only person who have rights to add/remove ppl here is x-savior ..
You need to speak with him

**Comment by adellaci** [comment]
Fair enough thank you very much I'll try to get ahold of him


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by Rushor** [comment]
i infomed x-savior in the vengeancewow iirc chat

**Comment by adellaci** [comment]
@Grz3s 

I will close this one out 10/16/16 if you don't have any objections

**Comment by Grz3s** [comment]
@adellaci ... im not using this Issue tracker anymore:
You can close it :)
