### ISSUE TITLE
Glowing Sanctified Shard

### ISSUE THREAD

**Issue by DaMadBoy** [unified-db/Database#197]
In item_template. 

Spelltrigger_1 has a value of 3, is this meant to be 4 as it is a  Soulstone?  

Item name: Glowing Sanctified Shard
Item id: 23442

**Comment by Grz3s** [comment]
Item id: 23442 - "Glowing Sanctified Crystal"
its a quest item...
Player will recive it after using another item on "damaged" Uncontroled Voidwalker
Just checked this quest.. and all works fine...

May I ask why you asking about it?

**Comment by DaMadBoy** [comment]
Because it is the only item in the database that has a spell trigger of 3 and no wiki anywhere has any info for this trigger value. Does this mean the trigger of 3 would be a spell being cast upon it? 

I would have thought more items would have this trigger if that is the case.

**Comment by Grz3s** [comment]
Wiki probably missing a lots ...
Item_template data comes from WDB... and nothing should be changed inside.. 
For us important is ..that Item works fine...
