### ISSUE TITLE
*INTERAL* - UDB slow progress

### ISSUE THREAD

**Issue by Grz3s** [unified-db/Database#198]
Hi all
Recently u may see ..that from almost 2 weeks not much going on ... 
REason for this is as some of you may know... is (legal action - if i may say that) --  blizz took against priv serv.. *Nost...*

This situation leads to few qustions:
- if stuff im working on is 100% safe... 
- what impact it may have on our small projects..

Im sure not only me asking same question...  i see many of smaller projects slowed down after this *incydent*...
We'll see what future will bring and if i'll and other will be able to come back to do what we love doing ;)

BTW:
I never had anything to do with *nost* project ... 

Regards

**Comment by Rushor** [comment]
well other project like vengeance wow and warmane profit from this stuff. I think as far as noone makes money with it's privatserver and as long as the the player number does not go over 13000 at peak time, there will we not problem with blizz :)

**Comment by Ulduar** [comment]
Do not worry, in terms of European and Russian legislation in the educational purposes you can work.

**Comment by Grz3s** [comment]
Will see ..

**Comment by Grz3s** [comment]
hi friends...
Unfortunately... I have some difficulties in private life and i have to deal with it...
It is for me more important than wow / eurocup :( etc... 
I cannot continue any work (fun) ... until main thing will be sorted..(I hope it will)
Sory to everyone...

**Comment by Rushor** [comment]
good luck with everything @Grz3s, i hope everything will be well soon :)

**Comment by cyberium** [comment]
I wish you the best for your issue. May the chance be with you.

**Comment by xfurry** [comment]
@Grz3s I'm sad to see you leave, but at the same time we all understand that personal life is always the top priority.
I wish you all best, and I hope that everything will be well!

**Comment by Grz3s** [comment]
![fueife](https://cloud.githubusercontent.com/assets/2374069/17865799/cdf6d3ee-689b-11e6-8d78-d1ea7ddd3ef7.jpg)

**Comment by Grz3s** [comment]
![here](https://cloud.githubusercontent.com/assets/2374069/17947921/a306acf2-6a46-11e6-821c-6ddd09803916.jpg)

**Comment by xfurry** [comment]
:question:

**Comment by malcrom** [comment]
It was for me. I sniffed it for him.

**Comment by Phatcat** [comment]
I'm sorry to be... very late... with these 'news' but there is NOTHING WHATSOVER illegal about emulation, packet sniffing or even breaking an EULA.

Companies such as Sony, Nintendo, and others, have all tried shutting down emulation before, and pretty much all failed.


https://en.wikipedia.org/wiki/Server_emulator

> If the complete emulator is a work of its own, copyright violation is not as obvious as EULA violation (see Lotus v. Borland case).

--

https://en.wikipedia.org/wiki/Lotus_Development_Corp._v._Borland_International,_Inc.

> The Lotus decision establishes a distinction in copyright law between the interface of a software product and its implementation. The implementation is subject to copyright. The public interface may also be subject to copyright to the extent that it contains expression (for example, the appearance of an icon). However, the set of available operations and the mechanics of how they are activated are not copyrightable.[7]:211-215 This standard allows software developers to create competing versions of copyrighted software products without infringing the copyright.

Let's.. Let's take that last part once more:

> the set of available operations and the mechanics of how they are activated are **not copyrightable**.[7]:211-215 This standard allows software developers to create competing versions of copyrighted software products **without infringing the copyright**.

Blizzard neither can, nor will ever be bringing any DMCA (which would by the way be false) up in here, or they would be liable to penalty under perjury.
