### ISSUE TITLE
[WotLK] Quests cannot be obtained

### ISSUE THREAD

**Issue by apo126** [unified-db/Database#202]
- [x] Quest 3446 "Into the Depths" cannot be obtained.
- [x] Quest 3447 "Secret of the Circle" cannot be obtained.
- :x: Quest 4241 "Marshal Windsor" cannot be obtained.
Or the above quests are marked obsolete, please check.

- [x] Item 10697 "Enchanted Azsharite Felbane Dagger" cannot weaken the servants of Razelikh the Defiler. The servants cannot be killed.

**Comment by NeatElves** [comment]
quest 4241- 3.0.2 patch removed http://wowwiki.wikia.com/wiki/Quest:Marshal_Windsor
