### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#206]
select a.guid,b.guid,a.id,b.id,a.position_x,b.position_x,a.position_y,b.position_y , a.position_z,b.position_z , a.orientation,b.orientation , a.map , b.map from creature a join creature b on (a.id=b.id and a.position_x=b.position_x and a.position_y=b.position_y and a.position_z=b.position_z and a.orientation=b.orientation and a.map = b.map and a.guid<>b.guid) where not exists(select d.guid from game_event_creature d where a.guid=d.guid or b.guid=d.guid);

Run this query. The database seems to have some duplicates, feel free to check only for same "phase" duplicate data.

**Comment by Grz3s** [comment]
it gives very interesting results ....
one day i may look at this closer
thank you.

**Comment by killerwife** [comment]
Np, I thought I would share since we found about 130 duplicate entries in our VOA TBC-DB
