### ISSUE TITLE
Database standardisation

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#207]
Alright, lets drop the bomb.

The databases have varying columns and its a general nightmare to port stuff. (example creature_template has EquipmentTemplateId in TBC-DB and creature has equipment_id). Also we miss a lot of FKs throughout the database. Not only would FKs enable a cleaner database with less errors (doing it code side is a nightmare), but would promote cleaner database development.

Currently it is a nightmare to do stuff efficiently. While some tables were fixed over the years there is still a ton of inconsistencies.

Your thoughts?

@cala @X-Savior @xfurry @Grz3s @Tobschinski @evil-at-wow

**Comment by Muehe** [comment]
Actually there has been a [forum discussion](http://cmangos.net/thread-7250.html) about this before, sadly it did not lead to anything really. I even [compared the DBs](http://cmangos.net/thread-7255.html) against each other, which might come in handy if you want to push this issue. The list might be outdated though, will see if I can find that python script I used anywhere.

Anyway, I assume first order of buisness would be to agree on a code style. shiendra proposed a style guide to use in the first thread I linked, but there wasn't any feedback on that.

**Comment by killerwife** [comment]
Yes thats because maximus is incredibly busy. My eventual plan is to do this after I sync VoA TBC-DB with UDB. I posted this thread because I knew it would take a while for this to get noticed. We will see what the gurus will say.

But yes, most likely proper renaming will be done in one step, and the possible FKs would be second step.
