### ISSUE TITLE
NPC Vhel'kur pathing

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#208]
This creature http://www.wowhead.com/npc=21801/vhelkur is missing pathing. 
Currently we do not have any data on his path in any database, most likely due to him being invisible without spirit goggles. Let me know if you have any data, I can tell someone to script and and then PR it here. If not, we will need to improvise.

**Comment by Grz3s** [comment]
yes.. i have all data for this creature...
and will fix it .. when I'll find time ..
thx for report

**Comment by killerwife** [comment]
Awesome, btw I just backported updatepack 406 to TBC, amazing pathing in SMV I have to say.

**Comment by Grz3s** [comment]
I had fun to redoing that zone :)... 
P.S
this was only preparation to DK Zone - all phases etc... heh was hard :)

**Comment by killerwife** [comment]
Yup, still a lot of things to do there tho. But mostly core side. I hope I can get TBC-DB synched with UDB in the coming months. 407 and 408 still missing mostly. Then I can provide more valuable feedback.

**Comment by Grz3s** [comment]
I wouldnt say that ... many things are missing in SMV... (5% max)... U'll see after addding 407/408 ;)

**Comment by Rushor** [comment]
datas: https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/6.x/world/01_2015_03_21/2015_04_17_01_world_2015_04_04_03.sql

**Comment by killerwife** [comment]
@Grz3s just look if the data is legit or its not up to your standard :)

**Comment by Grz3s** [comment]
wps - are legit..
aura - not (both trinity and Cmangos has same problem with FlySpeed, some ppl trying to fix this by using auras for fly and spd...etc,,(We wont) 
Sniff for this creature shows 2 auras '37509 37497'.
Thx @rushor for data
