### ISSUE TITLE
[WotLK] Quest 9738 and 10898

### ISSUE THREAD

**Issue by apo126** [unified-db/Database#209]
- [x]  The NPC "Earthbinder Rayge" is missing, so the quest 9738 "Lost in Action" cannot be finished.

- [x]  The pathfinding of Skywing seems wrong and it cannot get to the right place, so the quest 10898 "Skywing" cannot be finished.
Please kindly check. Thank you!

**Comment by xfurry** [comment]
Poke @killerwife
He might know more details about this.
However I'm pretty sure that 10898 works.

**Comment by killerwife** [comment]
@xfurry skywing has issues related to MMAPs and Lost in Action is not thoroughly scripted even on vengeance.

For skywing try disabling MMAPs or tweaking them (I am using custom ones and still had to disable usage on one waypoint)

For Lost in Action its more complicated. Afaik it needs dbscripts, eventai and even more shenanigans. XS did something with it lately but it still isnt done on vengeance either. (eventai part is in public ACID tho)

**Comment by Grz3s** [comment]
fixed some time ago
