### ISSUE TITLE
851 - Verog the Dervish

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#21]
Verog don't spawn, i killed many kolkars but verog don't spawn

**Comment by Tauriella** [comment]
I have testet with UDB_408_Beta and works fine

**Comment by Dainara82** [comment]
i use the same UDB version,
can you tell me the coords maybe i was on the wrong positions

**Comment by Schmoozerd** [comment]
He is spawned with EventAI and some chance.

**Comment by Grz3s** [comment]
yes ... 
he spawns with % Chance. .. just tested and works fine.
I also found that his ability is missing ... so I'll add it to ACID...
thx for your report.
