### ISSUE TITLE
Ring of Blood: Mogor

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#211]
Currently a very specific event can occur that if players die(or run away) during the phase transitions when he has unit flag UNATTACKABLE he will be stuck with the flag until server restart. Therefore the flag should be removed at "reached home" just to be sure.

I used this query to fix it up but you propably want a proper change in ACID:

UPDATE creature_ai_scripts SET action2_type=19,action2_param1=2 WHERE id=1806911;

@Grz3s

**Comment by Grz3s** [comment]
:)
but who could run away in that moment :)

**Comment by killerwife** [comment]
Well, dont ask me. It just broke the event until server restart :D

**Comment by Grz3s** [comment]
done.
thanks :+1:
