### ISSUE TITLE
[WotLK] The quest 8945

### ISSUE THREAD

**Issue by apo126** [unified-db/Database#212]
The quest 8945 "Dead Man's Plea"
If you do it normally, you should meet Baron Rivendare within the Buff time, then you will find Ysida is missing.
However, I do it this way, use the command .go and teleport to where Baron Rivendare is immediately after receipt of the Buff, then you will find Baron Rivendare's killing of Ysida.
So I think the time for the execution of Ysida is wrong. Please check.

**Comment by xfurry** [comment]
This should have been fixed here: https://github.com/cmangos/mangos-wotlk/commit/37d046b2579670fab9e41578303d142b1aabf15c

Feel free to reopen the ticket if ti's still a problem.
