### ISSUE TITLE
Syntax error in 487_quest_8945.sql

### ISSUE THREAD

**Issue by apo126** [unified-db/Database#220]
UPDATE creature_template SET FactionAlliance = 794, FactionHorde = 794, UnitFlags = 131072 WHERE Entry = 16031

The correct is below:
UPDATE creature_template SET FactionAlliance = 794, FactionHorde = 794, UnitFlags = 131072 WHERE Entry = 16031;

**Comment by Grz3s** [comment]
thx for report:
https://github.com/unified-db/Database/commit/132e0e3a376b544eb2cff73bb8f1ee1bc57b5ae7
