### ISSUE TITLE
[WotLK] Missing leatherworking trainer in Undercity (Arthur Moore - 4588)

### ISSUE THREAD

**Issue by Vladskywolf** [unified-db/Database#227]
Undercity's leatherworking trainer, Arthur Moore (creature_template id 4588) is missing. He should be located in the Rogue's Quarter at around x:1510.42, y:199.876, z:-62.1389. This is behind Gillian Moore, the Leather Armor Merchant, and just in front of the standing caskets (as per info and screenshots in Wowhead and WowWiki).

In the interim, I used the following sql statement to add him:

`-- Arthur Moore - Undercity Leatherworking Trainer

INSERT INTO creature (id, map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, DeathState, MovementType) VALUES
(4588,0,1,1,0,0,1510.42,199.876,-62.1389,3.74561,300,0,0,1342,0,0,0);
`

**Comment by Grz3s** [comment]
:+1:  thx for report...
