### ISSUE TITLE
[WotLK] Quest ID 872 'The Disruption Ends' has incorrect previous quest id

### ISSUE THREAD

**Issue by Vladskywolf** [unified-db/Database#228]
Quest id 872 'The Disruption Ends', located in the Barrens, has an incorrect previous quest id assigned, 5041 'Supplies for the Crossroads'. It should be quest id 871 'Disrupt the Attacks'. Verified via [WowWiki](http://wowwiki.wikia.com/wiki/Quest:The_Disruption_Ends) and various guides.

**Comment by Grz3s** [comment]
yes you are right...
I just checked my old collection ..with "levelling guide" vids. (one for vanilla ..second for wotlk)
and here's a proof:
![qst](https://cloud.githubusercontent.com/assets/2374069/16818427/a3b6d79e-493f-11e6-85a3-bb3cf2888f5f.jpg)

and here:

![qs2](https://cloud.githubusercontent.com/assets/2374069/16818432/aa7d1e1c-493f-11e6-9112-c60ca17b33f9.jpg)

I'll correct it .. soon*
