### ISSUE TITLE
[WotLK] Lesser Darkmoon Decks should NOT require Inscription to turn in

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#229]
Rogues Deck, Mages Deck, Swords Deck and Demons Deck are created by Scribes, but can be sold via AH and should be usable by anyone to get the prize and Rep.

[Source 1](http://www.wowhead.com/quest=12517/rogues-deck#comments:id=407871), [Source 2](http://www.wowhead.com/quest=12518/mages-deck#comments:id=1954567), [Source 3](http://www.wowhead.com/item=37164/swords-deck#comments:id=407954), [Source 4](http://www.wowhead.com/quest=13311/demons-deck#comments:id=1717045), [Source 5](http://wowwiki.wikia.com/wiki/Inscription#Darkmoon_cards).

Suggested fix:

```
UPDATE quest_template SET RequiredSkill = 0, RequiredSkillValue = 0 WHERE entry IN 
(12517,  /* Rogues Deck */
12518,   /* Mages Deck */
12798,   /* Swords Deck */
13311);  /* Demons Deck */
```

**Comment by Grz3s** [comment]
:+1:
