### ISSUE TITLE
WotLK - in the Cave before Wailing Caverns

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#23]
the Raptors and the goblin  you don't see, if you walk through the cave, the mobs spawning and attack you, i think they are in the wall or anywhere

**Comment by xfurry** [comment]
Do you have vmaps active? (latest version of course)

**Comment by Dainara82** [comment]
i have the vmaps exportet from the client 3.3.5a
i extractet it under linux but not with the actual version from git   i extracted it bevore 3 or 4 mont's
does the extraction change?  should i extract vmaps, dbs, mmaps and maps newly?

**Comment by Grz3s** [comment]
Goblin - Mad Magglish has aura [http://www.wowhead.com/spell=22766/sneak] - so yes ..u can be souprised when he will attaack you :]
Raptors - Deviate Stalker - same as above...
Raptors - Deviate Stalker - this one has a wrong EventAi - set (shouldnt use sneak aura) - i'll fix that soon for ACID ;)
Thank you for your report...
