### ISSUE TITLE
[WotLK] Quest 12188 "The Forsaken Blight and You: How Not to Die"

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#230]
The quest currently requires BOTH q12182 "To Venomspite!" and q12189 "Imbeciles Abound!" to be completed. (ExclusiveGroup = -12182)
Should be EITHER one of those. (ExclusiveGroup = 12182)

[Source 1](http://www.wowhead.com/quest=12182/to-venomspite#comments:id=1160885), [Source 2](http://www.wowhead.com/quest=12189/imbeciles-abound#comments:id=455168:reply=57601).

Suggested fix:
```
UPDATE quest_template SET ExclusiveGroup = 12182 WHERE entry IN (12182, 12189);
```

**Comment by Grz3s** [comment]
good catch :+1:
