### ISSUE TITLE
[Classic - WotLK] Warlock's Imp and Succubus have wrong class

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#231]
Warlock's Imp and Succubus have UnitClass = 1 (Warrior) and because of this, they can't use any abilities (abilities require Mana and they have Rage). All other Warlock Pets have UnitClass = 2 (Paladin) and work fine.

Suggested fix:

```
UPDATE creature_template SET UnitClass = 2 WHERE entry IN 
(416,    /* Imp */
1863);   /* Succubus */
```

**Comment by Grz3s** [comment]
thx :+1:
