### ISSUE TITLE
[WotLK] Quest 11979 "The Taunka and the Tauren"

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#232]
Quest 11979 "The Taunka and the Tauren" is supposed to be alternate starting point for quest 11978 "Into the Fold" for players, who come from the east. Players who come from the west get quest 11977 "A Tauren Among Taunka".

Currently q11979 "The Taunka and the Tauren" does not unlock q11978 "Into the Fold", because "Into the Fold" has PrevQuestId = 11977 ("A Tauren Among Taunka").

Also, q11977 "A Tauren Among Taunka" and q11979 "The Taunka and the Tauren" both have ExclusiveGroup =0, so players can complete both. Should be only one.

[Source 1](http://www.wowhead.com/quest=11977/a-tauren-among-taunka#comments:id=872017), [Source 2](http://www.wowhead.com/quest=11979/the-taunka-and-the-tauren#comments:id=552426).

Suggested fix:

```
-- Remove PrevQuestId from q11978 "Into the Fold"
UPDATE quest_template SET PrevQuestId = 0 WHERE entry = 11978;

-- Make q11977 "A Tauren Among Taunka" and q11979 "The Taunka and the Tauren" exclusive
-- Add q11978 "Into the Fold" as NextQuestId to both quests
UPDATE quest_template SET ExclusiveGroup = 11977, NextQuestId = 11978 WHERE entry IN (11977, 11979);
```

**Comment by Grz3s** [comment]
good job :+1:
