### ISSUE TITLE
[WOTLK] Typo in game_tele

### ISSUE THREAD

**Issue by jungleman2** [unified-db/Database#233]
there is 'ArgentTourna**mnet**Grounds'

fix:
UPDATE `game_tele` SET `id`='1418',`position_x`='8374.07',`position_y`='794.042',`position_z`='547.921',`orientation`='6.22349',`map`='571',`name`='ArgentTournamentGrounds' WHERE `id`='1418';

**Comment by Grz3s** [comment]
:+1:
