### ISSUE TITLE
[WotLK] Quest 12312 "Secrets of the Scourge"

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#234]
Currently, q12312 "Secrets of the Scourge" requires q12311 "The Noble's Crypt" to be completed (PrevQuestId = 12311). Should require q12309 "Find Durkon!" (PrevQuestId = 12309).

[Source 1 (video)](https://www.youtube.com/watch?v=XxDWlZA5jN8). Note how on the last second of video turning in q12309 "Find Durkon!" pops 2 quest marks on minimap - one for q12311 "The Noble's Crypt" and one for q12312 "Secrets of the Scourge". Proves that both quests are unlocked by q12309 "Find Durkon!"

[Source 2 (video)](https://www.youtube.com/watch?v=FsCyzPih-ZI). Note how on very first second of video the quest mark for q12312 "Secrets of the Scourge" is visible before q12311 "The Noble's Crypt" is even accepted. Proves that q12311 "The Noble's Crypt" is not a requirement for q12312 "Secrets of the Scourge".

Suggested fix:

`UPDATE quest_template SET PrevQuestId = 12309 WHERE entry = 12312;
`

**Comment by Grz3s** [comment]
:+1:
