### ISSUE TITLE
Shadowfiend visual

### ISSUE THREAD

**Issue by Phatcat** [unified-db/Database#235]
https://github.com/lovelol/server/commit/e8770f8279bc9e69039b2213e64d9b23d60d592c

**Comment by Darth-Postal** [comment]
Says "Page not found".

**Comment by Phatcat** [comment]
Yeah, he just deleted the repo.
Robin is the owner. give me a second, I fetched his repo locally so I will just post the update here.

**Comment by Phatcat** [comment]
UPDATE `creature_template_addon` SET `auras`='34424' WHERE (`entry`='19668');

**Comment by Phatcat** [comment]
I cannot get that to look good no matter how I try to format it -.-

**Comment by Grz3s** [comment]
hmm...
Source?

We have this aura 34429 ... is it wrong?

**Comment by Phatcat** [comment]
Actually, the original commit did say that it closed an issue, but since it was archived it didn't like to the actual issue.

@robinsch This is your change, do you recall where you got this info?

**Comment by Phatcat** [comment]
> Id: 34429
Name: Shadowform
General info
Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (8207, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x00000000 00000000 00000000
SpellSchoolMask = 1 (SCHOOL_MASK_PHYSICAL, SCHOOL_MASK_ALL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000180 (SPELL_ATTR_UNK7, SPELL_ATTR_UNK8)
AttributesEx1: 0x00000400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 15
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 30 (SPELL_AURA_MOD_SKILL), value = 15, misc = 162 (162), miscB = 0, periodic = 0
Effect 1:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -90
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 10 (SPELL_AURA_MOD_THREAT), value = -90, misc = 127 (127), miscB = 0, periodic = 0
Effect 2:
Id: 46 (SPELL_EFFECT_SPAWN)
BasePoints = 1
Targets (0, 0) (NO_TARGET, NO_TARGET)

- 

> Id: 34424
Name: Shadow Armor
General info
Category = 0, SpellIconId = 9, ActiveIconId = 0, SpellVisual = (8205, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x00000000 00000000 00000000
SpellSchoolMask = 1 (SCHOOL_MASK_PHYSICAL, SCHOOL_MASK_ALL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000010 (SPELL_ATTR_UNK4)
AttributesEx1: 0x10000000 (SPELL_ATTR_EX_UNK28)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1000
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1000, misc = 0 (0), miscB = 0, periodic = 0
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

Judge for yourself.

**Comment by robinsch** [comment]
Oh sorry I just saw my mention now. This was not sniffed, I just took 34424 because the spell visual matches retail look (check out Hydra 5 or other videos) and made the dummy give 1000 resistance to all schools.
