### ISSUE TITLE
[WotLK] Missing Exploration BaseXP Data for LvL 70-80

### ISSUE THREAD

**Issue by Darth-Postal** [unified-db/Database#236]
Currently UDB only has Exploration_BaseXP data up to LvL 70 (and LvL 70 says 1300 when it should be 1250).

After Cata, WoW uses new system where exploration XP is based on character LvL, not zone LvL, so its very hard to find WotLK-era data for this, but I gave it my best shot. 

I watched a bunch of YouTube videos from 2009-2010 (non of them are mine), and whenever I saw "Discovered: XXXX, Experience Gained YYYY" message in the video, I cross-referenced XXXX with AreaTable.dbc to get Area Level. 

With this technique, I was able to find data for all levels, except 79. ~~I took an educated guess and used the value from LvL 78 for LvL 79 also.~~ UPDATE: LvL 79 gives 2200 XP. Researched by @Grz3s.

Here comes the list of Zones, their LvL, their BaseXP and YouTube videos (not mine), starting from the moment where you can see "Discovered: XXXX, Experience Gained YYYY" message:

Wyrmskull Village (LvL 70)
1250 XP https://youtu.be/xo5ySs9W6wo?t=11m41s

Glittering Strand (LvL 71)
2000 XP https://youtu.be/UvbdW9rAJSs?t=57s

Kili'lua's Atoll (LvL 72)
2050 XP https://youtu.be/UvbdW9rAJSs?t=16s

The Wicked Coil (LvL 73)
2050 XP https://youtu.be/FvprRAxDky8?t=1m15s

Reliquary of Pain (LvL 74)
2100 XP https://youtu.be/GGgjESoFN3U?t=1m15s

Voltarus (LvL 75)
2100 XP https://youtu.be/GGgjESoFN3U?t=2m23s

Rainspeaker Canopy (LvL 76)
2100 XP https://youtu.be/kOBU5wPmjTs?t=1m13s

Hardknuckle Clearing (LvL 77)
2150 XP https://youtu.be/kOBU5wPmjTs?t=1m24s

The Bombardment (LvL 78)
2150 XP https://youtu.be/9y8cHTm0tOU

The Shadow Vault (LvL 80)
2200 XP https://youtu.be/9y8cHTm0tOU

Based on above, suggested fix:

```
-- Add Exploration BaseXP data for LvL 70-80 zones
DELETE FROM exploration_basexp WHERE level BETWEEN 70 AND 80;
INSERT INTO exploration_basexp (level, basexp) VALUES
(70, 1250),
(71, 2000),
(72, 2050),
(73, 2050),
(74, 2100),
(75, 2100),
(76, 2100),
(77, 2150),
(78, 2150),
(79, 2200),
(80, 2200);
```

**Comment by Grz3s** [comment]
I like your work... all clear... and always with details.
:+1:

**Comment by boxa** [comment]
from YTDB:
70, 1250
71, 1330
72, 1370
73, 1410
74, 1440
75, 1470
76, 1510
77, 1530
78, 1600
79, 1630

**Comment by Darth-Postal** [comment]
Source for these numbers? 

I posted a video for each level. I don't see how those videos can ALL be incorrect.

**Comment by Grz3s** [comment]
hi... sory for long delay on this...
Well... @boxa your values look nice.. but i think they were changed in later expansions for smth like u got...
I spent last week... checking 2 lvling guides...
And It looks like that @Darth-Postal  is right... (wotlk - had diff values for lvl 70-80)
Only 79th lvl u made wrong :)
This is what I found...

``` code
-- Patch 3.3
-- lvls xps
Baleheim           -- 70  -- 1250
Nifflevar          -- 70  -- 1250
Westguard Keep     -- 70  -- 1250
Ember Spear Tower  -- 70  -- 1250
Gjalerbron         -- 70  -- 1250 (player lvl 71)

Ember Clutch       -- 71  -- 2000
Frostblade Peak    -- 71  -- 2000 (player lvl 70)
Chillmere Coast    -- 71  -- 2000 (player lvl 71)
Gjalerhorn         -- 71  -- 2000 (player lvl 71)
Moonrest Gardens   -- 71  -- 2000 (player lvl 71)
The Briny Pinnacle -- 71  -- 2000 (player lvl 71)

Icemist Village    -- 72  -- 2050 (player lvl 71)
The Pit of Narjun  -- 72  -- 2050 (player lvl 71)
Kili’ua’s Atoll    -- 72  -- 2050 (player lvl 72)    
Azure Dragonshrine -- 72  -- 2050 (player lvl 72) 
Ruby Dragonshrine  -- 72  -- 2050 (player lvl 73)


Wintergarde Keep   -- 73  -- 2050  (player lvl 71)
Amberpine Lodge    -- 73  -- 2050  (player lvl 73) 
Nozzlerust Post    -- 73  -- 2050  (player lvl 73)   

The Broken Bluffs   -- 74 -- 2100   (player lvl 71)
The Dragon Wastes   -- 74 -- 2100   (player lvl 72)
The Carrion Fields  -- 74 -- 2100   (player lvl 72)
Ruins of Drak’Zin   -- 74 -- 2100   (player lvl 73)
Vordrassil’s Limb   -- 74 -- 2100   (player lvl 74)
Drakil’jin Ruins    -- 74 -- 2100   (player lvl 75)

Light’s Breach      -- 75 -- 2100   (player lvl 75)
Rageclaw Den        -- 75 -- 2100   (player lvl 75)
Altar of Sseratus   -- 75 -- 2100   (player lvl 76)
Kolramas            -- 75 -- 2100   (player lvl 76)

Pools of Jin’Alai   -- 76 -- 2100   (player lvl 76)
Altar of Rhunok     -- 76 -- 2100   (player lvl 76)
Heb’Drakkar         -- 76 -- 2100   (player lvl 76)

Dubra’Jin           -- 77 -- 2150   (player lvl 77)
The Argent Vanguard -- 77 -- 2150   (player lvl 77)
The Breach          -- 77 -- 2150   (player lvl 77)
Ironwall Dam        -- 77 -- 2150   (player lvl 79)

Sindragosa’s Fall               -- 78 -- 2150   (player lvl 77)
Aldur’thar: The Desolation Gate -- 78 -- 2150   (player lvl 77)
Stormcrest                      -- 78 -- 2150   (player lvl 79)

The Pit of Fiends               -- 79 -- 2200   (player lvl 77)
Valley of Ancient Winters       -- 79 -- 2200   (player lvl 79)

Crusaders’ Pinnacle -- 80 -- 2200   (player lvl 77)
Icecrown            -- 80 -- 2200   (player lvl 77)
Ymirheim            -- 80 -- 2200   (player lvl 77)
The Shadow Vault    -- 80 -- 2200   (player lvl 78)
Valhalas            -- 80 -- 2200   (player lvl 78)
Icecrown Citadel    -- 80 -- 2200   (player lvl 79)
```

**Comment by Darth-Postal** [comment]
Well, I did warn that I guessed LvL 79. Looks like I guessed wrong.  :disappointed:

Thank you for verifying this, @Grz3s. I updated the patch in the OP with correct data for 79.
