### ISSUE TITLE
[WotLK] Ilkrud Mathrull's Succubus Minion - Invalid Traget

### ISSUE THREAD

**Issue by adellaci** [unified-db/Database#237]
Ilkrud Magthrull - Entry 3664 - GUID - 32439
Succubus Minion - Entry 10928 - GUID - 2 - Petnumber - 591

When I start the fight with Ilkrud Magthrull he spawns a Succubus Minion. Any attack I use on her, says "Invalid Target". I was using my Druid, and had the buff "Thorns" on. She took damage from that buff, but no damage from any of my spells or physical attack. Also once I kill Ilkrud Magthrull, Minion does not de-spawn.

**Comment by Darth-Postal** [comment]
I think this is a Core issue, because same thing happens with [Wastewander Shadow Mages](http://www.wowhead.com/npc=5617/wastewander-shadow-mage) in Tanaris. Their Voidwalkers can not be attacked.

I can't say about Ilkrud, but I'm positive, those Shadow Mages' Voidwalkers worked fine few month ago. Possible problem with recent Pet Patch.

**Comment by killerwife** [comment]
Please post it on core bug github.

**Comment by Grz3s** [comment]
this may also be related to this:
https://github.com/cmangos/issues/issues/1039#issuecomment-238992493
```quote
now ... if your controled creature gets aggro from anyone ...you loosing control on it... he just runs for few secs .. out of your control... ...and this repeats every moment, when you are hit by someone :(
 Basically it looks now like this:
https://youtu.be/kdSEk3BS9SU
```
not only that ... if u want to attack anyone ... it shows "EVADE" on creature every your hit.

**Comment by Phatcat** [comment]
Unlikely a core issue, please verify that you do not set any unwanted flags for these creatures.

**Comment by Darth-Postal** [comment]
Works fine with same DB but earlier core:
https://github.com/cmangos/issues/issues/1044#issuecomment-239759463

**Comment by killerwife** [comment]
@Phatcat maybe ur forgetting to set one of the mandatory runtime flags, which causes it to fail?

**Comment by Phatcat** [comment]
@killerwife https://github.com/cmangos/issues/issues/1044#issuecomment-239726970

**Comment by Phatcat** [comment]
Succubus Minion has ExtraFlags = 2. That is:
>    CREATURE_EXTRA_FLAG_CIVILIAN               = 0x00000002,       // not aggro (ignore faction/reputation hostility)

Not saying removing it will fix the issue (still on it) but it probably shouldn't have that flag.

**Comment by Darth-Postal** [comment]
Yes, you are correct.

`
UPDATE creature_template SET ExtraFlags = 0 WHERE Entry = 10928;`

This should fix the part, where Succubus doesn't attack you. But not the part, where you can't attack her.

**Comment by Phatcat** [comment]
The Voidwalker Minion also needs to have his unit class changed to mage instead of warrior (again, this won't solve it, just another bug we may as well fix now we're at it - it needs to be downported all the way down to classic that one by the way, perhaps also the succubus one)

**Comment by Darth-Postal** [comment]
I think Voidwalker should be Paladin (UnitClass = 2) since it is a tanking minion. Imps are mages (UnitClass = 8). But definitely not warriors (UnitClass = 1).

This should do it:

`UPDATE creature_template SET UnitClass = 2 WHERE Entry = 8996;`

**Comment by Phatcat** [comment]
Pretty sure Paladin is reserved for mobs with healing spells but I'm not too sure on that. doesn't matter atm as the CreatureEventAI doesn't differantiate based on unit class (something I'm looking into changing)

**Comment by Grz3s** [comment]
Paladin (UnitClass = 2) - this class using mana (pls look at: creature_template_classlevelstats)
Voidwalker is a tanking pet. (0:mana in his stats) - class 1 warrior is correct here.

**Comment by Phatcat** [comment]
Okay, there is no way that the voidwalker minion is unit class warrior, take a look at the warlocks voidwalker - don't tell me we have 2 different classes for these 2 voidwalkers, that'd be mental... but okay, blizzard is mental.. (warlocks voidwalker is by the way correctly of the mage unit class)

**Comment by Phatcat** [comment]
Also, it was back when I introduced Pet Patch 1 for all cores that I made Classlevelstats redundant for creature pets (take a look at Pet::InitStatsForLevel), mobs load their values directly from creature_template.

Basically any non SUMMON_PET (except the hunter's pet level stats of course) can be removed; I told @cala this some time ago and he should be able to vouch for this, even though he doesn't want to pull it out yet for some reason, which is beyond me.

Look at the comment thread of https://github.com/classicdb/database/pull/829

**Comment by Grz3s** [comment]
ok... you're expert with pets not me...

I just found smth that may be interesting...
Voidwalker c.8996
creature_template  = mana = 0
pet_levelstats = mana > 0 (mana is set for all level between 1 and 70) 

So... there is smth wrong here ;]

Anyway... this wont solve problem with "Invalid Target"

**Comment by Phatcat** [comment]
> (...) again, this won't solve it, just another bug we may as well fix now we're at it (...)

I know `*sadface*`

**Comment by killerwife** [comment]
Since I do not have a wotlk up and running, I would like to point out one thing. Put a breakpoint in Spell::CheckCast and see where it throws invalid target. Then unless you will know why its throwing that, post it here, and I can help.

**Comment by Grz3s** [comment]
ok... did some digging...
pls look at this pic...
Comes from Joana vanilla levelling guide....
![vanilla](https://cloud.githubusercontent.com/assets/2374069/17716701/b292fea0-6401-11e6-8cd5-21f602c01d09.jpg)

and another one 
this one is from Wrath ... 
https://www.youtube.com/watch?v=FValICyAFxc  3:41
![wrath2](https://cloud.githubusercontent.com/assets/2374069/17716933/ecd4e44c-6402-11e6-8ec7-3109d94b7ccc.jpg)

So I was right.... this minion has nothing to do with warlocks minion...

**Comment by Phatcat** [comment]
I think that's a nice find which proves you right, yeah, and yet again proves that blizzard did a lot of inconsistent stuff. Way to let me down once again, Blizzard.

**Comment by adellaci** [comment]
fix in 
[(https://github.com/cmangos/issues/issues/1044)]
