### ISSUE TITLE
Red vs blue - Theramore

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#239]
It has come to my attention that such a script exists: 
http://www.wowhead.com/npc=5095/captain-andrews

There are training exercises going on in theramore, and I was wondering if you guys knew about it, or maybe even script it. Maybe something for @cala as well :)

**Comment by Grz3s** [comment]
they're lots of this kind of small events around azeroth:
and similar to this one... lots of them were broken when new expansions came out..
Your one was damage probably between TBC and WoTLK...

I always wanted to make script for similar one in Bloodhoof Village (broken in Wotlk)...
fight between Thontek and Hulfnar.
Its difficult to get correct data etc... but one day who knows :]

**Comment by xfurry** [comment]
I think it would be also nice to have the clock bells implemented.
On retail you can hear the bells ringing every hour in certain cities.

**Comment by killerwife** [comment]
Can you now? Get me sound IDs from sniffs and I will do it.

**Comment by xfurry** [comment]
I think there was a patch some time ago, on SD2 forum.
Not sure if I can find it, but I'll try.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/19e5402b635001e73e89ee35a19681b39659fbbe
