### ISSUE TITLE
952 - Grove of the Ancients

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#24]
after you finished the quest by the NPC "Onu <Ancient of Lore>" you get a next Quest and you should get an Item "Phial of Scrying"
but no quest in questlog and no item in inventory but "Onu <Ancient of Lore>" have an yellow ? when you talk to him

**Comment by Grz3s** [comment]
thank you for report...
i need to look up ... at "Onu" .... he has smth broken in quest chain...

**Comment by Grz3s** [comment]
Well.. to start questline with Onu .. you need to start with:
quest 947 'Cave Mushrooms'
also:
quest 961 ... should be available only if we'll lose source item for ... 'The Master's Glaive' ...normaly should be done by gossip_options -- no idea why they tried to do in this way..

**Comment by Grz3s** [comment]
this will help:
https://github.com/unified-db/Database/commit/eab2c8b9f3a08b3c1936da7018c8c8d0278f6768
