### ISSUE TITLE
Missing creature spawns for quests.

### ISSUE THREAD

**Issue by DaMadBoy** [unified-db/Database#246]
I have created a list of missing creature spawns that are required in quest.
Creatures required in quests that are not currently in the creature table (in game)

Quest ID: 55 - Creature IDs: 24782
Quest ID: 409 - Creature IDs: 1946
Quest ID: 1471 - Creature IDs: 5676
Quest ID: 1474 - Creature IDs: 5677
Quest ID: 1504 - Creature IDs: 5676
Quest ID: 1513 - Creature IDs: 5677
Quest ID: 1657 - Creature IDs: 15415
Quest ID: 1689 - Creature IDs: 5676
Quest ID: 1719 - Creature IDs: 6238
Quest ID: 1739 - Creature IDs: 5677
Quest ID: 1795 - Creature IDs: 6268
Quest ID: 1819 - Creature IDs: 6390
Quest ID: 1955 - Creature IDs: 6549
Quest ID: 1957 - Creature IDs: 6550
Quest ID: 2118 - Creature IDs: 11836
Quest ID: 3520 - Creature IDs: 8612
Quest ID: 4740 - Creature IDs: 10323
Quest ID: 4961 - Creature IDs: 6549
Quest ID: 4971 - Creature IDs: 10717
Quest ID: 5056 - Creature IDs: 10737
Quest ID: 5211 - Creature IDs: 11064
Quest ID: 5282 - Creature IDs: 11122
Quest ID: 5384 - Creature IDs: 10506
Quest ID: 5561 - Creature IDs: 11627
Quest ID: 5581 - Creature IDs: 11937
Quest ID: 5721 - Creature IDs: 10936
Quest ID: 6124 - Creature IDs: 12299
Quest ID: 6129 - Creature IDs: 12297
Quest ID: 6148 - Creature IDs: 12339
Quest ID: 6481 - Creature IDs: 11920
Quest ID: 7029 - Creature IDs: 13696
Quest ID: 7041 - Creature IDs: 13696
Quest ID: 7081 - Creature IDs: 13756
Quest ID: 7082 - Creature IDs: 13756
Quest ID: 7101 - Creature IDs: 13778
Quest ID: 7102 - Creature IDs: 13778
Quest ID: 7122 - Creature IDs: 13796
Quest ID: 7124 - Creature IDs: 13796
Quest ID: 11257 - Creature IDs: 24095
Quest ID: 11255 - Creature IDs: 24124
Quest ID: 7181 - Creature IDs: 12159
Quest ID: 7202 - Creature IDs: 12159
Quest ID: 7281 - Creature IDs: 13320
Quest ID: 7282 - Creature IDs: 13154
Quest ID: 7301 - Creature IDs: 14029 14031 14030
Quest ID: 7302 - Creature IDs: 14026 14028 14027
Quest ID: 7367 - Creature IDs: 13597
Quest ID: 7368 - Creature IDs: 13598
Quest ID: 7629 - Creature IDs: 14500
Quest ID: 7631 - Creature IDs: 14502
Quest ID: 7640 - Creature IDs: 14564
Quest ID: 11249 - Creature IDs: 23671
Quest ID: 8105 - Creature IDs: 15005 15004 15002 15003
Quest ID: 8120 - Creature IDs: 15005 15004 15002 15001
Quest ID: 11246 - Creature IDs: 24095
Quest ID: 8166 - Creature IDs: 15005 15004 15002 15003
Quest ID: 8167 - Creature IDs: 15005 15004 15002 15003
Quest ID: 8168 - Creature IDs: 15005 15004 15002 15003
Quest ID: 8169 - Creature IDs: 15005 15004 15002 15001
Quest ID: 8170 - Creature IDs: 15005 15004 15002 15001
Quest ID: 8171 - Creature IDs: 15005 15004 15002 15001
Quest ID: 11227 - Creature IDs: 24000
Quest ID: 11170 - Creature IDs: 24121
Quest ID: 8490 - Creature IDs: 16364
Quest ID: 8535 - Creature IDs: 15212
Quest ID: 8536 - Creature IDs: 15307
Quest ID: 8537 - Creature IDs: 15209
Quest ID: 8538 - Creature IDs: 15206 15207 15220 15208
Quest ID: 8606 - Creature IDs: 15554
Quest ID: 8737 - Creature IDs: 15211
Quest ID: 8945 - Creature IDs: 16031
Quest ID: 8966 - Creature IDs: 16080
Quest ID: 8967 - Creature IDs: 16097
Quest ID: 8968 - Creature IDs: 16101 16102
Quest ID: 8969 - Creature IDs: 16118
Quest ID: 8989 - Creature IDs: 16080
Quest ID: 8990 - Creature IDs: 16097
Quest ID: 8991 - Creature IDs: 16101 16102
Quest ID: 8992 - Creature IDs: 16118
Quest ID: 8995 - Creature IDs: 16042
Quest ID: 9015 - Creature IDs: 16166
Quest ID: 9065 - Creature IDs: 25499
Quest ID: 9085 - Creature IDs: 16143
Quest ID: 9165 - Creature IDs: 16254
Quest ID: 9174 - Creature IDs: 16292
Quest ID: 9257 - Creature IDs: 16387
Quest ID: 9269 - Creature IDs: 16387
Quest ID: 9270 - Creature IDs: 16387
Quest ID: 9271 - Creature IDs: 16387
Quest ID: 9303 - Creature IDs: 16534
Quest ID: 9364 - Creature IDs: 16479
Quest ID: 9370 - Creature IDs: 16994
Quest ID: 9427 - Creature IDs: 17000
Quest ID: 9524 - Creature IDs: 17290
Quest ID: 9525 - Creature IDs: 17296
Quest ID: 9545 - Creature IDs: 17413
Quest ID: 9619 - Creature IDs: 5676
Quest ID: 9629 - Creature IDs: 17654
Quest ID: 9670 - Creature IDs: 17681
Quest ID: 9678 - Creature IDs: 17716
Quest ID: 9683 - Creature IDs: 17715
Quest ID: 9689 - Creature IDs: 17592
Quest ID: 9749 - Creature IDs: 17681
Quest ID: 9816 - Creature IDs: 18152
Quest ID: 9847 - Creature IDs: 18185
Quest ID: 9849 - Creature IDs: 18181
Quest ID: 9958 - Creature IDs: 18458
Quest ID: 9959 - Creature IDs: 18458
Quest ID: 9962 - Creature IDs: 18398
Quest ID: 9967 - Creature IDs: 18399
Quest ID: 9970 - Creature IDs: 18400
Quest ID: 9972 - Creature IDs: 18401
Quest ID: 9973 - Creature IDs: 18402
Quest ID: 9975 - Creature IDs: 18491
Quest ID: 9976 - Creature IDs: 18491
Quest ID: 9977 - Creature IDs: 18069
Quest ID: 9980 - Creature IDs: 18533 18494
Quest ID: 9981 - Creature IDs: 18533 18496
Quest ID: 10040 - Creature IDs: 26464 26465 26466
Quest ID: 10041 - Creature IDs: 26464 26465 26466
Quest ID: 10084 - Creature IDs: 18838
Quest ID: 10092 - Creature IDs: 18838
Quest ID: 10168 - Creature IDs: 19480
Quest ID: 10190 - Creature IDs: 19595
Quest ID: 10250 - Creature IDs: 19862
Quest ID: 10255 - Creature IDs: 16992
Quest ID: 10256 - Creature IDs: 19938
Quest ID: 10259 - Creature IDs: 19284
Quest ID: 10274 - Creature IDs: 18544
Quest ID: 10283 - Creature IDs: 20155
Quest ID: 10284 - Creature IDs: 20156
Quest ID: 10299 - Creature IDs: 20209
Quest ID: 10321 - Creature IDs: 20417
Quest ID: 10322 - Creature IDs: 20418
Quest ID: 10323 - Creature IDs: 20440
Quest ID: 10329 - Creature IDs: 20209
Quest ID: 10330 - Creature IDs: 20417
Quest ID: 10338 - Creature IDs: 20418
Quest ID: 10351 - Creature IDs: 19305
Quest ID: 10365 - Creature IDs: 20440
Quest ID: 10369 - Creature IDs: 20680
Quest ID: 10411 - Creature IDs: 20806 20805
Quest ID: 10482 - Creature IDs: 21161
Quest ID: 10512 - Creature IDs: 21241
Quest ID: 10531 - Creature IDs: 15005 15004 15002 15003
Quest ID: 10544 - Creature IDs: 21446 21452
Quest ID: 10545 - Creature IDs: 21241
Quest ID: 10556 - Creature IDs: 21511
Quest ID: 10563 - Creature IDs: 21502
Quest ID: 10584 - Creature IDs: 21731
Quest ID: 10585 - Creature IDs: 21735
Quest ID: 10588 - Creature IDs: 21181
Quest ID: 10596 - Creature IDs: 21502
Quest ID: 10602 - Creature IDs: 21735
Quest ID: 10612 - Creature IDs: 21959
Quest ID: 10613 - Creature IDs: 21959
Quest ID: 10639 - Creature IDs: 21877
Quest ID: 10641 - Creature IDs: 21925
Quest ID: 10645 - Creature IDs: 21877
Quest ID: 10657 - Creature IDs: 21910
Quest ID: 10669 - Creature IDs: 21894
Quest ID: 10674 - Creature IDs: 21929
Quest ID: 10702 - Creature IDs: 21978
Quest ID: 10703 - Creature IDs: 21978
Quest ID: 10714 - Creature IDs: 22383
Quest ID: 10723 - Creature IDs: 22434
Quest ID: 10724 - Creature IDs: 22435
Quest ID: 10742 - Creature IDs: 20555
Quest ID: 10769 - Creature IDs: 22051
Quest ID: 10776 - Creature IDs: 22051
Quest ID: 10802 - Creature IDs: 22434
Quest ID: 10804 - Creature IDs: 22131
Quest ID: 10806 - Creature IDs: 20555
Quest ID: 10821 - Creature IDs: 19963
Quest ID: 10830 - Creature IDs: 22226
Quest ID: 10836 - Creature IDs: 22197
Quest ID: 10842 - Creature IDs: 21636
Quest ID: 10854 - Creature IDs: 22316
Quest ID: 10859 - Creature IDs: 21929
Quest ID: 10864 - Creature IDs: 22334
Quest ID: 10873 - Creature IDs: 22459
Quest ID: 10879 - Creature IDs: 22375 22376
Quest ID: 10882 - Creature IDs: 20912
Quest ID: 10896 - Creature IDs: 22419
Quest ID: 10909 - Creature IDs: 22454
Quest ID: 10911 - Creature IDs: 22504 22503
Quest ID: 10915 - Creature IDs: 22452
Quest ID: 10923 - Creature IDs: 22441
Quest ID: 10925 - Creature IDs: 22441
Quest ID: 10566 - Creature IDs: 21713 21714 21715 21716
Quest ID: 11001 - Creature IDs: 23035
Quest ID: 9382 - Creature IDs: 16970
Quest ID: 11096 - Creature IDs: 23450
Quest ID: 11120 - Creature IDs: 23531 23529 23530
Quest ID: 11409 - Creature IDs: 24263 24264 24265
Quest ID: 11318 - Creature IDs: 24263 24264 24265
Quest ID: 11152 - Creature IDs: 23768
Quest ID: 11159 - Creature IDs: 23786
Quest ID: 11162 - Creature IDs: 23789
Quest ID: 11169 - Creature IDs: 23811
Quest ID: 11180 - Creature IDs: 23861
Quest ID: 11183 - Creature IDs: 23864
Quest ID: 11209 - Creature IDs: 23928
Quest ID: 11383 - Creature IDs: 17839
Quest ID: 11010 - Creature IDs: 23118
Quest ID: 11020 - Creature IDs: 23209
Quest ID: 11023 - Creature IDs: 23118
Quest ID: 11026 - Creature IDs: 23327
Quest ID: 11051 - Creature IDs: 23327
Quest ID: 11065 - Creature IDs: 23343
Quest ID: 11066 - Creature IDs: 23343
Quest ID: 11073 - Creature IDs: 21838
Quest ID: 11086 - Creature IDs: 23393
Quest ID: 11093 - Creature IDs: 23438
Quest ID: 11102 - Creature IDs: 23118
Quest ID: 11118 - Creature IDs: 23528 23507 23527
Quest ID: 11122 - Creature IDs: 24337
Quest ID: 11293 - Creature IDs: 24202 24203 24204 24205
Quest ID: 11294 - Creature IDs: 24202 24203 24204 24205
Quest ID: 11407 - Creature IDs: 24202 24203 24204 24205
Quest ID: 11408 - Creature IDs: 24202 24203 24204 24205
Quest ID: 11412 - Creature IDs: 24337
Quest ID: 11490 - Creature IDs: 25042
Quest ID: 11502 - Creature IDs: 24867
Quest ID: 11503 - Creature IDs: 24867
Quest ID: 11515 - Creature IDs: 24955
Quest ID: 11537 - Creature IDs: 25065 25068
Quest ID: 11538 - Creature IDs: 25065 25068
Quest ID: 11541 - Creature IDs: 25086
Quest ID: 11885 - Creature IDs: 23161 23165 23163 23162
Quest ID: 11917 - Creature IDs: 26116
Quest ID: 11947 - Creature IDs: 26178
Quest ID: 11948 - Creature IDs: 26204
Quest ID: 11952 - Creature IDs: 26214
Quest ID: 11953 - Creature IDs: 26215
Quest ID: 11954 - Creature IDs: 26216
Quest ID: 11260 - Creature IDs: 23671
Quest ID: 11270 - Creature IDs: 24008
Quest ID: 11280 - Creature IDs: 24170
Quest ID: 11281 - Creature IDs: 24173
Quest ID: 11282 - Creature IDs: 24166 24165 24167
Quest ID: 11283 - Creature IDs: 24231
Quest ID: 11296 - Creature IDs: 24211
Quest ID: 11307 - Creature IDs: 24281
Quest ID: 11310 - Creature IDs: 24274
Quest ID: 11317 - Creature IDs: 27959
Quest ID: 11322 - Creature IDs: 27959
Quest ID: 11355 - Creature IDs: 27802
Quest ID: 11358 - Creature IDs: 24381
Quest ID: 11365 - Creature IDs: 27802
Quest ID: 11366 - Creature IDs: 24381
Quest ID: 11402 - Creature IDs: 5868
Quest ID: 11410 - Creature IDs: 24500
Quest ID: 11429 - Creature IDs: 24641
Quest ID: 11587 - Creature IDs: 25318
Quest ID: 11590 - Creature IDs: 25474
Quest ID: 11598 - Creature IDs: 25382
Quest ID: 11611 - Creature IDs: 25270
Quest ID: 11631 - Creature IDs: 25456
Quest ID: 11652 - Creature IDs: 25495 27109
Quest ID: 11653 - Creature IDs: 25505
Quest ID: 11661 - Creature IDs: 32576
Quest ID: 11670 - Creature IDs: 25581
Quest ID: 11690 - Creature IDs: 25698
Quest ID: 11706 - Creature IDs: 25629 25742
Quest ID: 11712 - Creature IDs: 25773
Quest ID: 11723 - Creature IDs: 25629 25794
Quest ID: 11730 - Creature IDs: 25815
Quest ID: 11788 - Creature IDs: 25830 25831 25832 25833
Quest ID: 11798 - Creature IDs: 27995
Quest ID: 11865 - Creature IDs: 25835
Quest ID: 11881 - Creature IDs: 25969
Quest ID: 11893 - Creature IDs: 25987
Quest ID: 11895 - Creature IDs: 26045
Quest ID: 11896 - Creature IDs: 26082
Quest ID: 11899 - Creature IDs: 26096
Quest ID: 11905 - Creature IDs: 26105
Quest ID: 11907 - Creature IDs: 25830 25831 25832 25833
Quest ID: 11909 - Creature IDs: 27995
Quest ID: 11938 - Creature IDs: 26195
Quest ID: 11959 - Creature IDs: 26227
Quest ID: 11969 - Creature IDs: 26237
Quest ID: 11984 - Creature IDs: 26444
Quest ID: 11989 - Creature IDs: 27921
Quest ID: 12015 - Creature IDs: 26490
Quest ID: 12017 - Creature IDs: 26510
Quest ID: 12019 - Creature IDs: 28189
Quest ID: 12023 - Creature IDs: 26518
Quest ID: 12029 - Creature IDs: 26612
Quest ID: 12035 - Creature IDs: 25993
Quest ID: 12038 - Creature IDs: 26612
Quest ID: 12065 - Creature IDs: 26773
Quest ID: 12066 - Creature IDs: 26773
Quest ID: 12083 - Creature IDs: 26831
Quest ID: 12084 - Creature IDs: 26831
Quest ID: 12093 - Creature IDs: 26920 26921 26922 26923
Quest ID: 12099 - Creature IDs: 26783
Quest ID: 12100 - Creature IDs: 26874
Quest ID: 12111 - Creature IDs: 26895 26882
Quest ID: 12121 - Creature IDs: 26902
Quest ID: 12138 - Creature IDs: 27017
Quest ID: 12152 - Creature IDs: 27199
Quest ID: 12159 - Creature IDs: 27561
Quest ID: 12166 - Creature IDs: 27111 27112
Quest ID: 12170 - Creature IDs: 27121
Quest ID: 12185 - Creature IDs: 27212
Quest ID: 12198 - Creature IDs: 27017
Quest ID: 12203 - Creature IDs: 27212
Quest ID: 12206 - Creature IDs: 27253
Quest ID: 12211 - Creature IDs: 27280
Quest ID: 12214 - Creature IDs: 27296
Quest ID: 12236 - Creature IDs: 27372
Quest ID: 12237 - Creature IDs: 27341
Quest ID: 12240 - Creature IDs: 27238
Quest ID: 12243 - Creature IDs: 28013
Quest ID: 12244 - Creature IDs: 27396
Quest ID: 12249 - Creature IDs: 27372
Quest ID: 12260 - Creature IDs: 27419
Quest ID: 12261 - Creature IDs: 28820
Quest ID: 12270 - Creature IDs: 27396
Quest ID: 12273 - Creature IDs: 27426 27427 27428 27429
Quest ID: 12274 - Creature IDs: 27445 27444
Quest ID: 12284 - Creature IDs: 27453
Quest ID: 12288 - Creature IDs: 27466
Quest ID: 12289 - Creature IDs: 27453
Quest ID: 12291 - Creature IDs: 27472 27471 27473 27474
Quest ID: 12296 - Creature IDs: 27466
Quest ID: 12308 - Creature IDs: 28019
Quest ID: 12316 - Creature IDs: 28190
Quest ID: 12317 - Creature IDs: 28190
Quest ID: 12323 - Creature IDs: 27568
Quest ID: 12324 - Creature IDs: 27568
Quest ID: 12444 - Creature IDs: 27121
Quest ID: 12453 - Creature IDs: 27786
Quest ID: 12457 - Creature IDs: 27788
Quest ID: 12459 - Creature IDs: 27821 27809 27807
Quest ID: 12476 - Creature IDs: 27875
Quest ID: 12478 - Creature IDs: 27879
Quest ID: 12481 - Creature IDs: 24276 24275
Quest ID: 12484 - Creature IDs: 27929
Quest ID: 12512 - Creature IDs: 28136 28142 28148
Quest ID: 12516 - Creature IDs: 28151
Quest ID: 12541 - Creature IDs: 28248
Quest ID: 12544 - Creature IDs: 28256
Quest ID: 12545 - Creature IDs: 28270
Quest ID: 12555 - Creature IDs: 28289
Quest ID: 12557 - Creature IDs: 28293 28294 28295 28296
Quest ID: 12568 - Creature IDs: 28316
Quest ID: 12575 - Creature IDs: 28105
Quest ID: 12580 - Creature IDs: 28644
Quest ID: 12601 - Creature IDs: 28248
Quest ID: 12602 - Creature IDs: 28248
Quest ID: 12606 - Creature IDs: 28415
Quest ID: 12620 - Creature IDs: 28595
Quest ID: 12621 - Creature IDs: 28482
Quest ID: 12632 - Creature IDs: 28526
Quest ID: 12652 - Creature IDs: 28591
Quest ID: 12659 - Creature IDs: 28622
Quest ID: 12661 - Creature IDs: 28738
Quest ID: 12663 - Creature IDs: 28663
Quest ID: 12664 - Creature IDs: 28663
Quest ID: 12668 - Creature IDs: 28713
Quest ID: 12673 - Creature IDs: 28740
Quest ID: 12674 - Creature IDs: 28753 28755 28757
Quest ID: 12676 - Creature IDs: 28777 28786 28928
Quest ID: 12677 - Creature IDs: 28762
Quest ID: 12678 - Creature IDs: 28763 28764
Quest ID: 12680 - Creature IDs: 28767
Quest ID: 12685 - Creature IDs: 28795
Quest ID: 12690 - Creature IDs: 29099 28873
Quest ID: 12698 - Creature IDs: 28845
Quest ID: 12701 - Creature IDs: 28849
Quest ID: 12707 - Creature IDs: 28876
Quest ID: 12710 - Creature IDs: 28929
Quest ID: 12722 - Creature IDs: 28984 28986
Quest ID: 12726 - Creature IDs: 29008 29009
Quest ID: 12730 - Creature IDs: 29028
Quest ID: 12733 - Creature IDs: 29025
Quest ID: 12735 - Creature IDs: 29033 29018 29034
Quest ID: 12737 - Creature IDs: 29055
Quest ID: 12740 - Creature IDs: 29060
Quest ID: 12801 - Creature IDs: 29245
Quest ID: 12805 - Creature IDs: 29303
Quest ID: 12810 - Creature IDs: 29391
Quest ID: 12813 - Creature IDs: 29398
Quest ID: 12814 - Creature IDs: 29406
Quest ID: 12851 - Creature IDs: 29595 29597
Quest ID: 12852 - Creature IDs: 29627
Quest ID: 12856 - Creature IDs: 29734 29709
Quest ID: 12865 - Creature IDs: 29816
Quest ID: 12886 - Creature IDs: 29800
Quest ID: 12887 - Creature IDs: 29803
Quest ID: 12892 - Creature IDs: 29803
Quest ID: 12893 - Creature IDs: 29845 29846 29847
Quest ID: 12896 - Creature IDs: 29851
Quest ID: 12897 - Creature IDs: 29851
Quest ID: 12904 - Creature IDs: 29882
Quest ID: 12906 - Creature IDs: 29886
Quest ID: 12911 - Creature IDs: 29902
Quest ID: 12920 - Creature IDs: 29579
Quest ID: 12924 - Creature IDs: 30126
Quest ID: 12939 - Creature IDs: 30038
Quest ID: 12967 - Creature IDs: 30125
Quest ID: 12970 - Creature IDs: 30467
Quest ID: 12977 - Creature IDs: 30138 30139
Quest ID: 12987 - Creature IDs: 30210
Quest ID: 12995 - Creature IDs: 30220
Quest ID: 12996 - Creature IDs: 30221
Quest ID: 12998 - Creature IDs: 30299
Quest ID: 13003 - Creature IDs: 30415
Quest ID: 13005 - Creature IDs: 30296 30297
Quest ID: 13008 - Creature IDs: 30274
Quest ID: 13010 - Creature IDs: 30327
Quest ID: 13038 - Creature IDs: 30444
Quest ID: 13039 - Creature IDs: 30402
Quest ID: 13043 - Creature IDs: 30404
Quest ID: 13046 - Creature IDs: 30421
Quest ID: 13051 - Creature IDs: 30461
Quest ID: 13064 - Creature IDs: 30514
Quest ID: 13086 - Creature IDs: 30670 30575
Quest ID: 13091 - Creature IDs: 30644
Quest ID: 13110 - Creature IDs: 30546
Quest ID: 13118 - Creature IDs: 30543 30541 30202
Quest ID: 13121 - Creature IDs: 30750
Quest ID: 13125 - Creature IDs: 30829 30830 30831
Quest ID: 13127 - Creature IDs: 27655
Quest ID: 13128 - Creature IDs: 27656
Quest ID: 13133 - Creature IDs: 30880
Quest ID: 13137 - Creature IDs: 30924
Quest ID: 13142 - Creature IDs: 31016
Quest ID: 13147 - Creature IDs: 31481
Quest ID: 13151 - Creature IDs: 31006
Quest ID: 13159 - Creature IDs: 31134
Quest ID: 13169 - Creature IDs: 31119
Quest ID: 13177 - Creature IDs: 31086
Quest ID: 13178 - Creature IDs: 31086
Quest ID: 13179 - Creature IDs: 31086
Quest ID: 13180 - Creature IDs: 31086
Quest ID: 13185 - Creature IDs: 31093
Quest ID: 13186 - Creature IDs: 31093
Quest ID: 13190 - Creature IDs: 31105
Quest ID: 13220 - Creature IDs: 31235
Quest ID: 13222 - Creature IDs: 31284
Quest ID: 13223 - Creature IDs: 31284
Quest ID: 13228 - Creature IDs: 31272
Quest ID: 13231 - Creature IDs: 31312
Quest ID: 13232 - Creature IDs: 31312
Quest ID: 13235 - Creature IDs: 30698
Quest ID: 13236 - Creature IDs: 31329
Quest ID: 13239 - Creature IDs: 31364
Quest ID: 13243 - Creature IDs: 27744
Quest ID: 13259 - Creature IDs: 31413
Quest ID: 13261 - Creature IDs: 31364
Quest ID: 13264 - Creature IDs: 31743 32168 32167
Quest ID: 13276 - Creature IDs: 31743 32168 32167
Quest ID: 13279 - Creature IDs: 31767
Quest ID: 13280 - Creature IDs: 31766
Quest ID: 13281 - Creature IDs: 31767
Quest ID: 13283 - Creature IDs: 31766
Quest ID: 13285 - Creature IDs: 31810
Quest ID: 13288 - Creature IDs: 31743 32168 32167
Quest ID: 13289 - Creature IDs: 31743 32168 32167
Quest ID: 13291 - Creature IDs: 31364
Quest ID: 13292 - Creature IDs: 31364
Quest ID: 13295 - Creature IDs: 31767
Quest ID: 13297 - Creature IDs: 31767
Quest ID: 13300 - Creature IDs: 31866
Quest ID: 13302 - Creature IDs: 31866
Quest ID: 13312 - Creature IDs: 32162
Quest ID: 13315 - Creature IDs: 32195 32196 32197 32199
Quest ID: 13318 - Creature IDs: 32229
Quest ID: 13321 - Creature IDs: 32266
Quest ID: 13322 - Creature IDs: 32266
Quest ID: 13323 - Creature IDs: 32229
Quest ID: 13329 - Creature IDs: 32288
Quest ID: 13335 - Creature IDs: 32288
Quest ID: 13337 - Creature IDs: 32162
Quest ID: 13342 - Creature IDs: 32314
Quest ID: 13344 - Creature IDs: 32314
Quest ID: 13346 - Creature IDs: 32300
Quest ID: 13350 - Creature IDs: 32300
Quest ID: 13351 - Creature IDs: 32195 32196 32197 32199
Quest ID: 13352 - Creature IDs: 32229
Quest ID: 13353 - Creature IDs: 32229
Quest ID: 13356 - Creature IDs: 32266
Quest ID: 13357 - Creature IDs: 32266
Quest ID: 13358 - Creature IDs: 32314
Quest ID: 13361 - Creature IDs: 32797
Quest ID: 13364 - Creature IDs: 32648
Quest ID: 13365 - Creature IDs: 32314
Quest ID: 13367 - Creature IDs: 32300
Quest ID: 13368 - Creature IDs: 32300
Quest ID: 13373 - Creature IDs: 32399 32410 32188
Quest ID: 13374 - Creature IDs: 32399 32188 32154 31721
Quest ID: 13376 - Creature IDs: 32399 32188 32154 31721
Quest ID: 13380 - Creature IDs: 32399 32410 32188
Quest ID: 13381 - Creature IDs: 32399 32188 32154 31721
Quest ID: 13382 - Creature IDs: 32399 32188 32154 31721
Quest ID: 13395 - Creature IDs: 31329
Quest ID: 13400 - Creature IDs: 32797
Quest ID: 13403 - Creature IDs: 32648
Quest ID: 13404 - Creature IDs: 32399 32410 32188
Quest ID: 13406 - Creature IDs: 32399 32410 32188
Quest ID: 13422 - Creature IDs: 29886
Quest ID: 13538 - Creature IDs: 35074
Quest ID: 13539 - Creature IDs: 35074
Quest ID: 13549 - Creature IDs: 33005 33006
Quest ID: 13524 - Creature IDs: 28019
Quest ID: 13625 - Creature IDs: 33341 33339 33340
Quest ID: 13663 - Creature IDs: 33519
Quest ID: 13671 - Creature IDs: 33192
Quest ID: 13676 - Creature IDs: 33192
Quest ID: 13677 - Creature IDs: 33341 33339 33340
Quest ID: 13699 - Creature IDs: 33708
Quest ID: 13713 - Creature IDs: 33708
Quest ID: 13723 - Creature IDs: 33708
Quest ID: 13724 - Creature IDs: 33708
Quest ID: 13725 - Creature IDs: 33708
Quest ID: 13726 - Creature IDs: 33708
Quest ID: 13727 - Creature IDs: 33708
Quest ID: 13728 - Creature IDs: 33708
Quest ID: 13729 - Creature IDs: 33708
Quest ID: 13731 - Creature IDs: 33708
Quest ID: 13789 - Creature IDs: 35297
Quest ID: 13791 - Creature IDs: 35297
Quest ID: 13810 - Creature IDs: 35297
Quest ID: 13813 - Creature IDs: 35297
Quest ID: 13850 - Creature IDs: 34157
Quest ID: 13889 - Creature IDs: 34327
Quest ID: 13903 - Creature IDs: 34336
Quest ID: 13904 - Creature IDs: 34338
Quest ID: 13915 - Creature IDs: 34327
Quest ID: 13916 - Creature IDs: 34338
Quest ID: 13917 - Creature IDs: 34336
Quest ID: 13937 - Creature IDs: 36209
Quest ID: 13938 - Creature IDs: 36209
Quest ID: 13997 - Creature IDs: 34436
Quest ID: 14023 - Creature IDs: 34737
Quest ID: 14024 - Creature IDs: 34740
Quest ID: 14028 - Creature IDs: 34741
Quest ID: 14033 - Creature IDs: 34739
Quest ID: 14037 - Creature IDs: 34737
Quest ID: 14040 - Creature IDs: 34740
Quest ID: 14041 - Creature IDs: 34741
Quest ID: 14043 - Creature IDs: 34739
Quest ID: 14064 - Creature IDs: 34806
Quest ID: 14065 - Creature IDs: 34806
Quest ID: 14090 - Creature IDs: 34899
Quest ID: 14101 - Creature IDs: 34980
Quest ID: 14102 - Creature IDs: 34965
Quest ID: 14104 - Creature IDs: 35012
Quest ID: 14107 - Creature IDs: 35055
Quest ID: 14141 - Creature IDs: 34899
Quest ID: 14035 - Creature IDs: 34738
Quest ID: 14047 - Creature IDs: 34738
Quest ID: 14444 - Creature IDs: 36715
Quest ID: 24480 - Creature IDs: 37158
Quest ID: 24535 - Creature IDs: 37601
Quest ID: 24547 - Creature IDs: 38121
Quest ID: 24555 - Creature IDs: 36715
Quest ID: 24561 - Creature IDs: 37158
Quest ID: 24563 - Creature IDs: 37601
Quest ID: 24585 - Creature IDs: 33113
Quest ID: 24589 - Creature IDs: 34780
Quest ID: 24802 - Creature IDs: 37554 38211
Quest ID: 24869 - Creature IDs: 38472
Quest ID: 24870 - Creature IDs: 38490
Quest ID: 24871 - Creature IDs: 38490
Quest ID: 24874 - Creature IDs: 38558
Quest ID: 24875 - Creature IDs: 38485
Quest ID: 24876 - Creature IDs: 38494
Quest ID: 24877 - Creature IDs: 38494
Quest ID: 24879 - Creature IDs: 38558
Quest ID: 24536 - Creature IDs: 37558
Quest ID: 24629 - Creature IDs: 37990
Quest ID: 24635 - Creature IDs: 37990
Quest ID: 24636 - Creature IDs: 37990
Quest ID: 24655 - Creature IDs: 37558
Quest ID: 25199 - Creature IDs: 39355 39356 39362 39361
Quest ID: 25285 - Creature IDs: 39683
Quest ID: 25289 - Creature IDs: 39691 39692 39695
Quest ID: 25293 - Creature IDs: 39757 39758 39760 39763
Quest ID: 25295 - Creature IDs: 39703
Quest ID: 25306 - Creature IDs: 39683
Quest ID: 26034 - Creature IDs: 39863
Quest ID: 25212 - Creature IDs: 39420
Quest ID: 25229 - Creature IDs: 39623 39466
Quest ID: 25393 - Creature IDs: 39901
Quest ID: 25444 - Creature IDs: 40188
Quest ID: 25445 - Creature IDs: 40428
Quest ID: 25446 - Creature IDs: 40218
Quest ID: 25461 - Creature IDs: 40257 40260
Quest ID: 25470 - Creature IDs: 40301
Quest ID: 25480 - Creature IDs: 40387

**Comment by Grz3s** [comment]
Quest ID: 55 - Creature IDs: 24782
Creature IDs: 24782 'Weakened Morbent Fel' ... he spawns after q. item is used on 'Morbent Fel' .. 
Quest works fine...

Quest ID: 409 - Creature IDs: 1946
http://www.wowhead.com/npc=1946/lillith-nefara .. spawned with quest event...
quest works also fine..

It looks like that your list contain creatures ... that are summoned or morphed etc...
It may contain smth useful ( but im sure in most cases ..nothing is missing for DB here)

**Comment by DaMadBoy** [comment]
Where in the database are creatures spawned by quests or morphed. I could use that to narrow down any that are actually missing. 

I know some are missing as I tried to complete a quest in game but the npcs were nowhere to be found.

**Comment by offl** [comment]
>Creatures required in quests that are not currently in the creature table (in game)

Most(or all) of them should be summoned during quest progress(via items, scripts or something else), so they shouldn't be in creature table.
Useless list.

>I know some are missing as I tried to complete a quest in game but the npcs were nowhere to be found.

Read comments to quests on Wowhead.

**Comment by Grz3s** [comment]
Well you need to inclue all DB_scripts_on_*
```code
dbscripts_on_creature_death         Creature entry
dbscripts_on_creature_movement      DB project self defined id
dbscripts_on_event                  Event id. Several sources: spell effect 61, taxi/transport nodes, gameobject_template data
dbscripts_on_go_use                 Gameobject guid
dbscripts_on_go_template_use        Gameobject entry
dbscripts_on_gossip                 DB project self defined id
dbscripts_on_quest_end              DB project self defined id (generally quest entry)
dbscripts_on_quest_start            DB project self defined id (generally quest entry)
dbscripts_on_spell                  Spell id
```
Also some spells itself ...summons creatures..
EventAI also is used to spawn creatures...

So better will be for you... to point where you couldn't finish quest ... so I could look at it..
Closed

**Comment by DaMadBoy** [comment]
The quest I was trying to complete was 25229 requiring creatures 39623. I watched a video on youtube which showed the npcs in ironforge where you take the quest but were nowhere to be found.

**Comment by offl** [comment]
Don't know how this quest should work. You could open up an new issue, related to only this quest.

**Comment by Phatcat** [comment]
It looks like it took some time compiling that list. a shame it isn't really helpful much =/

**Comment by Grz3s** [comment]
yes... lots of stuff here... but after first 2 checked..i realised that... we don't need it :(

**Comment by Grz3s** [comment]
```quote
The quest I was trying to complete was 25229 requiring creatures 39623. I watched a video on youtube which showed the npcs in ironforge where you take the quest but were nowhere to be found. 
```
this quest is already on issues list:
https://github.com/unified-db/Database/issues/157
not easy to fix
