### ISSUE TITLE
Missing game object spawns for quests

### ISSUE THREAD

**Issue by DaMadBoy** [unified-db/Database#247]
I have created a list of missing game object spawns that are required for quests.
Game Objects required in quests that are not currently in the creature table (in game)

Quest ID: 9319 - Game Object IDs: 181346 181347 181348 181349
Quest ID: 9322 - Game Object IDs: 181342 181339 181343 181340
Quest ID: 9323 - Game Object IDs: 181344 181338 181345 181341
Quest ID: 9386 - Game Object IDs: 181346 181347 181348 181349
Quest ID: 9388 - Game Object IDs: 181561 181560 181563 181562
Quest ID: 9389 - Game Object IDs: 181566 181564 181565 181567
Quest ID: 13058 - Game Object IDs: 194123

**Comment by NeatElves** [comment]
Quest ID: 9319, 9322, 9323, 9386, 9388, 9389
The subject of this article was removed from World of Warcraft in patch 2.4.0.
Quest ID: 13058 ->  http://www.wowhead.com/spell=56890

**Comment by Grz3s** [comment]
thank @NeatElves  for checking it...
it saves a lot of work...

**Comment by NeatElves** [comment]
))
```sql
DELETE FROM `creature_involvedrelation` WHERE `quest` in (9319,9322,9323,9386,9388,9389);
DELETE FROM `creature_questrelation` WHERE `quest` in (9319,9322,9323,9386,9388,9389);
```
