### ISSUE TITLE
Wyrm from beyond wrong model

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#248]
http://www.wowhead.com/npc=21796/wyrm-from-beyond#abilities

the issue is that when you spawn this mob, he has "no model". Anyone got correct data that would correspond to the picture on wowhead?

**Comment by Grz3s** [comment]
Npc is controled by spells and in right time is morphed to model from another npc.
34876 - Wyrm from Beyond Transform

Fixed
https://github.com/cmangos/wotlk-db/commit/c96d89daae0de5b0fcd6e48f7b491e020d15e2c0
