### ISSUE TITLE
Bonus armor items

### ISSUE THREAD

**Issue by killerwife** [unified-db/Database#250]
Recently we discovered items that have bonus armor account for bonus armor twice, because Armor column contains not only BASE_ARMOR but also BONUS_ARMOR. Fix is following:

UPDATE item_template SET armor= armor-ArmorDamageModifier WHERE ArmorDamageModifier>0 AND armor >= ArmorDamageModifier;
(the where are failsaves)

I would advise you to check your db. Such item includes Blackskull shield. @Grz3s

**Comment by killerwife** [comment]
Wrong.

**Comment by Grz3s** [comment]
?
