### ISSUE TITLE
Quality control against Let's Play WoW Draenei Shaman 1 - 80 [video 2/142]

### ISSUE THREAD

**Issue by Phatcat** [unified-db/Database#252]
https://www.youtube.com/watch?v=BGk9x8_H6II&list=PL28173C4849CA7E04&index=2
(run it at 0.25 speed , recorded pre 3.3.0 so patch differences will occur)

0:13
Shouldn't she be linked to any of the mobs in the area? shouldn't the neutral mobs patroling by her react either to their bretheren in combat?
The red flowing crystal object thing should disappear/become invisible when she stops channeling at it, on cmangos it keeps being there even when she's dead.
Looks like she has a much higher preference for melee; on cmangos all she does is throw fire balls basically.. CreatureEventAI is most likely at large here (core)

1:10
Her respawn on cmangos is too slow; I had to wait for her respawn, and I run the video at 0.25 speed, and I have it paused more time than it's playing, so..

1:43
Vindicator Aldar should greet you with a /talk animation when you interact with him, on cmangos he doesnt.
He should also do /talk animation when you press complete quest on 'Blood Elf Spy'

1:51
Technician Zhanaa should have the new quest for you right away once you've turned in 'the Emitter'

3:00
When you accept the quest from Diktynna she is supposed to do a /shrug type of animation and not the /point she is currently during

3:07
(- 4:10 ish)
The chance for an angry murloc to appear seems too high on cmangos;
(I only caught 3 of my own fish, and the murlocs didn't even drop them 100% for me..) - i could just be incredibly unlucky / video be lucky
Angry Murlocs should NOT try to run away in fear (3:15 good example); of all the 5 murlocs we see being fought in the video not a single one tries to flee

4:37
When you complete 'Find Acteon' it should not lead in to his other quest but rather quit his gossip menu as we see in the video.

4:56
Like with basically all other shops, cmangos orders items wrongfully. (most likely a core issue, but I'll still keep noting them down just in case)

6:51
Root Trapper Vine has a slightly too high drop chance on cmangos it would seem, almost 100%, while it doesn't even seem to much more than 50% in the video, (again, differences could be down to luck...)
He gets his 3rd here, I got my 7th (I've tried to kill roughly the same mobs, if I have killed more than in the video it's either 1 or 2 more, tops)

8:20
Theese mooses are overpowered on cmangos; they seem to attack a bit too fast, not directly by attack speed, though (read below)
It seems like they are somtimes able to do 3 melee attacks right after each other (they will do a melee attack, then go straight for the knock-down effect and then straight for melee attack again, they don't seem to be able to do that on retail)

Unrelated:

4:45
So, this heirloom kind of gear, we don't have that on cmangos do we?

**Comment by Phatcat** [comment]
pro copy-pasting clean-up skills ^

**Comment by Grz3s** [comment]
```quote
1:43
 Vindicator Aldar should greet you with a /talk animation when you interact with him, on cmangos he doesnt.
 He should also do /talk animation when you press complete quest on 'Blood Elf Spy'
```
this one is invaild:  He does all req. emotes.. just checked it ...

**Comment by Phatcat** [comment]
Either I was stoned out of my mind doing this or something is messed in my db because that is just too many misreports there, if you can confirm there is no issue on cmangos you can just go ahead and ignore those.

**Comment by Phatcat** [comment]
I'll move the core related stuff of course.

**Comment by Phatcat** [comment]
But yeah, gonna write off the chance with murlucs as luck based and leave that be as it didn't feel too punishing on cmangos, just maybe not right, but one video is just not enough to base it off on, but they however still shouldn't flee =)
