### ISSUE TITLE
Wailing Caverns - Endevent with Naralex don't work

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#31]
the endevent to with Naralex don't work.
i killed every bossmod in the dungeon than you can talk to NPC 26878 - Disciples of Naralex
then you go with him to naralex 
when he will wake im up the event should  start and more mob waves should spawn
the 1. mobwave spawn but they don't come to naralex when i killd all the 2. mobwave spawn, here the same they don't come  after i killt all  than spawn no 3. mobwave so the bossmob don't spawn to kill him to finish the event and you don't complete the dungeon

**Comment by Grz3s** [comment]
sd2 - core bug
canot be done by db
https://github.com/scriptdev2/scriptdev2/issues/137
