### ISSUE TITLE
5098 - All Along the Watchtowers

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#32]
1 from the 4 towers you can mark with the torch, the working one is the 1. (west tower)
the other towers you can use the torch but the tower will don't show as marked in the quest,
so you can't finisch the quest

**Comment by Grz3s** [comment]
ok.. tested both ver . off this quest:
5098 horde
5097 Alliance
Both works perfect
pls read description of quest : (...) You'll need to be in the doorway of each tower to plant the beacon(...)
This vid is a good example:
https://www.youtube.com/watch?v=an7TcjJt-ac
and this pic: will show u where exact place item:
http://www.wowhead.com/quest=5098/all-along-the-watchtowers#screenshots:id=137261
