### ISSUE TITLE
12946 - Hypercapacitor Gizmo

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#35]
when i open the cage, the panther don't come out of the cage and don't attack me, i can't attack the panther too.
the Panter is not attackable

wenn i killed the panther with GM command  .die     i can loot the questitem.

**Comment by xfurry** [comment]
Maybe the GO is missing the script that will make the panther attackable and hostile.
Please provide the details so we can fix it. (npc and go ids).

**Comment by xfurry** [comment]
Here is the fix:
```sql
DELETE FROM dbscripts_on_go_template_use WHERE id=176195;
INSERT INTO dbscripts_on_go_template_use (id,delay,command,datalong,datalong2,buddy_entry,search_radius,data_flags,comments) VALUES
(176195, 0, 26, 0, 0, 10992, 20, 3, 'Enraged Panther - attack');
```

I'll leave it to @Grz3s to commit

**Comment by Grz3s** [comment]
https://www.youtube.com/watch?v=2QDb1j2EfQ8
Your fix works fine..
Thank you.
