### ISSUE TITLE
SQL Error in 122_ClassicDB_Backport#3 part1.sql

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#36]
In the SQL FIle 122_ClassicDB_Backport#3 part1.sql 
Error Code:1062 Dublicate entry "52150" for Key "PRIMARY"

**Comment by Dainara82** [comment]
yes i have the same in
122_ClassicDB_Backport#3 part1.sql
ERROR 1062 (23000) at line 62: Dublicate entry '52150' for key 'PRIMARY'
