### ISSUE TITLE
Leotheras the Blind and Spellbinder Greyheart cosmetic.

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#37]
Spellbinder Gray Heart of the tribe must not only channeling spell (completed in ACID), but also to take in the Target Leotheras. Leotheras himself must have STAND STATE KNEEL.
SCRIPT_COMMAND_SET_FACING and SCRIPT_COMMAND_STAND_STATE
can help me with this. I have long understood how the team should work SET_FACING.
``` SQL
DELETE FROM `creature` WHERE `id`=21806;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`DeathState`,`MovementType`) VALUES
(71742, 21806, 548, 1, 1, 0, 0, 383.127, -435.241, 29.5273, 3.34481, 604800, 0, 0, 80416, 80775, 0, 0),
(701001, 21806, 548, 1, 1, 0, 0, 373.747, -444.703, 29.5225, 0.981184, 604800, 0, 0, 80416, 80775, 0, 0),
(701000, 21806, 548, 1, 1, 0, 0, 372.455, -434.156, 29.5231, 5.28776, 604800, 0, 0, 80416, 80775, 0, 0);

UPDATE `creature` SET `MovementType` = 2 WHERE `id` = 21215;

DELETE FROM `creature_movement_template` WHERE `entry` = 21215;
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `orientation`) VALUES
('21215','1','376.48','-438.652','29.5257','60000','2121501','1.45931');

-- Script id: 2121501
DELETE FROM dbscripts_on_creature_movement WHERE id=2121501;
INSERT INTO `dbscripts_on_creature_movement` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES
('2121501','0','36','0','0','21806','701001','24','0','0','0','0','0','0','0','0','Spellbinder Greyheart - Set Facing to Leotheras.'),
('2121501','0','36','0','0','21806','71742','24','0','0','0','0','0','0','0','0','Spellbinder Greyheart - Set Facing to Leotheras.'),
('2121501','0','36','0','0','21806','701000','24','0','0','0','0','0','0','0','0','Spellbinder Greyheart - Set Facing to Leotheras.'),
('2121501','0','28','8','0','0','0','0','0','0','0','0','0','0','0','0','Leotheras the Blind - Set Stand State on Kneel.');
```

**Comment by Grz3s** [comment]
why would you..use "SET_FACING" here ? .. if they all are facing in correct way (they/he are static objects,  so correct orientation will be enough)

**Comment by Ulduar** [comment]
Because by the method Set Target Guid (pTarget-> GetObjectGuid) they must take it to the Target.

**Comment by xfurry** [comment]
I think that the orientation should do just fine.
The ```SetFacingObject(pObject)``` function does the same thing, and calculates the orientation inside the function.

Just use the creature_movement orientation column and it will work just fine.

**Comment by Ulduar** [comment]
``` BLACK
Spellbinder should Set Target Guid on Leotheras the Blind.
```
So it is understandable?

**Comment by xfurry** [comment]
I think you didn't understand what I tried to say.

I told you to use this:
INSERT INTO creature_movement (id, point, position_x, position_y, position_z, **orientation**) VALUES

You will get the same result and you don't need to add a new command that does exactly the same thing.
You can see that I used the same logic here: https://github.com/unified-db/Database/commit/b0d1f2fe1899d6a8b040272dc60e340a7db266aa

**Comment by Ulduar** [comment]
I need to set the focus on the Spellbinder Leotheras. And about the orientation will say this. Leotheras movement coordinate = his spawn coordinate.
SCRIPT_COMMAND_SET_FACING needed here, anyway.
This is a good team because of it is not necessary to calculate the orientation for Spellbinder - she will do everything and they do not just set facing to object, but also by the method Set Target Guid will set the focus to it - like me and need, as well as on the official server.

**Comment by xfurry** [comment]
Ok, this sounds reasonable.
If nobody has any objection then I think we can add this new command.

**Comment by Ulduar** [comment]
@Schmoozerd  has long been said that a new team! More @Virusav long requested and it was done (for what that of quest)
i talking about commit https://github.com/cmangos/mangos-wotlk/commit/5060f4a3c243d8f218f186a7d854b211eb4fed34

**Comment by Grz3s** [comment]
so be it....
*Remind to mysefl* 
ill reopen this issue ...when will find time to work on it...

**Comment by Grz3s** [comment]
to @Ulduar: your "SET_FACING"" its done by: 
AttributesEx1: 0x10004404 (SPELL_ATTR_EX_CHANNELED_1, SPELL_ATTR_EX_NO_THREAT, SPELL_ATTR_EX_CHANNEL_TRACKING_TARGET, SPELL_ATTR_EX_HIDDEN_AURA)
