### ISSUE TITLE
Shadowmoon Slayer <Servant of Illidan>

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#38]
http://www.wowhead.com/npc=22082/shadowmoon-slayer
Have to fight with each other when they are attacked by someone else, restores health and attacks the invoker. With 50 percent of health should stop the fight with a friend.
Analogic issue https://github.com/cmangos/issues/issues/561

**Comment by Grz3s** [comment]
This is how it works on UDB..
https://www.youtube.com/watch?v=T5k8hnHq5Ag 
dont u think its fine enough?

**Comment by Ulduar** [comment]
Out there some emotions.

**Comment by Grz3s** [comment]
ok then.....
so:
we have 2 shadowmoon slayers:
---------------------------------------------------------------
first:
```quote
GUID: Full: 0xF130564200001E2B Type: Unit Entry: 22082 Low: 7723
Slot: 0
Spell ID: 45091
Flags: EffectIndex0, EffectIndex1, NotCaster, Positive, Duration, Unk100 (315)
Level: 68
Charges: 1
Max Duration: 30000
Duration: 6710
```
and second:
```quote
ServerToClient: SMSG_AURA_UPDATE_ALL (0x7A25) 
Number: 14422
GUID: Full: 0xF130564200001E2C Type: Unit Entry: 22082 Low: 7724
Slot: 0
Spell ID: 45092
Flags: Unk100 (256)
Level: 68
Charges: 1
Caster GUID: Full: 0xF130564200001E2C Type: Unit Entry: 22082 Low: 7724
```
and problem we have here:
-- 45092 -- hidden server side spell...
-------------------------------------------------------------------------
what i know about this spell???
```quote
ServerToClient: SMSG_AURA_UPDATE_ALL (0x7A25) 
Number: 59906
GUID: Full: 0xF1305642002CFE16 Type: Unit Entry: 22082 Low: 2948630
Slot: 0
Spell ID: 45092
Flags: Unk100 (256)
Level: 68
Charges: 1
Caster GUID: Full: 0xF1305642002CFE16 Type: Unit Entry: 22082 Low: 2948630

ServerToClient: SMSG_UPDATE_OBJECT (0x6264)
Number: 59927
Map: 530
Count: 5
[0] UpdateType: Values
[0] GUID: Full: 0xF1305642002CFE16 Type: Unit Entry: 22082 Low: 2948630
[0] UNIT_FIELD_TARGET: 20844/2.920867E-41
[0] 21: 4046476866/-8.731783E+29
[0] UNIT_FIELD_FLAGS: 559104/7.834716E-40

HitInfo: HITINFO_AFFECTS_VICTIM, HITINFO_CRITICALHIT, HITINFO_UNK10, HITINFO_UNK11, HITINFO_UNK12, HITINFO_RAGE_GAIN (8396290)
AttackerGUID: Full: 0xF1305642002CFE16 Type: Unit Entry: 22082 Low: 2948630
TargetGUID: Full: 0xF13056420000516C Type: Unit Entry: 22082 Low: 20844
Damage: 524
OverDamage: -1
Count: 1
[0] SchoolMask: 1
[0] Float Damage: 524
[0] Int Damage: 524
VictimState: VICTIMSTATE_NORMAL (1)
Unk Attacker State 0: 1000
Melee Spell ID : 0
Rage Gained: 130
```

Do you wana help here?? then find what this spell do.
Untill that moment... i'll keep what we have .. (visually fine)
GL

**Comment by Ulduar** [comment]
Oh no, it's better to close the issue until better times, spell_template use - a dead case.
Will not work on 3.3.5 (by the way there is no achievement credit spell does not work in this table), well, 4.3.4 - and even more so.

**Comment by xfurry** [comment]
@Ulduar 
I think you didn't understand anything on how this thing works.

If you expect that when you post an issue, some might blizz God will come down from the skies and fix for you, then your are wrong!
This is a community work!

@Grz3s gave you the sniff details that show what is actually happening, so if you want to help, then please do so, otherwise just leave the ticket opened.

**Comment by Ulduar** [comment]
``` QUOTE
If you expect that when you post an issue, some might blizz God will come down from the skies and fix for you, then your are wrong!
```
I would have it and so fixed, but it seems necessary to hack - not functional.
``` QUOTE
@Grz3s gave you the sniff details that show what is actually happening, so if you want to help, then please do so, otherwise just leave the ticket opened.
```
Is There to me only hack can help.
