### ISSUE TITLE
Event missing/Defias Tower Patroller

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#4]
Defias Tower Patroller - http://www.wowhead.com/npc=7052/defias-tower-patroller#comments
Two of them actually meat in one place and start's having this conversation:

J: Hey, Raven...
(Other patroller comes running to stand in front of the speaker)
R: Yea?
J: Can we take a break? My feet are killing me and those ... those things down there are creeping me out.
R: Klaven doesn't pay me enough to deal with zombies, drones, or whatever he calls 'em. I don't know Jill. If Klaven comes down while we're slacking, we might end up as one of those things!
J: Sigh You're probably right, Raven. I'm going back on patrol...

**Comment by cala** [comment]
Sorry, I did not see that issue before. Unfortunately, we don't have more info than what was provided by Tafuna. :(

**Comment by Rushor** [comment]
at least the correct texts:

(3126, 0, 'Hey, Raven...', 'Hey, Raven...', 0, 0, 0, 0, 0, 0, 0, 0, 1, 18019), -- 3126
(3127, 0, 'Yea?', 'Yea?', 0, 0, 0, 0, 0, 0, 0, 0, 1, 18019), -- 3127
(3128, 0, 'Can we take a break? My feet are killing me and those ... those things down there are creeping me out.', 'Can we take a break? My feet are killing me and those ... those things down there are creeping me out.', 0, 0, 0, 0, 0, 0, 0, 0, 1, 18019), -- 3128
(3129, 0, 'I dunno, Jill. If Klaven comes down while we''re slacking, we may end up as one of those things!', 'I dunno, Jill. If Klaven comes down while we''re slacking, we may end up as one of those things!', 0, 0, 0, 0, 0, 0, 0, 0, 1, 18019), -- 3129
(3130, 0, '*Sigh* You''re probably right, Raven. I''m going back on patrol....', '*Sigh* You''re probably right, Raven. I''m going back on patrol....', 0, 0, 0, 0, 0, 0, 0, 0, 1, 18019), -- 3130

from https://raw.githubusercontent.com/TrinityCore/TrinityCore/60e87db489b5bdb766e6e347a6dedd163adf30ec/sql/updates/world/2014_03_30_06_world_broadcast_text.sql

**Comment by Grz3s** [comment]
small update for this:
good news  - I have found good source with waypoints in area around this tower ;)
So I'll be able to fix this....and gues what....
We having a problem: (i'ts never easy) :/
Somehow path for one of the Patrollers is blocked by *magic* invisible force... and he wont go, ike we wanted to :(

this is the place where it happens:
![gpsa](https://cloud.githubusercontent.com/assets/2374069/11915982/a334f4d8-a6b8-11e5-98cc-653df059b8d1.jpg)

And more on avi:
https://youtu.be/cyU83iUROu4

And the problem only happens with "MMAPS = ON"
without them... Patrollers  walk there without any issue... 
Also...
The same situation happens in every simmilar tower:
checked in:
- Tower of Azora - Elvynn forest
- Tower of Ilgalar - Redridge Mountains
 

@cyberium can You pls look at this ... using your... RecastDemo
http://cmangos.net/thread-88-post-41309.html#pid41309
Maybe you will find what is that magic barrier for creatures there...
Im not good enough (this tool wont even start for me - or im missing smth or i have no idea how to run it:) 
Thx
