### ISSUE TITLE
Bloodwarder Protector(The Botanica)

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#41]
I vaguely remember, but when approaching the room Laj, the protector should says:
``` QUOTE
Bloodwarder Protector yells: Get out of here, there are too many of them! Escape while you can!
Bloodwarder Protector yells: Help! Someone help us!
```
and then dies, and all the blood elves in this room also die (their plants to break free and rend)
more information I do not unfortunately.
http://www.wowhead.com/npc=17993/bloodwarder-protector

**Comment by Grz3s** [comment]
this part works perfectly well....
u can see here:
https://github.com/unified-db/Database/commit/3fc6a28ec23c8e94a593712131947f6684893d14
(...)* Instances: 100% redone and completed by @ X-Savior 
-- Tempest Keep: The Arcatraz  
-- Tempest Keep: The Botanica 
-- Tempest Keep: The Mechanar 
...
Closed.

**Comment by Ulduar** [comment]
The problem is not solved. There's no this. In vain you close.

**Comment by Grz3s** [comment]
i see....
Well.. UDB has this part scripted.
look at `dbscripts_on_creature_movement` for creature 17993.
 ONe more think....
This is issue tracker for UDB 3.3.5a ver. - I am happy for all your issues posted here... but Im not going to help you.. with your own "xxx DB"
Belive me ... its not hard to get free udb files and search for stuff u wanted.
...

**Comment by xfurry** [comment]
> I watched all the commits, and ACID and db script. In my issue no lines.

Did you actually test this ingame using UDB 335?
If not, please do it before posting an issue!

**Comment by Ulduar** [comment]
I play on 4.3.4, UDB I just do not fit, UDB 4.3.4 - almost empty.
Please indicate the line in which the script is, and I do at home.

**Comment by xfurry** [comment]
> I play on 4.3.4, UDB I just do not fit, UDB 4.3.4 - almost empty.

Then I must inform you that you are posting on the wrong tracker...
This is for UDB 3.3.5a

If you post some issue here, then you should first test it on 3.3.5a using UDB!
You don't need to search for a specific line in an old script.
This is SQL, so just write your query and interrogate the database, then find out if it's fixed or not.

**Comment by Ulduar** [comment]
Emplty line, In YTDB added everything that you have in your UDB, everything. But this line is empty.
