### ISSUE TITLE
Quest 12727 Bloody Breakout

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#42]
You can't attack the incoming NPC's ( no attackable )

**Comment by Ulduar** [comment]
http://www.wowhead.com/quest=12727/bloody-breakout
quest
http://www.wowhead.com/npc=28912/koltira-deathweaver
http://www.wowhead.com/npc=29011/high-inquisitor-valroth
At least you could provide links. Empty issue.

**Comment by Grz3s** [comment]
hey...
You  need to read .. all comment below... commit..
```quote
@xfurry:
Pls remove it from sd2:
UPDATE creature_template SET ScriptName='' WHERE entry = 28912;

also pls add ACID part:
Here is the acid part: https://github.com/ACID-Scripts/WOTLK/commit/84875f4277da6d903a0c5620867bd81942c7bddf
For SD2 let's wait a few more days until everybody will have a chance to update the DB to this commit.
```

so as u see u need to add sd2 by yourself
simply:

```code
UPDATE creature_template SET ScriptName='' WHERE entry = 28912;
```

**Comment by Tauriella** [comment]
Thank you :+1: works great
