### ISSUE TITLE
NPC-ID 4772 Ultham Ironhorn <Riding Trainer> Dun Morogh

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#44]
Ultham Ironhorn at Amberstill Ranch in Dun Morogh
i playing dwarf hunter
can't learn riding from this NPC
with lvl 20 i get the mail that i can learn riding from this NPC
when i go to the NPC i can talk to him and i have the needed Gold
but i can't learn anything from him

**Comment by Grz3s** [comment]
confirmed...
thank you for report...
i will fix this soon

**Comment by Grz3s** [comment]
also... after 20lvl player will recive quest in mail ... that will direct you to Riding Trainer.
Thanks for report
