### ISSUE TITLE
Shade of Aran

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#46]
Few Bugs on Shade of Aran (16524)

Triggers must be Visble Entrys (17168,17169,17170,17171,17172)

http://prntscr.com/6q94p5

Spells not cast on trigger have records on spell_script_target maybe worng ?

Spells

```
SPELL_SUMMON_WATER_ELEM_1   = 29962,
SPELL_SUMMON_WATER_ELEM_2   = 37051,
SPELL_SUMMON_WATER_ELEM_3   = 37052,
SPELL_SUMMON_WATER_ELEM_4   = 37053,

Records on spell_script_target

SELECT * FROM `spell_script_target` WHERE entry IN (37051,37052,37053,29962);
```

**Comment by xfurry** [comment]
We need to check the sniffs to see which are the npc entries that are required for these spells.
@Grz3s if you don't have Karazhan sniff, please let me know.

**Comment by xfurry** [comment]
All spells have targets in spell_script_target.
```
29962	1	17172	0
37051	1	17175	0
37052	1	17174	0
37053	1	17173	0
```

I'm seriously starting to think that you should reinstall your database and recheck all the issues all over again :wink:

**Comment by xfurry** [comment]
Actually I think there might be a core problem with these spells...

They have 
```
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0
```
So unless the target is specifically provided in the cast function, it won't find it automatically.
I've see similar issues in the Chess event, so it's worth investigating.
