### ISSUE TITLE
Karazhan - Prince Malchezaar

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#47]
NPC (17650) Prince Malchezaar's Axes http://www.wowhead.com/npc=17650/prince-malchezaars-axes
Need UnitFalgs that they can not attack this in moment you can attack and kill the axes that is not right need to change to non select flag.
Same for NPC http://www.wowhead.com/npc=17646/netherspite-infernal

**Comment by Ulduar** [comment]
For 17646
``` SQL
UPDATE `creature_template` SET `UnitFlags` = 33554944 WHERE `entry` = 17646;
```
Not_Selectable, no Cast interact spell able.
About 17650 you could not more precisely?

**Comment by xfurry** [comment]
Are you sure you are using the latest UDB?
In my local DB they both have the right flag (33554432)

**Comment by Tafuna** [comment]
i use last UDB and i have same flag but i can attack the npc so the flag not works or worng and yes i have gm off 10 real players without gm rights tested
