### ISSUE TITLE
Koren, Karazhan

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#49]
Koren, Karazhan (16388)

Can repair at him with friendly Violet Eye rep.
Should have to be honored.

 http://www.wowwiki.com/Koren

**Comment by Grz3s** [comment]
he has NpcFlags = 4227
```quote
-- 4096 Repairer Creatures with this flag can repair items. 
-- 128 Vendor Any creature selling items needs to have this flag. 
-- 2 Quest Giver Any creature giving or taking quests needs to have this flag.
-- 1 Gossip If creature has more gossip options, add this flag to bring up a menu.
```
Have no idea how to block 128 and 4096 -- depends of Reputation, even if ill use conditions for gossip...still vendor will be poss.
not sure if its possible :( ... 
maybe update in core is needed here

**Comment by xfurry** [comment]
I'm not sure if I understand what is the problem.
Can you please detail?

**Comment by Grz3s** [comment]
well... (im not 100% sure)
he shouldnt be vendor or repair items until u'll get honored with Violet Eye reputation.
so: 
rep < honored  -- you should see only welcome gossip (nothing else) -- that gossip is set for him already
rep = or > honored -- you should see his vendor and repair option. (so you can buy stuff and repair items)
I have no idea ... how to block that vendor(128) and Repairer(4096) flag... before u'll get honored with tchem.

**Comment by Rushor** [comment]
was there a special gossipoption to show the repait and vendorstuff. i mean a gossip_menu_option like 'i'd like to buy your shit'? if yes reputationconditions can be used probably

**Comment by xfurry** [comment]
Well... if this is done by a npc flag change, then it's a missing feature and I'm exactly sure how are we going to fix it.
But this can also be done by normal gossip where you can simply apply conditions. See here: https://github.com/cmangos/issues/wiki/gossip_menu_option

**Comment by Saben65** [comment]
Maybe someone can format this to UDB format.

https://github.com/TrinityCore/TrinityCore/issues/16411

**Comment by Grz3s** [comment]
Basically this cannot be fixed in curent Core...
Reason...
Yes we have that gossip option:
```sql
DELETE FROM gossip_menu_option WHERE menu_id = 7435;
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag, action_menu_id, action_poi_id, action_script_id, box_coded, box_money, box_text, condition_id) VALUES
(7435,0,1,'I\'m in need of your skill as a blacksmith, Koren.',3,128,0,0,0,0,0,NULL,1131);
DELETE FROM conditions WHERE condition_entry = 1131;
INSERT INTO conditions (condition_entry, type, value1, value2) VALUES
(1131,5,967,5);  -- this will make it available only with rep honored or higher
```
But issue is with creature_template NPCFLags ...
he has 4227 -- so he is vendor and repairer from begining...
Sniff shows his flag = 3.. (gossip and questgiver) -- if ill set it like that.. ill recive an error:
```quote
 Table gossip_menu_option for menu 7435, id 0 has `npc_option_npcflag` = 128 but creatures using this menu does not have corresponding `NpcFlags`. Option will not accessible in game.
 Table `npc_vendor` has data for creature (Entry: 16388) without vendor flag, ignoring
```
without core dev help we cant fix this.

**Comment by Lumber-Jack-2** [comment]
btw should we move all the issue here to the cmangos tracker? (ref: https://github.com/unified-db/Database/issues/254)
