### ISSUE TITLE
Defender Corpse, The Arcatraz

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#51]
Defender Corpse, The Arcatraz
http://www.wowhead.com/npc=21303/defender-corpse

Currently, the NPC is attackable, but nothing happens.

When a player attacks the corpse or gets near it, it is supposed to cast the spell "Corpse Burst" and spawn 2-3 Protean Spawns.

i saw have a ai script but not working tested on last  udb with last acid ans lat sd2

**Comment by Grz3s** [comment]
fixed by @X-Savior 
https://github.com/ACID-Scripts/WOTLK/commit/e60ed0190598d09a21f931317cb5bcffeb137ce2
