### ISSUE TITLE
The Refectory, Shadow Labyrinth

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#52]
The entire last room with Murmur in it needs to be looked at.
The mobs that are supposed to spawn and run into the middle and get killed by Murmur are already spawned.
The Cabals cast an invisible shadow bolt at Murmur.
Murmur doesn't shoot his spell at any one.

**Comment by xfurry** [comment]
I think I looked at this some time ago.
Problem is that I couldn't find any good source for this and I don't have all the details on how this event starts.
