### ISSUE TITLE
Cabal Ritualist, Shadow Labyrinth

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#53]
NPC Entry 18794

Creature has odd behavior.
They will continue to channel their red beam indefinitely, or until they decide to cast frost nova (which they only will do in melee range), where they will then start attacking you.

Currently, if everyone stays out of melee range they will not attack for a good length of time, even if you are attacking them.

**Comment by Grz3s** [comment]
confired.
creature need .. update for channel spell..

**Comment by Grz3s** [comment]
pls check this:
```sql
-- Cabal Ritualist -- UPDATE needed for channeling spells
Delete from `creature_ai_scripts` where `id` = 1879401;
Insert into `creature_ai_scripts` values
('1879401','18794','11','0','100','6','0','0','0','0','0','0','0','0','0','0','0','0','30','1','3','5','Cabal Ritualist - Random Phase Select on Spawn');
```
also... i see that we missing more things in that room:
-- every group (4 Cabal Ritualists) should be linked
-- boss of that room should be banished... (we should be able to see him)

**Comment by Tafuna** [comment]
Tested the query but not working the Ritualist stop channel but not attack the player.

Fixed other bug on the instance

Report
Boss appears to be scripted correctly and spawns voidwalkers one at a time from all the portals.
However, the voidwalkers themselves move way to fast, they are supposed to be walking speed, if not slower.
Instead they run to the boss.

Fix
UPDATE creature_template SET SpeedWalk = 0.8, SpeedRun = 0.285714 WHERE entry = 19226;

**Comment by Grz3s** [comment]
- script i gave here is for chanelling spell interupt
- as i said before they should be linked ... 
- we not changing _templates (this comes from legit source)
