### ISSUE TITLE
The Mechanar

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#54]
used Cache of the Legion key on Cache of the legion in The Menchanar and nothnig happens and door is still locked.

Object Entry 184465 Loot Entry 20529

SELECT * FROM gameobject_template WHERE entry = 184465;
SELECT * FROM gameobject_loot_template WHERE entry = 20529;

**Comment by Grz3s** [comment]
you need to kill:
Gatewatcher Gyro-Kill  -- drops first part for key
Gatewatcher Iron-Hand -- drops second part for key
also: doors will open after they both are killed.
4.x.x changed a little ... with mechanics there...
Anyway... tested and works fine... -- pls check again.

**Comment by Tafuna** [comment]
you right sorry i try the first one only
