### ISSUE TITLE
Fix Archmage Leryda, Deadwind Pass

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#55]
Issues
I am Friendly with The Violet Eye so Archmage Leryda is supposed to offer 4 quests to choose my path for the Violet Signet rings.
However, she has a yellow question mark above her head and when I right click her, no dialogue box comes up.

Fix
UPDATE creature_template SET NPCFlags = 2 WHERE entry = 18253;

**Comment by Grz3s** [comment]
very nice.
thank you.
