### ISSUE TITLE
Quest 11626 - The Emissary

### ISSUE THREAD

**Issue by Dainara82** [unified-db/Database#59]
"Find Leviroth in the waters below the iceberg floating among the northern edge of Riplash Ruins. Use the Trident of Naz'jan to slay him and return to Karuk to the north of Riplash Strand. "

If i try to slay Leviroh (NPC ID 26452) with the Trident (Item ID 35850), i get the message   "unknown target"

**Comment by Grz3s** [comment]
INVALID..
Pls read 'Description' for this quest:
(...)Drive the trident into his flesh and slay him!(...) <-- how far from him u can be ... to do this?:)
anyway:
spell used in this quest has : Radius (Id 19) 18,00 .. 

Just checked ..and works fine.
