### ISSUE TITLE
few missing things shadowmoon valley

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#6]
missing flying guards not spawnd on udb maked some screenshots from offi
http://www.imgbox.de/users/public/images/eShZLd1vxm.jpg
http://www.imgbox.de/users/public/images/AZsthTepJj.jpg

missing caster event, udb have spawned the npc´s but not casting here a screenshot from offi
http://www.imgbox.de/users/public/images/uEhq9yKhax.jpg

i have not found the right spell id, but i think the trigger is alrady spawnd on udb

**Comment by kvipka** [comment]
Grz3s, https://github.com/healthstone/RustEmu-Core/commit/5eb4b63440cdd602d2680f8e56b52b268eb5c507

video : http://www.youtube.com/watch?v=JcJO6Fg5EbY&feature=youtu.be

**Comment by Grz3s** [comment]
kvipka -- you're master of spells... i only hope that code is ok for core devs;o
thank you very much.
@xfurry can u pls look at this?? .. this could help us in many places....

**Comment by xfurry** [comment]
The commit that @kvipka provided contains many updates. Maybe if he can isolate only the channel spell fix and post it on the forum it would be great.

As I already told you before the issue is known to us, and it happens to all channeled spells cast as triggered. So just avoid casting these spells as triggered or by c_t_a and it should be fine.

**Comment by kvipka** [comment]
xfurry , https://github.com/kvipka/mangos-wotlk/commit/43541cc183516f1ad41439bb71c2c118c8a06b7d

**Comment by kvipka** [comment]
(UPDATED) Special for this case  : https://github.com/kvipka/mangos-wotlk/commit/1ce9d05484e735e75e2ef8ccb1635d915d7521c9

**Comment by Grz3s** [comment]
@kvipka  why your isnt available anymore?

**Comment by kvipka** [comment]
https://github.com/kvipka/mangos-wotlk/commit/c314fed30e54cc975a7797723a1fecd13d9aca9e again

**Comment by Grz3s** [comment]
hi again....
https://www.youtube.com/watch?v=NFcGaL8Udpw <--- effect of "channeling interupt"
so we're almost got this working like it shoud ;)
ofc thx to @kvipka  for his great patch.

**Comment by Grz3s** [comment]
2nd part completed.

**Comment by Grz3s** [comment]
about 1st. 
They are spawned when oposite faction comming to close (with small bug)
Whole event works fine - and is handled by sd2 script.
Bug:
gryphons(bats - horde) - are spawned ... almost on the ground...and thyre missing  ACID scripts...

**Comment by Grz3s** [comment]
both fixed long time ago
