### ISSUE TITLE
spell target problem...

### ISSUE THREAD

**Issue by Grz3s** [unified-db/Database#61]
Having problem with some spells...
Example:
Spell:
ID - 32826 Polymorph Cast Visual (Rank 1)

``` quote
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Effect 1:  NO EFFECT
Effect 2:  NO EFFECT
```

How it should work:
Caster should "do" visual casting effect ... you can see on this picture:
http://www.wowhead.com/npc=18743/elrodan#screenshots:id=458929
and SPELL_EFFECT_DUMMY -- should target another npc....(morph him to random critter)
and that creature is:
http://www.wowhead.com/npc=18744

How it works now:
caster cast this spell (visal works fine) ... but effect will hit himself... so he will morph himself...
i tried ... all flags and whoever will cast spell (source or buddy) same person
 will recive dummy effect..

Also.. 
We cant set spell_script_target WHERE entry = 32826 = error on console.

Any ideas?
BTW:
Got same situation with more spells ... but let's see, if this can be fixed somehow:??

Got some sniffs if they can help here:
http://paste2.org/8nfYtPB5

@xfurry
@kvipka

**Comment by xfurry** [comment]
Well, I think it's pretty obvious that the target should be self. :smile:
```
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
```

What you need to do, is just write a dbscript_on_spell that will search for creature 18744 as buddy and as per the sniff, cast a random of one of the 4 spells: 32820, 32816, 32818 or 32813.

If you have problems in writing the script I just let me know.

**Comment by Grz3s** [comment]
sure...
but explain why i should cast ... any of these spells "32820, 32816, 32818 or 32813" .. if thats done by:
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)... ??
Problem is:
if ill use caster to cast main spell: .... ID - 32826 Polymorph Cast Visual (Rank 1) ... that dummy will hit him... so .. no difference if ill use buddy or no... still caster will morph himself.. and that what i dont want do do...

**Comment by xfurry** [comment]
I think I found the issue:
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/SpellEffects.cpp#L3075

I'm not sure what would be the way to fix this.
I was thinking of something like this:
```sql
DELETE FROM dbscripts_on_spell WHERE id IN (32826);
INSERT INTO dbscripts_on_spell (id,delay,command,datalong,datalong2,buddy_entry,search_radius,data_flags,dataint,dataint2,dataint3,dataint4,comments) VALUES
(32826,0,15,32813,0,18744,20,0,32816,32818,32820,0,'Polymorph Cast Visual (Rank 1) - Cast random polymorph spell');
```
but I think we need more than 4 spells.

**Comment by Grz3s** [comment]
needs core suport.

**Comment by xfurry** [comment]
Ok, core support is not a problem here.
But for this I would need to know if this spell is used somewhere else, as I don't want to break something

We have 2 options:
1. Make it work directly in the core, but giving the target entry.
2. Allowing the dbscript engine to use a random of 6 spells. The 4 dataInt and the 2 dataLong. combined. Not sure how useful would this be.

**Comment by Grz3s** [comment]
i think ... safe is to remove it from SpellEffects ... and let scripts decide "when" and "on who" spell should be casted.
Also having only 4 random morphs wont damage it at all ..

**Comment by xfurry** [comment]
Ok, but I still think we should keep all 6 spells.

**Comment by Ulduar** [comment]
Expand dataint4 on dataintx - where x - field number ,  6, 8, 10 or more.

**Comment by Grz3s** [comment]
fixed in:
https://github.com/cmangos/wotlk-db/commit/1df0d35919a26b518768520776662b1307828e86
