### ISSUE TITLE
Rotlimb Cannibal - attackers event

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#62]
Rotlimb Cannibal - attackers Event don't start
but it worked for some time
I use Mangos 12868, latest ACID, SD2 3128, and UDB with all Updates

**Comment by Grz3s** [comment]
well... 
1. theres timer set for respawn....
2. probably u waiting where Ranger Jaela is -  if yes ..then "yes" u wont see tchem comming :(
this is problem with grid unloading for saving memory ...and unfortunately this how cmangos works...
event will trigger if u'll come closer (a bit) to theirs spawn point....(all depends how far u have visible distance set in config)... 
Theres a option to make it working without unload etc... You need to set flag extra active... so they will be loaded with server start and will be never unloaded (so they will work all the time ...no diff if ure there or not)... 
Let me answer your question before u'll ask :) (why this flag is not set in first place)
Well... its not clear for me ..how big impact on server perform.. this will do .. so im trying use this flag only if is extremly nesesery... but this event in my eyes is not. :)
Maybe ... someone from cmangos devs can say something more about this... 

Anyway.. i just checked it ..and still works like it should :)

**Comment by Tauriella** [comment]
Thank you for your answer Grz3s
But it is strange it worked for some time
I have now the [145] Sunstrider Isle - more Updates in the Databas played 
And now!
it works again :)
