### ISSUE TITLE
Pink Elekk

### ISSUE THREAD

**Issue by Tafuna** [unified-db/Database#64]
pink elekks must be only visible when drunk

DELETE FROM `creature_template_addon` WHERE `entry` IN (21250,23507,23527,23528,23529,23530,23531,27958);
INSERT INTO `creature_template_addon` (`entry`,`auras`) VALUES
(21250,36440), 
(23507,36440),
(23527,36440),
(23528,36440),
(23529,36440),
(23530,36440),
(23531,36440);

**Comment by Grz3s** [comment]
Thanks ;)
