### ISSUE TITLE
DK Zone - Possible to skip/miss out on some quests, leading to missing skill points.

### ISSUE THREAD

**Issue by zimms** [unified-db/Database#75]
This is from when I tested with DK Zone update 10 - I'm not able to test it now due to #72 .

During the phase where you go to meet Keleseth in the crypt ([55] The Crypt of Remembrance), you have to also complete several quests to continue:
[55] The Plaguebringer's Request 
[55] Nowhere To Run And Nowhere To Hide 
[55] Lambs To The Slaughter

After completing these, you are supposed to get:
[55] How To Win Friends And Influence Enemies

However, what I found is that if you turn in "Nowhere To Run And Nowhere To Hide" last, you are also offered the quest after, "Behind Scarlet Lines", which is supposed to be only offered after "How To Win Friends And Influence Enemies".

This seems to be a bug since it's possible to skip "How To Win Friends And Influence Enemies", and permanently lose out on 2 skill credits and an item.

**Comment by Grz3s** [comment]
hi
this was fixed in https://github.com/unified-db/Database/commit/d3e4e92928eb7fc5429306f9597960d3f46fd677
-- after this update u will not be able to take Behind Scarlet Lines..without finishing previous ones...
Small note:
there may be small mistake... about How To Win Friends And Influence Enemies ... but i need to check it again.

**Comment by Grz3s** [comment]
ok....
look at this avi
https://www.youtube.com/watch?v=lt-E4KTB6oI   from 6:42
it shows all 3 quests...
and then he finishes [55] Nowhere To Run And Nowhere To Hide  and recived [55] How To Win Friends And Influence Enemies without finishing ... other 2.
so my fix is correct:
Behind Scarlet Lines is available only after player will finish:
How To Win Friends And Influence Enemies
Noth's Special Brew
Lambs To The Slaughter
