### ISSUE TITLE
City guards are hostile to new DKs

### ISSUE THREAD

**Issue by zimms** [unified-db/Database#76]
After Darion sends you to Stormwind/Ogrimmar, you are supposed to deliver a letter to Varian/Thrall.  However, this is made difficult (to put it lightly) due to the city guards being hostile, attacking you on sight.

(The prereq quest "The Light of Dawn" is also broken due to a few things, preventing DKs from finishing the questline normally, but I'm assuming that part is still WIP)

This seems like a DB issue, feel free to close if not..

**Comment by Grz3s** [comment]
Hi
Yes ... Final Phase for DK is still WIP.. 
should be finished soon.

**Comment by Grz3s** [comment]
We req. fix for spell:
58530 .. that works only for first 4 secs: and than breaks...
Reason of this ... is his:
```code
Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 4000
   Trigger spell (58533) Return to Stormwind. Chance = 101
```
this part should search for all creatures in range =20 ... and force them to react agains our player (or text or cast spell - this can be done via EAI)

Same situation happens on horde ver...
This req. @xfurry 's or @kvipka 's knowledge

**Comment by xfurry** [comment]
What is spell 58533 supposed to do?
What do you mean "react against our player"?

**Comment by Grz3s** [comment]
spell 58533 ... targets everyone in range of 20yards...(every 4 secs)
you can see here:
```code
ServerToClient: SMSG_SPELL_GO (0x1161) Length: 155 ConnIdx: 3 
(Cast) CasterGUID: Full: 0x081110000000000000000000069C782D Player/0 R1092/S0 Map: 0 Low: 110917677
(Cast) CasterUnit: Full: 0x081110000000000000000000069C782D Player/0 R1092/S0 Map: 0 Low: 110917677
(Cast) SpellID: 58533 (58533)
... -- not important
(Cast) [0] HitTarget: Full: 0x1C3A0400000011000000400003DAF723 Creature/0 R3713/S64 Map: 0 Entry: 68 Low: 64681763
(Cast) [1] HitTarget: Full: 0x1C3A04000000110000004000025AF72C Creature/0 R3713/S64 Map: 0 Entry: 68 Low: 39515948
(Cast) [2] HitTarget: Full: 0x0811100000000000000000000524D314 Player/0 R1092/S0 Map: 0 Low: 86299412
```
We can see here
spell catches:
entry 68 - guard
and another player

and As a reaction:
guards will:
- throw banana or apple + texts(cast spells like this one: 58513 Rotten Banana Toss)
that part can be done by acid:
cast spell on spell hit...

**Comment by xfurry** [comment]
@Grz3s I think we need the following:
1. Spell script target for 58533 on the City Guards.
2. a positive exception for 58533 (maybe)
3. Spell script for 58533 to make the target cast 58513

Can you please try this and let me know if it works.

**Comment by Grz3s** [comment]
```quote
2. a positive exception for 58533 (maybe)
```
can you explain this one?

**Comment by xfurry** [comment]
> can you explain this one?

Same like https://github.com/cmangos/mangos-wotlk/commit/26eeb6afd738671cc9b254880e8ddf6887330028 but returning a positive result.

**Comment by Grz3s** [comment]
After seting target for spell... our player is not attacked by anything else ... only by that target.
So now we know... that spell 58533...makes aggro on us...
```qoute
2. a positive exception for 58533 (maybe) 
``` 
Didnt help .. they will still aggro us.

another problem:
I wanted to use EAI to create reaction after spell hit.. but all guards in SW using sd2 scripts....
So reaction for our targets need to be done... in diff way:
- somehow we need to "target" - react passive (can give list with all spells)
- cast one of few random spells + text (can give all texts)
Can we make a fix in core for this?

**Comment by xfurry** [comment]
> Can we make a fix in core for this?

I will investigate when I'm back from holiday.
Just note that next week I'll be on holiday without access to internet or phone. (I'm going wild :smile: )

**Comment by Rushor** [comment]
without access to internet or phone. -> holy jesus, could'nt live like that :D but your motivation to fix great things after it will be 500% xD

**Comment by xfurry** [comment]
Here is your solution:
1. Check the spell_area entries for 58530 and 58551. I'm not sure if currently that is correct as I couldn't cast those spells anywhere. I just deleted the records to be able to test.
2. Add script targets for 58533 and 58552 to target city guards and city royal guards (you should see it in sniff / video)
3. Use the following core patches:
```diff
@@ -688,10 +688,12 @@ bool IsPositiveEffect(SpellEntry const* spellproto, SpellEffectIndex effIndex)
                 case 37388:                                 // Move 2
                 case 45863:                                 // Cosmetic - Incinerate to Random Target
                 case 49634:                                 // Sergeant's Flare
                 case 54530:                                 // Opening
                 case 56099:                                 // Throw Ice
+                case 58533:                                 // Return to Stormwind
+                case 58552:                                 // Return to Orgrimmar
                 case 62105:                                 // To'kini's Blowgun
                 case 63745:                                 // Sara's Blessing
                 case 63747:                                 // Sara's Fervor
                 case 64402:                                 // Rocket Strike
                     return true;

```
```diff
@@ -2705,10 +2705,20 @@ void Spell::EffectDummy(SpellEffectIndex eff_idx)
                     break;
                 }
                 case 58418:                                 // Portal to Orgrimmar
                 case 58420:                                 // Portal to Stormwind
                     return;                                 // implemented in EffectScript[0]
+                case 58533:                                 // Return to Stormwind
+                case 58552:                                 // Return to Orgrimmar
+                {
+                    if (!unitTarget)
+                        return;
+
+                    unitTarget->CastSpell(m_caster, urand(0, 1) ? 58509 : 58513, true);
+                    // only break so that we can handle the texts in dbscript
+                    break;
+                }
                 case 58601:                                 // Remove Flight Auras
                 {
                     m_caster->RemoveSpellsCausingAura(SPELL_AURA_FLY);
                     m_caster->RemoveSpellsCausingAura(SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED);
                     return;
```
4. Add dbscript_on_spell to handle texts that should be yelled by the guards.
5. Done!

**Comment by Grz3s** [comment]
@xfurry youre genius....
it works.. 
```quote
1. Check the spell_area entries for 58530 and 58551. I'm not sure if currently that is correct as I couldn't cast those spells anywhere. I just deleted the records to be able to test.
```
yes both spells has info in spell_area... but its correct and works fine...

```quote
2. Add script targets for 58533 and 58552 to target city guards and city royal guards (you should see it in sniff / video)
``` 
This will be done ... via DB.. and also script for quest completed

Got only problem with ... random texts:
in DB i can use only 4 random texts...
here we have:
```sql
(2000000563,'Monster!',0,0,0,0,NULL),
(2000000564,'Murderer!',0,0,0,0,NULL),
(2000000565,'GET A ROPE!',0,0,0,0,NULL),
(2000000566,'How dare you set foot in our city!',0,0,0,0,NULL),
(2000000567,'You disgust me.',0,0,0,0,NULL),
(2000000568,'Looks like we\'re going to have ourselves an execution.',0,0,0,0,NULL);
```
and ... they shouldnt be said everytime... 
Also i cant use acid (can be done there) becouse guards have ds2 scripts.
So i just Wonder... whats better:
1.
Use only 4 texts and make tchem random - easiest way (can be done in few secs)
2.
You'll add these texts in core/sd2 scripts? with 75% Chance?
3.
Somehow we will use fields like x,x,z,o -- for more texts ??

pls tell me what you think about it?

Anyway... i think there will be one more problem on the end of this q... but lets leave it.. for a bit :)
Waiting for respond...
thx

**Comment by Rushor** [comment]
the whole script_text stuff can be converted to the creature_text from trinitycore maybe, there we have groupids and ids

f.ex:
```sql
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES 
(3627, 0, 0, 'Magical studies stressing your brain? Relax at the Blue Recluse!', 12, 7, 100, 0, 0, 0, 1197, 0, 'Erich Lohan');
(3627, 0, 1, 'Best drinks in Stormwind!', 12, 7, 100, 0, 0, 0, 1195, 0, 'Erich Lohan');
(3627, 0, 2, 'Come for the beer, stay for the atmosphere!', 12, 7, 100, 0, 0, 0, 1196, 0, 'Erich Lohan');
(3627, 0, 3, 'The only place in Stormwind where magic and spirits mix, come to the Blue Recluse!', 12, 7, 100, 0, 0, 0, 1198, 0, 'Erich Lohan');
(3627, 0, 4, 'Free drinks at the Blue Recluse!', 12, 7, 100, 0, 0, 0, 1193, 0, 'Erich Lohan');
(3627, 0, 5, 'Feeling blue? Come on down to the Blue Recluse for a good time!', 12, 7, 100, 0, 0, 0, 1199, 0, 'Erich Lohan');
(3627, 0, 6, 'Head on over to the Blue Recluse. Where everybody knows your name!', 12, 7, 100, 0, 0, 0, 1194, 0, 'Erich Lohan');
```

in the script you would call that the creature should talk the text with `groupid`. all texts in `id` which are assigned with `groupid` 0 will randomly be spoken. pretty nice and useful, maybe this can be backported

**Comment by Schmoozerd** [comment]
hmm, maybe using sd2 is reasonable here (Especially to get the required randomness how frequent a npc should say this)
Alternative might be using the dummy-spell(s)
In theory there should also be the option with SpellHitTarget and a chance, not sure what eventAI will support here.

**Comment by Grz3s** [comment]
``` quote
In theory there should also be the option with SpellHitTarget and a chance, not sure what eventAI will support here.
```
this option cannot be used here becouse of sd2 script for guards...

**Comment by Schmoozerd** [comment]
We really still use SD2 for guards?
Well, then use a SD2 solution :)

**Comment by xfurry** [comment]
Ok, I forgot that we have the guards scripted in SD2.
I think we can use SD2 for this whole thing + the positive exception in the core.

@Grz3s let me know the text chance and the spell chance that we need to use.

**Comment by Grz3s** [comment]
ok this should be all you need... 
http://paste2.org/kxdLA8mY

**Comment by xfurry** [comment]
Well, of course we have some kind of problem with the guards...
Currently only these creatures are scripted as guards:
```sql
UPDATE creature_template SET ScriptName='guard_orgrimmar' WHERE entry=3296;
UPDATE creature_template SET ScriptName='guard_stormwind' WHERE entry IN (68,1976);
```

Which isn't covering all the creatures that we want for our event.

First I think we need to understand why aren't the other guards included in the scripts. If there is any solid reason for this, then we need to find a workaround.

**Comment by xfurry** [comment]
And another question:
@Grz3s from your note I would understand that the spell effect can be either one of the 3 spells + text emote, or any of the other 8 texts. 
So that means one random action out of 11, right?

**Comment by Grz3s** [comment]
yes

**Comment by xfurry** [comment]
@Grz3s here is the implementation:
core:
```diff
@@ -688,10 +688,12 @@ bool IsPositiveEffect(SpellEntry const* spellproto, SpellEffectIndex effIndex)
                 case 37388:                                 // Move 2
                 case 45863:                                 // Cosmetic - Incinerate to Random Target
                 case 49634:                                 // Sergeant's Flare
                 case 54530:                                 // Opening
                 case 56099:                                 // Throw Ice
+                case 58533:                                 // Return to Stormwind
+                case 58552:                                 // Return to Orgrimmar
                 case 62105:                                 // To'kini's Blowgun
                 case 63745:                                 // Sara's Blessing
                 case 63747:                                 // Sara's Fervor
                 case 64402:                                 // Rocket Strike
                     return true;
```

SD2: http://paste2.org/GHA5EaKD

Kindly let me know if this is what we want.
I think that we need to add some more random chance for the events, as it looks a little strange triggering some action on all guards on every spell hit.

**Comment by Grz3s** [comment]
@xfurry not sure if im missing smth.. but .. it doesnt work for me:
- above 2 lines added into SpellMgr.cpp
- whole sd2 patch added using "patch -p1 < patchfile" and patch was added without any problem (checked in guards file...)
So compilation completed without any problems...
made fresh imports: scriptdev2_script_full and into mangos..

And result:
guards not doing anything... just standing (not attacking player anymore - thats good) ,,, but whole random thing ..doesnt work...
What im missing there???
targets in scripts?

**Comment by xfurry** [comment]
> What im missing there???

You need to run the spell_script_target update that you provided.

**Comment by Grz3s** [comment]
```quote
Kindly let me know if this is what we want.
 I think that we need to add some more random chance for the events, as it looks a little strange triggering some action on all guards on every spell hit.
```
Are u suprised ... with amount of texts or spells there?? :)...
I should record you.. when i was staing on middle of "Trade district" -- anoying everybody there ehehe;]
99% players will use mount .. so you wont see that many "actions"
For me.... it works perfect so far.

BTW:
Pls dont forget to add:
-- 58509  -- > this should trigger 58511 on player (need to be fixed) 
-- 58513  -- > this should trigger 58514 on player (need to be fixed) 
-- 58520  -- > this should trigger 58519 on player (need to be fixed)
Also:
58511,58514,58519 -- should have a negative effect on player so:
-- we need to add in SpellMgr.cpp
```code
                    // dummy aura can be positive or negative dependent from casted spell
                    switch (spellproto->Id)
                    {
                        case 13139:                         // net-o-matic special effect
                        case 23445:                         // evil twin
                        case 35679:                         // Protectorate Demolitionist
                        case 37695:                         // Stanky
                        case 38637:                         // Nether Exhaustion (red)
                        case 38638:                         // Nether Exhaustion (green)
                        case 38639:                         // Nether Exhaustion (blue)
                        case 11196:                         // Recently Bandaged
                        case 44689:                         // Relay Race Accept Hidden Debuff - DND
+			  case 58511:				// Rotten Apple Aroma
+			  case 58514:				// Rotten Banana Aroma
+			  case 58519:                         	// Spit
			case 58600:                         // Restricted Flight Area
```

**Comment by Rushor** [comment]
assignement pingopong - yeah :D

**Comment by Grz3s** [comment]
heavy finger ;)

**Comment by xfurry** [comment]
> Pls dont forget to add:
> -- 58509 -- > this should trigger 58511 on player (need to be fixed) 
> -- 58513 -- > this should trigger 58514 on player (need to be fixed) 
> -- 58520 -- > this should trigger 58519 on player (need to be fixed)

This already works (or it should). Not sure what is the problem...
```
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
   Trigger spell (58511) Rotten Apple Aroma. Chance = 101
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
   Trigger spell (58514) Rotten Banana Aroma. Chance = 101
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
   Trigger spell (58519) Spit. Chance = 101
```

> 58511,58514,58519 -- should have a negative effect on player so:

Do you mean that the debuff can't be removed by click?

**Comment by Grz3s** [comment]
problem with first 3 spells - they're not casted on player. (dont know why)
Also:
they should be with red frame... so u cannot remove them (like that stanky one u accepted few weeks ago) - currently has blue frame .. like buff.
good example here:
https://www.youtube.com/watch?v=yFOkqJWtUtU -- 6:29

**Comment by xfurry** [comment]
Ok, I understand.
I will check why the spells are not triggering right.

**Comment by xfurry** [comment]
@Grz3s there you go: http://paste2.org/hNKCzP9W
Let me know if this fixed the issue. I think it should also fix a lot of other spells.

**Comment by Grz3s** [comment]
yes it fixes that problem ;)
also... debuff works fine ;)

P.S
only small strange thing... If u have on yourself example:
rotten banana
and they will cast it again ... it should just renew timer.. on it...
We have situation where another debuff stack on player ... so u can end up with "few" debuffs on yourself..
not a big issue.. koz they will dissapear in 40 secs... but... just to let u know..
Anyway we are almost finished with this quest :)

**Comment by xfurry** [comment]
Well, there are a bunch of problems with that dummy aura.
1. If I set it as negative, it will set the player in combat with the guard. So I won't add the negative effect now in order to not cause any problems
2. The auras should be replaced independent of the caster. Currently the aura stacking is a piece of crap, so I don't know which is the best way to repair this.

In conclusion, let's just make the event work as it is, and worry about the stacking and negative effect later.

**Comment by Grz3s** [comment]
:+1:  thx @xfurry for great job here ;)

**Comment by Tauriella** [comment]
Yea thx to all Dev's here nice Job :+1:
