### ISSUE TITLE
Quest 12801 The Light of Dawn

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#77]
The Event stopt if the fight is over

**Comment by Grz3s** [comment]
thanks for report
hmm
Script is made by sd2... not much can be done by DB...
anyway... i tested it few Times... and it never happened that event stoped .. 
I'll do more tests and we'll see..

**Comment by Tauriella** [comment]
Grz3s i must say THANKS YOU AGAIN for your TIME
It my mistake again grrrrr
I must from Time to Time my PC reset :( my Memory was full  "damned Windows"
I shame me
Works fine again

Thanks you for your great Job on your Database

**Comment by Tauriella** [comment]
Damn the Bug is return :(
Memory 16GB and Server runs ~1hour
If the fight is over 
Resul:Event stoped 

Now i stop the Server and start at new and ist works  (Confused Bug)

@xfurry can you Help for this issue please

**Comment by Grz3s** [comment]
hmm will try to find out ..whats going on there....

**Comment by Argonn** [comment]
Also occurred on our server, when I started (and ended) the event, the fight didn't reset. And the next DK awaiting his time in Azeroth couldn't progress.

**Comment by Tauriella** [comment]
Thanks you for comfirm

**Comment by Grz3s** [comment]
ok i did many tests with this script and I can confirm 2 problems:
1st - critical
After event completed... event should restart.
All creatures involved should be despawned after 5 idle mins... and then respawn stright after that on theirs spawn point.. to allow other players ... do this quest.
What happens now:
Well... we can see ... almost all npc despawns.. after X-time... except one (the most important one)
C. 29173 - Highlord Darion Mograine.
He will stay there forever...(until server restart) ... We need to fix this:

2nd - low lvl issue.
Moment, when all fight stops... and all DK-s a transported by spell....Highlord Darion Mograine .. should unmount...and stay unmounted ...until respawn... 
When i started redoing whole ... DK zone... he was unmounted on spawn (so i had to give him his horse) . Im sure whoever did this script... didnt notice that...and made it..without his mount ..

And now... becouse whole script is made by Scriptdev2... i cant fix both of these 2 issues... by DB scripts...
We need to ask.. @xfurry  if he can fix this for us. please.

**Comment by Grz3s** [comment]
fixed
