### ISSUE TITLE
New Avalon Registry ( Item 190947 )

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#80]
New Avalon Registry have no respawntime on BlizzServer
Spawnt instant return

**Comment by Grz3s** [comment]
so we taking this book or not? :)
.. kidding:)
We can set respawntime = 1. this will give that effect

**Comment by Tauriella** [comment]
I have testet withe 2 Sec and it is closer to Liveserver
-- New Avalon Registry
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 66384;
