### ISSUE TITLE
Spawn of Dimensius

### ISSUE THREAD

**Issue by Ulduar** [unified-db/Database#83]
http://www.wowhead.com/npc=21780/spawn-of-dimensius
Should have react state passive.
Suggested update
1) Db side:
``` SQL
UPDATE `creature_template` SET `AIName` = 'NullAI', `ScriptName` = '' WHERE `entry` IN (21780);
```
2) Or SD2 side:
``` diff
/*######
## npc_spawn_of_dimensius
######*/ 

struct npc_spawn_of_dimensiusAI : public ScriptedAI
{
    npc_spawn_of_dimensiusAI (Creature* pCreature) : ScriptedAI(pCreature) { Reset(); }
    
    void Reset() override { }
    void AttackStart(Unit* /*pWho*/) override { }
    void MoveInLineOfSight(Unit* /*pWho*/) override { }
    void UpdateAI(const uint32 /*uiDiff*/) override { }
    void EnterEvadeMode() override { }
    
};
```
3) EAI - i don't know - need action SET_REACT_STATE.

**Comment by Grz3s** [comment]
Thx for this report 
I can confirm what u said above...Found this ..where this is proven:
 https://www.youtube.com/watch?v=hYAsLJs9v18
Your script with "NullAI' works perfectly fine... but it need to be set by ACID .. not by DB.
Also... i noticed that ... theirs movement need to be changed to idle.. and then we can see that channeling spell..
So: (UDB) req. 2 scripts here:
DB:
```sql
UPDATE creature_template SET MovementType = 0 WHERE entry = 21780;
```
ACID:
```code
UPDATE creature_template SET AIName='NullAI' WHERE `entry` = '21780';
```
