### ISSUE TITLE
Quest 12288 Overwhelmed!

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#85]
Overwhelmed! ( Horde ) Quest
The Questcounter does not works

**Comment by xfurry** [comment]
Requires spell script for http://www.wowhead.com/spell=48812/renew-skirmisher
It's pretty easy to fix.

**Comment by Grz3s** [comment]
Thanks for report
will fix this soon

**Comment by Tauriella** [comment]
Thank you :+1:
