### ISSUE TITLE
Dark Rider of Archerus

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#87]
Dark Rider of Archerus dont stand still if attack you, and from time to time makes a Client Crash
Example:
You attack an DarkRider  with DeathGrip the Mob vanish you attack the next DarkRider and the Client crasht at anytime

**Comment by Grz3s** [comment]
confirmed...
I knew that we have a problem there... but i didnt know that it makes client freeze..
What i know so far:
- conection betwen horse and rider is done by sd2 script...(will be hard for DB to fix it)
- giving movementType =1 or 2... to horse... makes rider not able to aggro player..( I know what mistake i made there... and i'll look at this once again)
- Vehicle system may have some internal problems itself...I'll create new post on cmangos forum soon about that.

Anyway:
I'll try to find out... what is going on. and whats can be done there.

**Comment by Grz3s** [comment]
problem is ...with DarkRider.. he must take control on vehicle...
I tried everything i know:
- set link (between him and horse) - didnt work
- tried to use spell ..to control vehicle .. -- didnt work
etc...
I gave up... 
Maybe @xfurry and sd2 can do smth about it.
btw:
this may help:
``` code
ServerToClient: SMSG_AURA_UPDATE (0x091C) 
UpdateAll: True
UnitGUID: Full: 0x2039244C201C1B8000000300005E2027 Vehicle/0 R3657/S3 Map: 609 Entry: 28782 Low: 6168615
AurasCount: 1
[0] Slot: 0
[0] HasAura: True
[0] SpellID: 46598 (46598)
[0] Flags: Positive (2)
[0] ActiveFlags: 1
[0] CastLevel: 55
[0] Applications: 0
[0] Int56 Count: 0
[0] Effect Count: 0
[0] HasCastUnit: True
[0] HasDuration: False
[0] HasRemaining: False
[0] CastUnit: Full: 0x1C39244C201C180000000300005E2027 Creature/0 R3657/S3 Map: 609 Entry: 28768 Low: 6168615

ServerToClient: SMSG_AURA_UPDATE (0x091C) 
UpdateAll: True
UnitGUID: Full: 0x1C39244C201C180000000300035AF695 Creature/0 R3657/S3 Map: 609 Entry: 28768 Low: 56293013
AurasCount: 2
[0] Slot: 0
[0] HasAura: True
[0] SpellID: 46598 (46598)
[0] Flags: NoCaster, Positive (3)
[0] ActiveFlags: 2
[0] CastLevel: 55
[0] Applications: 0
[0] Int56 Count: 0
[0] Effect Count: 0
[0] HasCastUnit: False
[0] HasDuration: False
[0] HasRemaining: False
[1] Slot: 1
[1] HasAura: True
[1] SpellID: 52370 (52370)
[1] Flags: NoCaster, Positive (3)
[1] ActiveFlags: 1
[1] CastLevel: 55
[1] Applications: 0
[1] Int56 Count: 0
[1] Effect Count: 0
[1] HasCastUnit: False
[1] HasDuration: False
[1] HasRemaining: False
```

**Comment by Grz3s** [comment]
UPDATE:
after more search, i've found that we have 2 problems here:

1. VehicleTemplateID = 135 - is correct (sniff)
- problem with "VehicleTemplateID = 135" - with this one ... horse will  never take aggro on us (and yes he should aggro - on avis u can see that he does dmg also) We can simply change that vehTempID to =110 ... and he will aggro.... 

2. UnitFlags = 33587200 (correct sniffed flag for horse) = contain 2 flags 0x2000000 and 0x8000..
0x2000000 = non selectable.. creates problem here... any creature with this flag.. wont do anything ..
not even respond on aggro..Ofc. we can ask... "how can you attack someone that has this flag, becouse u cant even select him" ... well ... i tried link rider(master) and horse(slave) and give flag = 1
slave will aggro on masters aggro... but it wont work :(

So only option here...is sd2 script... for rider... and take control on horse ..
I saw trinitycore made script for rider to control horse... maybe this could help ..also...

Difficult one...

**Comment by Tauriella** [comment]
Nice Job Grz3s

**Comment by xfurry** [comment]
> Difficult one...

This is indeed difficult.
Currently the core doesn't support vehicles that are controlled by creatures. We should have that, but it's not very straight forward. I will try to see what can be done in SD2 with this.

For the client freeze, it happens to all vehicles that have accessories loaded from DB.
I couldn't find the exact root cause of this, but if someone can hand some help here, I'm sure we can get it fixed.

**Comment by Tauriella** [comment]
Is the Code from TrinityCore possible ?

**Comment by xfurry** [comment]
> Is the Code from TrinityCore possible ?

Maybe. But I need to understand why is the client freezing. And this is the most difficult part.

**Comment by Tauriella** [comment]
Now i have TrinityCore335 for test purposes installed
Result:
Trinity have the same Problems as Mangos with mountet NPC's with Waypoints but it makes no Client freez

**Comment by xfurry** [comment]
Yes, I also noticed that WP vehicles with accessories installed do this client freeze, after they complete a full WP circle

**Comment by xfurry** [comment]
I tried to do more digging into the client freeze problem and I finally got this:

```
2015-08-01 16:05:58 Send all time packets count: 277 bytes: 22726 avr.count/sec: 1.#INF00 avr.bytes/sec: 1.#INF00 time: 0
2015-08-01 16:05:58 Send last min packets count: 277 bytes: 22726 avr.count/sec: 4.616667 avr.bytes/sec: 378.766667
```

I'm not sure if this is related to our issue, but it might be.
What I also noticed is that the freeze only happens when the accessories of a vehicle are first loaded and boarded on the vehicle on grid load. Not sure if there are some movement sync problem here, but it might be the case.

Hope someone can help with some suggestions.

**Comment by Grz3s** [comment]
hey@ xfurry
I made some progres with this:
-- he shouldnt react for DeathGrip  -- so i made update already... (never had any crash since that)
Also:
Only for tests:
- I removed your sd2 patch:
```sql
UPDATE creature_template SET ScriptName = '' WHERE entry = 28782;
```
- and then I made 2 EAI scripts for both ... Rider and Horse:
```sql
-- Dark Rider of Acherus
Delete from `creature_ai_scripts` where `creature_id`= 28768;
Insert into `creature_ai_scripts` values 
('2876801','28768','30','0','100','0','5','28782','0','0','11','46598','10','6','1','0','0','0','0','0','0','0','Dark Rider of Acherus - cast Ride Vehicle Hardcoded on Recive event'),
('2876802','28768','4','0','100','0','0','0','0','0','1','-780','0','0','45','5','10','0','0','0','0','0','Dark Rider of Acherus - Send AI Event "A" and Yell on Aggro'),
('2876803','28768','0','0','100','1','0','1500','6000','9000','11','52372','1','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - Cast Icy Touch'),
('2876804','28768','0','0','100','1','3000','7000','6000','9000','11','50688','1','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - Cast Plague Strike'),
('2876805','28768','0','0','100','1','6000','10000','6000','9000','11','52374','1','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - Cast Blood Strike'),
('2876806','28768','9','0','100','1','5','30','2000','2000','11','52356','1','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - Cast Throw'),
('2876807','28768','6','0','100','0','0','0','0','0','45','6','10','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - Send AI Event "B" on Death');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '28768';

-- Acherus Deathcharger 
Delete from `creature_ai_scripts` where `creature_id`= 28782;
Insert into `creature_ai_scripts` values
('2878201','28782','11','0','100','0','0','0','0','0','45','5','10','0','0','0','0','0','0','0','0','0','Acherus Deathcharger  - Send AI Event on Spawn'),
('2878202','28782','8','0','100','1','46598','-1','0','0','48','0','0','0','0','0','0','0','0','0','0','0','Havenshire Colt - change MovementType to idle on SpellHIT'),
('2878202','28782','30','0','100','0','5','28768','0','0','19','33587200','0','0','48','0','0','0','0','0','0','0','Dark Rider of Acherus - Remove flag and change MovementType to idle on Recive event "A"'),
('2878203','28782','30','0','100','0','6','28768','0','0','2','35','1','0','48','0','0','0','0','0','0','0','Dark Rider of Acherus - set Faction and change MovementType to idle on Recive event "B"'),
('2878204','28782','21','0','100','0','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Dark Rider of Acherus - despawn on REACHED_HOME');
 UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '28782';
 -- link
DELETE FROM creature_linking_template WHERE entry = 28782;
INSERT INTO creature_linking_template (entry, map, master_entry, flag, search_range) VALUES    
(28782,609,28768,1,10);
```
We recived:
- horses with waypoints... will stop theirs movement...on aggro
- like sd2 script... horse will become friendly to us... and we can ride him after riders death
-- Also i confirmed that:
1.VehicleTemplateID = 135 .. is the main issue here
- even if i'll set his unit flags = 0, and faction = 16 (agressive) -- he still wont attack us., If i only change vehTemp to another one - then his aggro works fine...

I just Wonder... if we can ... do anything with vehicleids? (i mean if we can hardcode them)?
or change them if we need ?

any idea?

**Comment by FallenAngelX** [comment]
-- ** sql might be outdated , but old fix of mine a few months ago 
quest worked great
-- -------------------------------
-- Quest Into the Realm of Shadows
-- -------------------------------

-- Remove sd2 name setting from death charger
UPDATE `creature_template` SET `ScriptName` = '' WHERE `entry` = 28782;

-- Creature Template Stuff
UPDATE `creature_template` SET `unit_flags` = 0 WHERE `entry` = 28782;
UPDATE `creature_template` SET `faction_A` = 2082, `faction_H` = 2082 WHERE `entry` = 28782;

DELETE FROM `vehicle_accessory` WHERE  `vehicle_entry`=28782 AND `seat`=0;
DELETE FROM `creature_template_addon` WHERE (`entry`=28768);
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `b2_0_sheath`, `b2_1_pvp_state`, `emote`, `moveflags`, `auras`) VALUES (28768, 25445, 0, 0, 0, 0, 0, '');

UPDATE `npc_spellclick_spells` SET `cast_flags`=1 WHERE  `npc_entry`=28782;

-- Dark Rider ACID
DELETE FROM `creature_ai_scripts` WHERE (`creature_id`=28768);
INSERT INTO `creature_ai_scripts` VALUES 
( 2876803, 28768, 0, 0, 100, 1, 3000, 7000, 6000, 9000, 11, 50688, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dark Rider of Acherus - Cast Plague Strike'),
( 2876806, 28768, 6, 0, 100, 0, 0, 0, 0, 0, 11, 52361, 6, 16, 11, 52357, 6, 16, 0, 0, 0, 0, 'Dark Rider of Acherus - Spawn Deathcharger of Acherus and Set Quest Event Complete and Dismount on Death'),
( 2876801, 28768, 4, 0, 100, 0, 0, 0, 0, 0, 1, -780, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dark Rider of Acherus - Yell on Aggro'),
( 2876804, 28768, 0, 0, 100, 1, 6000, 10000, 6000, 9000, 11, 52374, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dark Rider of Acherus - Cast Blood Strike'),
( 2876802, 28768, 0, 0, 100, 1, 0, 1500, 6000, 9000, 11, 52372, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dark Rider of Acherus - Cast Icy Touch'),
(2876805, 28768, 9, 0, 100, 1, 5, 30, 2000, 2000, 11, 52356, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Dark Rider of Acherus - Cast Throw');

-- update quest template a little bit here
UPDATE `quest_template` SET `SrcSpell` = 52359, `ReqCreatureOrGOId1` = 28768, `ReqCreatureOrGOCount1` = 1, `ReqSpellCast1` = 0 WHERE `entry` = 12687;
INSERT IGNORE INTO creature_involvedrelation (id, quest) VALUES (28788, 12687);
UPDATE creature_template SET npcflag = 2 WHERE entry = 28788;


-- not sure what the udb guids are but need UDB guids

-- Delete Spawns of DeathChargers ( the deathchrgers guids match the new dark rider spawns in clean YTDB so no conflict)

DELETE FROM `creature` WHERE id = 28782;
DELETE FROM `creature_template_addon` WHERE entry = 28782;
-- Spawn Dark Riders of archerus
DELETE FROM `creature` WHERE `id`=28768;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`DeathState`,`MovementType`) VALUES
(89574, 28768, 609, 1, 32, 0, 0, 2327.46, -5860.18, 100.94, 2.53, 300, 30, 0, 7842, 0, 0, 1),
(89575, 28768, 609, 1, 32, 0, 0, 2281.5, -5847.78, 100.93, 2.19, 300, 30, 0, 7842, 0, 0, 1),
(89576, 28768, 609, 1, 32, 0, 0, 2252.86, -5880.67, 101.14, 4.24, 300, 30, 0, 7842, 0, 0, 1),
(89577, 28768, 609, 1, 32, 0, 0, 2206.94, -5919.25, 101.13, 2.83, 300, 30, 0, 7842, 0, 0, 1),
(89578, 28768, 609, 1, 32, 0, 0, 2162.25, -5895.19, 101.3, 2.59, 300, 30, 0, 7842, 0, 0, 1),
(89579, 28768, 609, 1, 32, 0, 0, 2146.42, -5837.14, 101.31, 2.48, 300, 30, 0, 7842, 0, 0, 1),
(89580, 28768, 609, 1, 32, 0, 0, 2161.78, -5793.11, 100.85, 0.74, 300, 30, 0, 7842, 0, 0, 1),
(89581, 28768, 609, 1, 32, 0, 0, 2195.46, -5763.84, 101.51, 5.76, 300, 30, 0, 7842, 0, 0, 1),
(89582, 28768, 609, 1, 32, 0, 0, 2239.68, -5788.27, 101.11, 2.2, 300, 30, 0, 7842, 0, 0, 1),
(89583, 28768, 609, 1, 32, 0, 0, 2117.98, -5754.23, 98.71, 2.72, 300, 30, 0, 7842, 0, 0, 1),
(89584, 28768, 609, 1, 32, 0, 0, 2086.45, -5786.83, 100.97, 4.86, 300, 30, 0, 7842, 0, 0, 1),
(89585, 28768, 609, 1, 32, 0, 0, 2081.43, -5837.9, 103.69, 5.11, 300, 30, 0, 7842, 0, 0, 1),
(89586, 28768, 609, 1, 32, 0, 0, 2276.81, -6109.68, 5.43, 5.43, 300, 30, 0, 7842, 0, 0, 1),
(89587, 28768, 609, 1, 32, 0, 0, 2246.27, -6139.44, 2.67, 3.85, 300, 30, 0, 7842, 0, 0, 1),
(89588, 28768, 609, 1, 32, 0, 0, 2205.61, -6127.75, 5.03, 2.2, 300, 30, 0, 7842, 0, 0, 1),
(89589, 28768, 609, 1, 32, 0, 0, 2213.68, -6079.06, 4.13, 2, 300, 30, 0, 7842, 0, 0, 1),
(89590, 28768, 609, 1, 32, 0, 0, 2163.42, -6072.82, 5.54, 3.79, 300, 30, 0, 7842, 0, 0, 1),
(89591, 28768, 609, 1, 32, 0, 0, 2141.65, -6110.49, 3.8, 3.99, 300, 30, 0, 7842, 0, 0, 1),
(89592, 28768, 609, 1, 32, 0, 0, 2107.47, -6127.09, 6.81, 3.03, 300, 30, 0, 7842, 0, 0, 1),
(89593, 28768, 609, 1, 32, 0, 0, 2113.17, -6067.31, 5.02, 2.32, 300, 30, 0, 7842, 0, 0, 1),
(89594, 28768, 609, 1, 32, 0, 0, 1908.47, -5960.74, 100.98, 2.75, 300, 30, 0, 7842, 0, 0, 1),
(89595, 28768, 609, 1, 32, 0, 0, 1938.95, -5922.41, 102.39, 1.1, 300, 30, 0, 7842, 0, 0, 1),
(89596, 28768, 609, 1, 32, 0, 0, 2000.87, -5908.94, 104.13, 0.05, 300, 30, 0, 7842, 0, 0, 1),
(89597, 28768, 609, 1, 32, 0, 0, 2000.42, -5856.61, 100.74, 2.25, 300, 30, 0, 7842, 0, 0, 1),
(89598, 28768, 609, 1, 32, 0, 0, 2014.37, -5809.11, 100.54, 1.81, 300, 30, 0, 7842, 0, 0, 1),
(89599, 28768, 609, 1, 32, 0, 0, 1959.71, -5810.86, 101.15, 2.63, 300, 30, 0, 7842, 0, 0, 1),
(89600, 28768, 609, 1, 32, 0, 0, 1967.38, -5753.68, 100.91, 2.62, 300, 30, 0, 7842, 0, 0, 1),
(89601, 28768, 609, 1, 32, 0, 0, 1870.54, -5859.3, 103.07, 3.92, 300, 30, 0, 7842, 0, 0, 1),
(89602, 28768, 609, 1, 32, 0, 0, 1868.75, -5913.9, 104.14, 3.33, 300, 30, 0, 7842, 0, 0, 1),
(89603, 28768, 609, 1, 32, 0, 0, 1813.23, -5932.86, 114.77, 3.34, 300, 30, 0, 7842, 0, 0, 1),
(89604, 28768, 609, 1, 32, 0, 0, 1767.03, -5921.69, 116.12, 2.91, 300, 30, 0, 7842, 0, 0, 1),
(89605, 28768, 609, 1, 32, 0, 0, 1716.41, -5927.23, 118.89, 3.57, 300, 30, 0, 7842, 0, 0, 1),
(89606, 28768, 609, 1, 32, 0, 0, 1697.58, -5887.86, 116.15, 1.9, 300, 30, 0, 7842, 0, 0, 1),
(89607, 28768, 609, 1, 32, 0, 0, 1677.37, -5835.38, 116.15, 2.43, 300, 30, 0, 7842, 0, 0, 1),
(89608, 28768, 609, 1, 32, 0, 0, 1683.29, -5783.39, 115.26, 1.59, 300, 30, 0, 7842, 0, 0, 1),
(89609, 28768, 609, 1, 32, 0, 0, 1729.95, -5744.53, 111.44, 0.46, 300, 30, 0, 7842, 0, 0, 1),
(89610, 28768, 609, 1, 32, 0, 0, 1566.04, -5796.96, 119.53, 3.42, 300, 30, 0, 7842, 0, 0, 1),
(89611, 28768, 609, 1, 32, 0, 0, 1619.05, -5881.41, 115.71, 6.11, 300, 30, 0, 7842, 0, 0, 1),
(97735, 28768, 609, 1, 32, 0, 0, 2058.19, -5744.74, 98.55, 0.4, 300, 30, 0, 7842, 0, 0, 1);

**Comment by Grz3s** [comment]
Hey @FallenAngelX 
Your script.. makes .. rider and horse work together,,,but:
- you skipping almost half... of that q. ( quest shouldnt autocomplete itself ..after killing Rider)
Horse should become available for player .. Also... after delivering it .. to quest Salanar.. you will recive small quest end event... etc...
UDB has all this done .. in correct way...
Anly problem for us is ..that Horse wont help rider with aggroing us...(not a big deal) .. only becouse VehicleTemplate =135 .. makes horse ..not aggresive .. (You just removed it) :)

BTW:
thanks for your script... it gave me few more ideas how we could fix above problem ;)

**Comment by Tauriella** [comment]
:100: :+1:

**Comment by FallenAngelX** [comment]
8) , just glad it works it was something that was thrown together to get a few private server owners to hush til a better fix came along lol , been thinking about getting back into development. was waiting for my old team R2 , but seems the project is dead 8(

**Comment by al3xc1985** [comment]
Why not step into cmangos and udb team?

**Comment by FallenAngelX** [comment]
honestly because cmangos is strict and whats to sit around and debate stuff til were blue in the face, im not against hard coded values and ect ect which is awesome if this was a paided company so few of us with very little time, like take this quest for example its still "Fixed" correct but in game quest works and is fine 80 but ya i would ove to join them in the near future , my time right now is none to almost little 8)

**Comment by al3xc1985** [comment]
hehe .. well I hope you will join sooon.  nice to hear from you that there is a moment when you will join. And I am sire that many features will be implemented in near future, but the right way...hehe joking
