### ISSUE TITLE
Quest Load'er Up! ( Quest 11881 )

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#89]
Jenny vanish from time to time.
Player can't complete the Quest

**Comment by Grz3s** [comment]
req. SD2 Script.
more info:
https://github.com/scriptdev2/scriptdev2/issues/176
im sure @xfurry shouldnt have problem with it ;)

**Comment by Grz3s** [comment]
hi @xfurry can this ticket be closed now??

**Comment by xfurry** [comment]
Hi @Grz3s 
Happy New Year!

From the script side this is fixed.
However, on the core side, we still need to address the issue that I described here: https://github.com/scriptdev2/scriptdev2/issues/176#issuecomment-143062439

So, we could close this, but @Tauriella might get back to us, saying that it doesn't work.

**Comment by Tauriella** [comment]
Hi
and Happy New Year! at all
Unfortunately, this quest is not working but you can close 
I hope cmangos Dev's fix this and many other Bugs.

**Comment by Grz3s** [comment]
Fixed:
https://github.com/cmangos/mangos-wotlk/commit/41e2481308312a8a8a51e6f6b217193456ddce41
