### ISSUE TITLE
Forum backup

### ISSUE THREAD

**Issue by HerrTrigger** [unified-db/Database#9]
This might be in vain, but nevertheless:

Can @arrai or @amki possibly make contact with someone from the UDB or CMangos dev team please?

Many great posts/links/ideas/tools etc were still there, and it would be a real pitty to see all these getting lost forever.

I for one, would be very grateful.
Hope to see this settled one day, cheers!  : )

**Comment by X-Savior** [comment]
I also have the new Domain Name that can be used for something new.

I have been sitting on the domain for a year and counting....

Anyone?

**Comment by al3xc1985** [comment]
any news with that forum backup?

**Comment by Grz3s** [comment]
ppl who has data .. are not interested anymore with it... so it looks like that our old data is lost:/

**Comment by al3xc1985** [comment]
2 bad because good fixes or reports  were left there

**Comment by Grz3s** [comment]
will never happen ;)

**Comment by HerrTrigger** [comment]
Well, browsing through my 'archive', I stumbled upon this one - UDB wiki save from 06/2010.
Perhaps this still might be of any use. :)
(Just open index.html with a browser)

http://s000.tinyupload.com/?file_id=01400128449420426622
