### ISSUE TITLE
Quest Taken by the Scourge ( Quest 11611 )

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#90]
If you destroy the Cocoon, nothing happens.

https://www.youtube.com/watch?v=b6mj-AUMSYI

**Comment by xfurry** [comment]
Need dbscript_on_creature_death or ACID for creature 25284.

**Comment by Grz3s** [comment]
Still two issues with this:
- Nerub'ar Victim - shouldn't react on Aggro.. I'm waiting for updated @xfurry's patch for ...ACTION_REACT_PASSIVE https://github.com/unified-db/Database/issues/147#issuecomment-156203171 ... it may solve this problem.

- all summoned guardians should have abilities + say texts..
I made scripts for all: http://paste2.org/Gz006thj
Unfortunately adding EAI to any of this creatures brakes them completely.. They will say texts on appear but ... they wont attack anyone/or follow player...
So I have no idea where this data (texts,abilities etc) should be stored for quardians...
Maybe one day we'll find out how to fix it correctly
