### ISSUE TITLE
Quest Bring 'Em Back Alive ( 11690 )

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#91]
You can sit on the Kodo , but the Kodo don't stand up an we can walk.

https://www.youtube.com/watch?v=82TqJnJ6GOA

**Comment by xfurry** [comment]
Requires some spell script for 45877 to handle quest credit / completion and also some way to enable creature movement on 25596 when vehicle mounted.
Maybe @Grz3s can tell us more.

**Comment by Grz3s** [comment]
im working on it right now :d

**Comment by Grz3s** [comment]
need a help with this one...
https://www.youtube.com/watch?v=82TqJnJ6GOA 0:35
U can see that spell 45877 (from vehicle spell list) is used.
From sniff i know ... that another spell is casted stright after this one:
spell = 48204 (and its casted by player on himself)

I need somehow ... to cast this spell...as effect of first one....
I tried everything using DBScripts and ACID.. cant catch player :/
So question is... can we use core ... to search for player (target_master ? or charmedby... ) and cast second spell on him?

**Comment by xfurry** [comment]
So spell 45877 has 3 effects:

* eff_0: has script effect. Can be handled in core and make the controlling player cast 48204 on self. Then you can handle spell 48204 by dbscripts_on_spell.
* eff_1: has script target to inform the quest giver. Can be handled by dbscripts_on_spell and can do texts.
* eff_2: gives quest credit to master (player controlling vehicle).

I will provide you the fix for eff_0 and you can handle the rest. Is that ok?

**Comment by xfurry** [comment]
@Grz3s please try to use this, I think it should work (untested).

```diff
@@ -8156,10 +8156,26 @@ void Spell::EffectScriptEffect(SpellEffectIndex eff_idx)
                         return;
 
                     unitTarget->CastSpell(unitTarget, 45836, true);
                     return;
                 }
+                case 45877:                                 // Deliver Kodo
+                {
+                    if (!unitTarget || unitTarget->GetTypeId() != TYPEID_UNIT || unitTarget->IsVehicle())
+                        return;
+
+                    // unboard player and cast spell 48204
+                    if (Unit* playerTarget = unitTarget->GetCharmerOrOwner())
+                    {
+                        if (playerTarget->GetTypeId() == TYPEID_PLAYER)
+                        {
+                            unitTarget->RemoveAurasDueToSpell(45875);
+                            playerTarget->CastSpell(playerTarget, 48204, true);
+                        }
+                    }
+                    return;
+                }
                 case 45892:                                 // Sinister Reflection
                 {
                     if (!unitTarget || unitTarget->GetTypeId() != TYPEID_PLAYER)
                         return;

```

**Comment by Grz3s** [comment]
your patch doesnt work....
but... did very good thing... mobilized me to recheck all again.. and i found missing link between vehicle and player:
spell: ID - 48203 Kodo Delivered
```code
Effect 0: Id 140 (SPELL_EFFECT_FORCE_CAST)
BasePoints = 1
Targets (27, 0) (TARGET_MASTER, NO_TARGET)
   Trigger spell (48204) Kodo Delivered. Chance = 101
```

i dont know how i missed it before :/
sory for making problem. :(

**Comment by Tauriella** [comment]
Nice Job guys i'm impress
Thank You!
