### ISSUE TITLE
Zul'Farrak Missing Exploanim...

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#93]
Weegli Blastfuse 
Missing barrel explosion animation when the doors is blown up

**Comment by xfurry** [comment]
I think it should work.
The GO has alternative animation which is handled by spell, using this effect https://github.com/cmangos/mangos-wotlk/blob/master/src/game/SpellEffects.cpp#L10172

I remember that it worked fine when I first implemented this.

**Comment by Grz3s** [comment]
confirmed..
Weegli's Armed Barrel object=141612 has spell: 11195
that will activate another object - destroy main gate (this part works fine)
only problem is with barrel itfelf...  should "blow up self".
look here: https://www.youtube.com/watch?v=Jy2v-ZhI4Vc  from 18:36 ( top right corner - can see barrel placed by goblin next to gate - and blow anim)

This part doesnt work... barrel will stay unaffected at all. 
I tried to use gameobject.cpp and add GetDisplayId() == 472.. 
``code
            // TODO: Improve this when more information is available, currently these traps are known that must send the anim (Onyxia/ Heigan Fissures/ Trap in DireMaul)
			if (GetDisplayId() == 472 || GetDisplayId() == 4392 || GetDisplayId() == 4472 || GetDisplayId() == 4491 || GetDisplayId() == 6785 || GetDisplayId() == 3073 || GetDisplayId() == 7998)
                SendGameObjectCustomAnim(GetObjectGuid());
``` 
but it didnt work also.. 
so no idea what else can be done here :)

**Comment by xfurry** [comment]
I will investigate. Maybe there is a logic mistake in core.

**Comment by xfurry** [comment]
Indeed, the barrel doesn't explode, even if we force the custom animation. No idea what the problem is....
