### ISSUE TITLE
Thrallmar cosmetic

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#95]
The Thrallmar Wolf Rider runs and not go  [Blizzlike]

Ps: Have you a example for me an i try to fix it

**Comment by Grz3s** [comment]
Well ... i had this done long time ago.. but it was never added.
reason for this is:
Creature_linking doesnt work "nice" with running creatures:
You can check it by yourself
``` sql
-- Thrallmar Wolf Rider
UPDATE creature_movement SET script_id = 1659901 WHERE id = 57597 AND point = 8;
UPDATE creature_movement SET waittime = 2000, script_id = 1659902 WHERE id = 57597 AND point = 36;
DELETE FROM dbscripts_on_creature_movement WHERE id IN (1659901,1659902); 
INSERT INTO dbscripts_on_creature_movement (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(1659901,1,25,1,0,0,0,0,0,0,0,0,0,0,0,0,'RUN ON'),
(1659902,1,25,0,0,0,0,0,0,0,0,0,0,0,0,0,'RUN OFF');
-- link
UPDATE creature SET MovementType = 2, spawndist = 0 WHERE guid = 57597;
UPDATE creature SET MovementType = 0, spawndist = 0 WHERE guid IN (57594,57595,57596);
DELETE FROM creature_linking WHERE guid IN (57594,57595,57596);
INSERT INTO creature_linking (guid, master_guid, flag) VALUES    
(57596,57597,515),
(57595,57597,515),
(57594,57597,515);
```

Pls comment ...

**Comment by Tauriella** [comment]
Yes it works, but she run not synchron and she turns around

**Comment by Grz3s** [comment]
and thats the reason why this was never added...
@Schmoozerd was a person who design whole linking stuff ... with flags follow etc..
and probably only he knows ... what may making this problem...
but he is not active anymore... so i dont expect that this will be fixed anytime soon.

**Comment by Schmoozerd** [comment]
creature linking is a high-level engine that relies on the movement generators. In this case the FollowMMGen.
This MMGen does not (yet) support speed/walk/run synchronisation, and hence this visual does not behave as desired.

**Comment by Grz3s** [comment]
https://youtu.be/JNhBlr71Lfs -- this is what happens..
looks like theyre not decided if they want to follow or not :)

**Comment by Schmoozerd** [comment]
as i say: this has nothing todo with the creature-linking engine, but with the underlying FollowMMGen.

CreatureLinking only does:
pFollower->MoveFollow(pLeader, DIST, ANGLE).
End of creature_linking :)

**Comment by al3xc1985** [comment]
If that so, why not add the fix to master?

**Comment by al3xc1985** [comment]
@Grz3s is this added to db?

**Comment by Grz3s** [comment]
7 years later :P
