### ISSUE TITLE
Missing and not working teleporter

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#96]
In Hellfire Peninsula this Gate to Orgimmar does not work .
The Portal in Orgrimmar to  Hellfire Peninsula is missing, stands near NPC Thuul

**Comment by Grz3s** [comment]
need more info..
```quote
In Hellfire Peninsula this Gate to Orgimmar does not work .
```
which gate?

**Comment by Tauriella** [comment]
![portaltoorgrimmar](https://cloud.githubusercontent.com/assets/10637389/9031208/95e4fe0c-39af-11e5-843b-a609c779aaec.jpg)
This is the Portal to Orgrimmar

**Comment by Grz3s** [comment]
ok ... i dont know about portal in Orgrimmar..
but I'm more than 100% sure... that... portal on 1st screenshot ..is not the one that u looking for...
Portal that u see there... is only for defenders ... that comes from it... to fight against Pit Lords army...
As player you shouldnt be able to even click on it

**Comment by Tauriella** [comment]
Now the Allianze Portal

![to_hellfire](https://cloud.githubusercontent.com/assets/10637389/9060081/b152a070-3ab0-11e5-813c-1a754cdac4b7.jpg)
to Hellfire
this Portal exist in the DB and works fine

![from_hellfire](https://cloud.githubusercontent.com/assets/10637389/9060087/c21056a0-3ab0-11e5-9194-46d2a4c843a6.jpg)
to Stormwind

Proof from LifeServer

**Comment by Tobschinski** [comment]
This is patch 6.x, isn't it?

**Comment by Grz3s** [comment]
as i said before....
i have very good source of these objects... and they're inded portals (visualy)... but not for players
.. Your portal to Orgrimmar in 3.x.x is named:
"Dark Assault - Horde Portal - Invisible stalker"  - and its used only as part of invasion event (not finished in UDB yet)
