### ISSUE TITLE
Scarlet Miner

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#98]
Scarlet Miner are not aggro on Blizz

**Comment by Grz3s** [comment]
yes you're right ..
- Citizen of Havenshire
- Scarlet Peasant
These should react simmilar....
And this is result of aura that is send from player every x secs... 
so... they all will react in few diff ways:
- react passive .. with fear emote
- take an aggro ..

Got some problems with it... but when i'll fix it..it will be added;)

**Comment by xfurry** [comment]
@Grz3s your description isn't clear. Is this related to spell or core, or just a DB issue?

**Comment by Grz3s** [comment]
will show more complex info soon*

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/wotlk-db/commit/cdf2eb1930fd4c8bd44ba2529ffe6e9fbbeeb7c5
