### ISSUE TITLE
Mature Netherwing Drake

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#99]
If you feeding a Mature Netherwing Drake then Comes to slowly from the Sky

**Comment by Grz3s** [comment]
flying speed = core issue
script with Drakes = made in sd2 
So you should create a issue there ;)

**Comment by xfurry** [comment]
This is scripted in SD2.
I don't understand the issue... Does it need to increase or decrease speed?

**Comment by Tauriella** [comment]
The Drakes flying general to slow, they need's more Speed for flying

**Comment by xfurry** [comment]
Does this fix the issue?

```diff
@@ -117,10 +117,11 @@ struct mob_mature_netherwing_drakeAI : public ScriptedAI
                     m_creature->GetMotionMaster()->MoveIdle();
 
                     float fX, fY, fZ;
                     pGo->GetContactPoint(m_creature, fX, fY, fZ, CONTACT_DISTANCE);
 
+                    m_creature->SetWalk(false);
                     m_creature->GetMotionMaster()->MovePoint(1, fX, fY, fZ);
                 }
                 m_uiEatTimer = 0;
             }
             else

```

**Comment by Tauriella** [comment]
Yes it works perfekt!
The Drakes Comes now with correct Speed from the Sky +1: 
BUT
Is the Drake landing on ground and fly in the Sky return is the Speed to slow again.

**Comment by Tauriella** [comment]
I have checked on Blizz and yes, from Ground to Sky is the same Speed as from Sky to Ground
